### ISSUE TITLE
panel reset fails on GTK+3.18

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#1020]
**Operating System**: Ubuntu 16.04
**Budgie version**: git master as of 08 Jul 17

**The issue encountered**

panel does not appear after running

    budgie-panel --reset--replace &

 ...

**Steps to reproduce the issue**

running the reset method shows in the terminal

displays "(budgie-panel:18500): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.interface' does not contain a key named 'show-battery-percentage'"

 ...

That key doesnt appear to be in GTK+3.18.  Maybe hide and don't bind in powerallocation.vala for GTK+3.18 ?

**Comment by ikeydoherty** [comment]
IDK what powerallocation.vala is.

**Comment by fossfreedom** [comment]
my mistake - src/applets/status/PowerIndicator.vala

**Comment by ikeydoherty** [comment]
K. Well hoping that commit fixes it. the `#ifdef` is a bit nasty but unavoidable really

**Comment by fossfreedom** [comment]
aye - it does.  thanks.
