### ISSUE TITLE
Budgie Desktop Settings doesn't work if Nautilus is uninstalled

### ISSUE THREAD

**Issue by Vistaus** [budgie-desktop/budgie-desktop#1029]
I notice that BSD crashes when Nautilus is not installed (it even drops an error about the Nautilus schema not being installed). I get that Nautilus is part of the default Solus application set, but shouldn't BDS work w/o Nautilus as well?

**Comment by Vistaus** [comment]
That was fast :P

**Comment by Vistaus** [comment]
Btw, I can confirm the fix works, thank you! 😸

**Comment by ikeydoherty** [comment]
xD np
