### ISSUE TITLE
Workspace switcher applet add and remove not working

### ISSUE THREAD

**Issue by MatthewScholefield** [budgie-desktop/budgie-desktop#1032]
Just wondering if there's something wrong or if it's just not implemented yet (it's fine if that's the case). @cybre [Here's a video.](https://streamable.com/ugyix)

**Comment by cybre** [comment]
What does it say if you run it from terminal and try to add a workspace?

**Comment by MatthewScholefield** [comment]
Wtf, it works now o_o. I guess we can close the issue.
