### ISSUE TITLE
Trash icon added outside view

### ISSUE THREAD

**Issue by lebjortvedt** [budgie-desktop/budgie-desktop#1046]
**Operating System**: Solus 2017.04.18.0 64-bit
**Budgie version**: budgie-desktop v10.3.1-400-gb70b63a

**The issue encountered**
When I tried to add Trash shortcut to the desktop from the new Budgie Settings, it was added but barely visible - I could only see a few pixels of the icon in the bottom right corner.

After moving the icon to a better position, I can switch it on an off without problems.
I have a laptop with 1920x1080 resolution.

**Steps to reproduce the issue**
Use the Desktop tab in Budgie settings, and add a Trash shortcut.

**Comment by ikeydoherty** [comment]
You can right click the desktop and select 'Organise desktop by name' which will automatically re-align everything on the desktop. The desktop functions are provided by Nautilus itself, and this is effectively how they expect this stuff to behave. Gonna have to close this as a cantfix/with workaround, sorry
