### ISSUE TITLE
last of the GTK+3.18 theming issues

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#1047]
git master

ubuntu 16.04 / GTK+3.18

**The issue encountered**

budgie panel is not arc-themed.  Errors thrown when running budgie-panel --replace - that the theme could not be loaded
 ...

**Steps to reproduce the issue**

compile and install git master

 ...

errors fixed via this patch:

```
--- a/src/theme/3.18/theme.scss
+++ b/src/theme/3.18/theme.scss
@@ -8,8 +8,6 @@
     text-shadow: none;
     icon-shadow: none;
     opacity: 1;
-    min-width: 0;
-    min-height: 0;
 }
 
```

Lastly,

.budgie-menubar - padding between the GtkMenuItems is 8px.  

Any thoughts how to reduce this to 2px to style in the same way as other panel icon spacing?

Have tried the following:

```
--- a/src/theme/3.18/_main.scss
+++ b/src/theme/3.18/_main.scss
@@ -56,6 +56,14 @@
 // Budgie styled Gtk Menus
 .budgie-menubar {
     @include budgie_menubar(GtkMenu, GtkArrow, GtkMenuItem, GtkMenuAccelerator);
+    
+    GtkMenuItem {padding: 2px;}
+}
+
```

didnt work

if I run budgie-panel via Gtk Inspector the CSS here works

```
.budgie-menubar {
    padding: 2px;
}

**Comment by fossfreedom** [comment]
ok - final patch I'm holding also resolves the menu spacing issue

```
--- a/src/theme/3.18/theme.scss
+++ b/src/theme/3.18/theme.scss
@@ -8,8 +8,6 @@
     text-shadow: none;
     icon-shadow: none;
     opacity: 1;
-    min-width: 0;
-    min-height: 0;
 }
 
 @import 'settings';
--- a/src/theme/common/_resets.scss
+++ b/src/theme/common/_resets.scss
@@ -1,5 +1,5 @@
 @mixin menu_reset_style($label,$insensitive) {
-    padding: 4px 8px;
+    padding: 2px 2px;
     border: solid transparent;
     border-width: 0;
 
```

**Comment by JosephMcc** [comment]
@fossfreedom I'm attempting to build budgie from git master on LinuxMint18/Ubuntu16.04. The issue I've run into is
```
WARNING: GLib compiled dependencies do not work reliably with 
the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368

Meson encountered an error in file src/theme/meson.build, line 31, column 0:
The "dependencies" argument of gnome.compile_resources() can not
be used with the current version of glib-compile-resources due to
<https://bugzilla.gnome.org/show_bug.cgi?id=774368>
```
I'm not too familiar with meson and I'm wondering how you are working around this. I know it's a bit off topic of your post but does relate to building the theme ;)

**Comment by alunux** [comment]
@JosephMcc you need to patch your GLib or meson, because meson reqiures GLib >= 2.51.1 to work with those stuffs.

**Comment by fossfreedom** [comment]
No need to patch GLib or meson - there is a workaround.  Its possible to carry a patch to invoke sassc separately via distro packaging instead of src/themes/meson.build.  Therefore you can remove the callout to sassc and hence the warning @JosephMcc encounters will not occur.

I'll be doing this for the Ubuntu 16.04 packaging.
