### ISSUE TITLE
Panel: Hiding Messes Up Click Detection on Panel

### ISSUE THREAD

**Issue by SolarLune** [budgie-desktop/budgie-desktop#1049]
**Operating System**: Solus 2017.04.18.0 64-bit
**Budgie version**: budgie-desktop v10.3.1-400-gb70b63a

**The issue encountered**

When hiding a panel is turned on, the "hitbox" for clicking on the panel doesn't transform to match the panel's hidden or visible state. Basically, it means that you can only click on the panel at the very bottom where the base is. Here's a GIF for an explanation.

![clickthroughdock](https://user-images.githubusercontent.com/4733521/28389699-1ce87d28-6c8c-11e7-80fb-ff2321d18d0a.gif)

**Steps to reproduce the issue**
1. Set a panel to auto-hide.
2. Hover over the panel to show it.
3. Click anywhere on the panel. You'd expect to click on the panel, but instead the window below is registered. Unfortunately, this step is inconsistent - sometimes clicking on the panel is problem-free, while others it's simply "unclickable" unless you click at the very base of the panel. It seems like raising the panel, moving the mouse up to hide it, and then going and showing the panel again without switching to another program or window makes it more likely to happen.

**Comment by SolarLune** [comment]
So quick! Thanks a lot!

**Comment by ikeydoherty** [comment]
Make sure and test it though on the latest Solus updates (restart budgie) to make sure i'm right :)
