### ISSUE TITLE
Panel overflows with icons

### ISSUE THREAD

**Issue by Shadow53** [budgie-desktop/budgie-desktop#1054]
When reporting issues for Budgie Desktop, ensure you read these guidelines and delete this first
introductory paragraph. If including build failures, or general tool output, please ensure they are
in English, i.e. `LC_ALL=C LANG=C`. If your issue is a Budgie *crash*, include a stack trace. (gdb)

**Operating System**: Solus 2017.04.18.0
**Budgie version**: 10.3.1-404-g128a50a (with material branding)

**The issue encountered**

 I tried moving my top panel to the left side of my screen, just for fun. What I came across was that I had so many icons on the panel that the panel contents were actually pushed off the bottom of the screen, as in the screenshot:

![screenshot from 2017-07-20 12-59-39](https://user-images.githubusercontent.com/10555070/28436413-c12d4f48-6d4b-11e7-8f1b-1aebbc0deb93.png)

Making the panel slimmer "fixed" the problem, since the smaller icons meant more could fit on the screen. I'd expect some sort of overflow handling to occur, such as making another panel "row" for the icons of the opened programs that can be switched between using up and down arrow buttons, some sort of popover once "X" amount of icons are added to the system tray, extra icons overflowing "behind" the system tray and having icons "slide" into view using left/right buttons, or whatever else the Solus devs can come up with.

**Steps to reproduce the issue**

Move a panel to the side of the screen and open a bunch of programs, especially ones that add system tray icons as well.

**Comment by fossfreedom** [comment]
basically the same as this: https://github.com/budgie-desktop/budgie-desktop/issues/83 (https://github.com/budgie-desktop/budgie-desktop/issues/855) - so we'll close this as a duplicate to keep the issue tracker clean.

thanks

**Comment by Shadow53** [comment]
I'd argue that this is a separate bug, because the icons are moving the others out of the way, not going underneath them. Opening more windows *pushes* the system tray down, while those bugs talk about the extra windows appearing *underneath* the system tray.

**Comment by ikeydoherty** [comment]
Whichever way you look at it, "panel constraints are fucked".  Also the introductory paragraph says to delete it :P

**Comment by Shadow53** [comment]
\*Facepalm\* I thought I did that.... Whoops.
