### ISSUE TITLE
Integrating Nautilus search into the Super key menu?

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#1061]
As far as I can tell, the current way for a user to search for his files is to open Nautilus and begin to type his search term. 

I am wondering whether this search can be integrated directly into the Super key menu so that the user doesn't have to open Nautilus first to search for files.

**Comment by ikeydoherty** [comment]
No, sorry. Budgie is a application menu only.

**Comment by orschiro** [comment]
Thanks, @ikeydoherty.

And what about this box triggered by Alt + F2?

![image](https://user-images.githubusercontent.com/170947/28491268-78e3432e-6eee-11e7-9e36-8e76e53078c5.png)

**Comment by ikeydoherty** [comment]
Its a run dialog. It runs applications

**Comment by orschiro** [comment]
Got it. :-)

**Comment by ikeydoherty** [comment]
We can look at extending this stuff during Budgie 11 maybe, but atm we're tied to GNOMEy stuff and Nautilus, and I'd rather not go down that rabbit hole

**Comment by orschiro** [comment]
Surely, makes sense to me! I will stick to the Nautilus way of doing search.

**Comment by orschiro** [comment]
@ikeydoherty on a related note, what do you think of at least integrating bookmarks like "Documents", "Downloads", "Music, "Pictures" into the menu?

For example, typing "Docu.." and pressing enter would allow the user to directly open the "Documents" folder inside Nautilus.
