### ISSUE TITLE
No quicklist support in icon task list if the application has no window

### ISSUE THREAD

**Issue by Jacob-Vlijm** [budgie-desktop/budgie-desktop#1062]
budgie-desktop 10.3.1 (upgraded https://launchpad.net/~ubuntubudgie-dev/+archive/ubuntu/master-branch)

On the new panel > icon task list, the icons only show their shortcuts, as defined in the `Actions=` -section (in the `.desktop` files), if the application is actually running (has one or more windows), like this (nautilus example): 

![b](https://user-images.githubusercontent.com/8932980/28489174-6c9ab82c-6ebc-11e7-9e9e-d74df55715e5.png)

...where the lower section is in my `.desktop` file.
If the application has no window however, only "remove from panel" shows:  

![a](https://user-images.githubusercontent.com/8932980/28489176-88c10e52-6ebc-11e7-9fb9-5387b9678c2d.png)

...which limits the usage of quick-lists.

---
Most likely, for the same reason, in the case of nautilus, bookmarks from `~/.config/gtk-3.0/bookmarks` are not included.

**Comment by ikeydoherty** [comment]
These aren't Unity quicklists these are freedesktop action specs.  Thus nowhere in the .desktop file does it say "please jam the contents of my bookmarks file into this menu".

**Comment by Jacob-Vlijm** [comment]
@ikeydoherty  I never mentioned Unity Quicklists, on Budgie, Plank supports quicklists as wel, and nautilus shortcuts. On Gnome, Dash to panel also does and so on. Just an icon on a panel is hardly of any use IMO.

**Comment by ikeydoherty** [comment]
>  I never mentioned Unity Quicklists

No but that's actually what you described :) The actions are severely limited due to only being statically defined in a `.desktop` file. Any other *dynamic runtime actions* would be defined via the menu that's in the titlebar. (The one that is placed by GNOME Shell into the "top panel")

**Comment by ikeydoherty** [comment]
Long story short you want the menu actions to always be visible, ya ? Regardless of whether its running or not (and whether they would then in fact work)

**Comment by Jacob-Vlijm** [comment]
@ikeydoherty Sorry for the delay, mobile issues :). Yeah, that's it.
