### ISSUE TITLE
Panel is still transparent when transparency is switched off 

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#1063]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: Budgie 10.3.1-404-g128a50a

Panel is still transparent when transparency is switched off.

![Alt Text](http://i.imgur.com/uuYqUiZ.png)

**Comment by fossfreedom** [comment]
transparency makes the entire dock(s)/panel(s) display without any theme - your picture looks normal with the transparency option off - i.e. Arc themed ... which has a slight bit of opacity applied.

**Comment by ikeydoherty** [comment]
Yea not-an-issue I'm afraid :) As @fossfreedom indicated, transparency literally renders it fully transparent. Its up to the theme how the panel itself is rendered with each option. To fit with Arc, the built-in theme (Arc based) is partially translucent.
