### ISSUE TITLE
Workspace Switcher Applet leaves traces on the Panel

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#1064]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: Budgie 10.3.1-404-g128a50a

Workspace Switcher Applet leaves traces (vertical lines) on the Panel. 

![Alt Text](http://i.imgur.com/vDCixPj.gif)

**Comment by JoshStrobl** [comment]
Closing as a duplicate of #997
