### ISSUE TITLE
Cannot add any application to autostart using Budgie Settings

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#1072]
**Operating System**: Latest Solus Testing ISO
**Budgie version**: budgie-desktop v10.3.1-404-g128a50a

**The issue encountered**

Cannot add any application to autostart using Budgie Settings.

**Steps to reproduce the issue**

Example of trying to add Thunderbird:

![peek 2017-07-26 21-33](https://user-images.githubusercontent.com/170947/28641746-97550d6e-7250-11e7-8fd9-d0cd8ec01ecd.gif)

**Comment by Nikki1993** [comment]
Present in stable version as well.

**Comment by Mowalle** [comment]
I can reproduce this as well in stable. I noticed that on a default fresh install (fresh home folder), the folder `~/.config/autostart` is missing where normally the autostart .desktop files would be placed. As a workaround fix, I created the folder `~/.config/autostart` manually, which then lets me add applications to autostart again.

**Comment by orschiro** [comment]
@Mowalle that's a workaround, thanks!

**Comment by ikeydoherty** [comment]
Yeah I'll fix this today - it's an assumption in the settings dialog. Cheers for tracing the issue guys

**Comment by Vistaus** [comment]
Strange, I can't reproduce this issue. Did a fresh install with the latest ISO a couple of days ago.

**Comment by orschiro** [comment]
Wow, that was fast, thanks @ikeydoherty!

**Comment by ikeydoherty** [comment]
Now in Solus https://dev.solus-project.com/R465:a22855d202615173b41b6f933cb79a9617e909e4
