### ISSUE TITLE
[Raven] "shutdown" Icon triggers "logout"

### ISSUE THREAD

**Issue by STiAT** [budgie-desktop/budgie-desktop#1077]
```
$ budgie-desktop --version
budgie-desktop v10.3.1-414-g7561deb1
Copyright © 2014-2017 Budgie Desktop Developers
```

The Raven-Panel uses the "shutdown" icon to trigger the "logout" action, while the systray icon has a different icon for "logout", which is actually the shutdown icon
Applet:
![applet](https://user-images.githubusercontent.com/1781015/28757900-3a1200b8-758d-11e7-86e4-d34f4d596657.png)
Raven:
![raven](https://user-images.githubusercontent.com/1781015/28757901-3a1290aa-758d-11e7-877b-2fc86a763b59.png)

You can see, the Icon which triggers "logout" in Raven actually triggers "shutdown" in the Applet. That's just an inconsistency, but an irritating one ;-).
.

**Comment by ekianjo** [comment]
I was going to report the very same thing. This is very inconsistent, design-wise, and confusing for the first time user. There should not be two places to do the very same thing, and certainly not the same icon for menus that are actually different in nature.

**Comment by Memnarch** [comment]
@ekianjo i think this missmatch comes some previous versions. IIRC they changed the way they use to access the current session. In the past, the Shutdown-Button actually opened a dialog which displayed a Cancel, Logout, Shutdown Dialog. AFter changing their mechanics, they lost the option to actually shutdown. If anything should be changed, they should readd Shutting down without having to logout first.

**Comment by Memnarch** [comment]
See:
https://github.com/budgie-desktop/budgie-desktop/issues/609
