### ISSUE TITLE
Suggestion: Provide an option for fatter scroll bars

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1083]
Operating System:Solus 2017.04.18.0
Budgie version: v10.3.1-404-g128a50a

**The issue encountered**

Thin scroll bars have been pushed by UI gurus as superior due to their lack of obtrusiveness. While this is empirically valid, they're also really annoying to deal with on a touchpad because they're paper thin. Please include an option to offer fatter ones that are easier to grab. 

**Steps to reproduce the issue**

N/A
 ...

**Comment by ikeydoherty** [comment]
Uh, that's a GTK level thing and not a Budgie level-thing. Applications can choose whether to have overlay scrolling or a permanently visible scrollbar, with the default being overlay scrolling. Secondly, the actual thumb **size** is then down to the GTK theme used.

Adapta offers a decent compromise here, in that the scrollbar thumb will grow in width when entering the thumb track region.

Closing as a !budgie-issue

**Comment by ChrisOfBristol** [comment]
I have a wide, wide screen and tiny scrollbars, there is no file similar to /usr/share/themes/elementary/gtk-3.0/scrollbar.css, so how and where does Budgie set up its scrollbars?
