### ISSUE TITLE
Calendar button opens default text/plain editor

### ISSUE THREAD

**Issue by SapiensAnatis** [budgie-desktop/budgie-desktop#1087]
**Operating System**: Arch Linux
**Budgie version**: v10.3.1-414-g7561deb

**The issue encountered**
Clicking the date/time in the default panel bring up a flyout menu. Proceeding to click Calendar on here opens the default text editor (in my case it was Visual Studio Code, after removing the line `text/plain=visual-studio-code-insiders.desktop;` from `~/.config/mimeapps.list`, it started using LibreOffice instead). In both instances no file content was opened and I was presented with a screen as if I had manually started the application myself.

**Steps to reproduce the issue**
Click Calendar in the drop-down menu from the date/time panel add-on.

---

I know this is likely to be a case of my system config being messed up, but I'm just making this issue in the small chance it's on Budgie's end. I did install budgie-calendar-applet from source, just updated to the latest git commit a few minutes ago (and had it, as well as this issue, for as long as I can remember) but it didn't actually work and show the calendar on the drop-down as it was supposed to.

**Comment by kimsaehun** [comment]
Maybe try going to the "Default Applications" settings inside the "Details" system setting and double checking that the default application for "calendar" is the application of your choice.

**Comment by SapiensAnatis** [comment]
How silly of me. I knew it'd be something stupid like that
