### ISSUE TITLE
Cannot unlock screen due to disabled keyboard

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1089]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: v10.3.1-404-g128a50a

**The issue encountered**

The screen cannot be unlocked because the keyboard is disabled.

**Steps to reproduce the issue**

You may need to use a laptop with integrated keyboard. Let the machine lock on its own after timing out. Hit a key to wake it up to the lock screen. Maybe 10% of the time, the password cannot be entered. Maybe this is because the machine goes into suspend or the keyboard itself is powered down, and cannot be properly restored. Anyway that's just a guess. I disabled suspend as far as I can see, to no avail. (Suspend still definitely occurs upon lid closure, although there is no lid closure involved here.) And of course it happens randomly, which suggests some sort of race condition. If this is due to suspend, please allow us to disable it.

**Comment by ikeydoherty** [comment]
Sounds like your Solus box isn't fully updated running the latest gnome-screensaver pkg tbh.

**Comment by KloudKoder** [comment]
It's now fully updated. Please leave this open for a month. If it occurs again, I'll report back.

**Comment by ikeydoherty** [comment]
It doesn't need to stay open - I intentionally fixed it with the fork of gnome-screensaver :)
