### ISSUE TITLE
Selecting the last line in Files conflicts with notification in lower right

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1091]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: v10.3.1-404-g128a50a

**The issue encountered**

 Open Files. Look at the contents of a folder containing lots of files, so that the list takes up the whole window.

**Steps to reproduce the issue**

Click on the file on the last line to highlight it. The notification in the lower right corner, which redundantly tells the user that he has selected file X of size Y, is printed directly on top of some of the file info in the righthand columns. This notification is useless anyway.

**Comment by ikeydoherty** [comment]
This is an upstream Nautilus issue (GNOME) and not a Budgie issue. The status information uses an overlay, which is why its on top of the other bits. Not a bug as such, more an upstream design decision.
