### ISSUE TITLE
Newly installed software doesn't appear in search until reboot.

### ISSUE THREAD

**Issue by s3w47m88** [budgie-desktop/budgie-desktop#1100]
**Operating System**: Ubuntu 16.04.3
**Budgie version**: Budgie 10.3.1

**The issue encountered**
After installing any new software and attempting to locate it on the system by using the search (upper left icon either clicking or using the super key) the application should appear in results but does not. This occurs with all applications in my experience.

 ...

**Steps to reproduce the issue**
1. Open Software
2. Install anything, for example, Gimp.
3. After successful install select the search and enter the application name, ex. "gimp".
4. You will see no result.
5. Restart the computer.
6. Run the same search and "gimp" will now appear.

**Comment by fossfreedom** [comment]
ok - I've backported a 17.04 patch.  Just update as usual. Thanks.

**Comment by ikeydoherty** [comment]
The dreaded gnome-menus+unity patch.. :)
