### ISSUE TITLE
hid_magicmouse not available

### ISSUE THREAD

**Issue by s3w47m88** [budgie-desktop/budgie-desktop#1101]
**Operating System**: Ubuntu 16.04.3
**Budgie version**: Budgie 10.3.1

**The issue encountered**
hid_magicmouse should be an available module on the system but is not. Forgive me if this is not explicitly related to Budgie Desktop.

 ...

**Steps to reproduce the issue**
1. Open Terminal.
2. Execute `systool -avm hid_magicmouse`
3. Result will state there was an error.

 ...

**Comment by ikeydoherty** [comment]
Yeaaah that's an Ubuntu kernel thing and not a Budgie Desktop thing, sorry.

You'll need to poke them about `CONFIG_HID_MAGICMOUSE`. Or use the next Solus ISO we release :P

**Comment by s3w47m88** [comment]
Okay, thank you!

**Comment by fossfreedom** [comment]
@s3w47m88 it should in theory work in ubuntu

 http://sneclacson.blogspot.co.uk/2016/09/using-apple-magic-mouse-with-ubuntu-1604.html

If its still not visible then that's a regression - please run

ubuntu-bug linux

to report the bug.
