### ISSUE TITLE
Raven: Issue with scrolling bars

### ISSUE THREAD

**Issue by MrksKwsnck** [budgie-desktop/budgie-desktop#1106]
With a freshly installed **Ubuntu Budgie 17.04 (Zesty Zapus)** the Raven panel offers scrolling bars if applets don't fit vertically. My System is  a Notebook with a **display resolution of 1366x768 pixels**. As you also can see in the screenshots below I am using the default Arc theme.

Budgie version **without issue**:

    $ budgie-desktop --version
    budgie-desktop 10.2.9
    Copyright © 2014-2017 Ikey Doherty, Solus Project

Screenshot **without issue**:

![bildschirmfoto vom 2017-08-17 14-54-28](https://user-images.githubusercontent.com/486983/29423057-85888198-837a-11e7-8120-acb4718560e0.png)

After installing software updates the scrolling bars don't appear anymore when I try to scroll inside the Raven panel.

Budgie version **with issue**:

    $ budgie-desktop --version
    budgie-desktop 10.3.1
    Copyright © 2014-2017 Ikey Doherty, Solus Project

Screenshot **without issue**: See the very bottom of the panel where I'm unable to reach some elements as they are overlayed.

![bildschirmfoto vom 2017-08-17 14-53-37](https://user-images.githubusercontent.com/486983/29423080-a6b97052-837a-11e7-950f-e1930be1acbe.png)

**Steps to reproduce the issue**

1. Get a display with a resolution of 1366x768.
2. Install `budgie-desktop` v10.2.9.
    1. Try to scroll inside the Raven panel: OK
3. Update `budgie-desktop` to v10.3.1.
    1. Try to scroll inside the Raven panel: Not OK

**Comment by ikeydoherty** [comment]
This is fixed in Budgie 10.4 - so I'll close it but tag in @fossfreedom so he can discuss backport/ubuntu options

**Comment by MrksKwsnck** [comment]
Nice one. That was a quick fix. Thanks.

**Comment by ikeydoherty** [comment]
Oh I didn't fix it just now, already fixed in 10.4 which is released :)

**Comment by fossfreedom** [comment]
@MrksKwsnck You'll see budgie-desktop 10.4 within the next week or so.  Just finishing up Debian unstable/buster and Ubuntu 17.10 with budgie-desktop 10.4

Then will look at 17.04 followed by 16.04
