### ISSUE TITLE
Drag and drop from Budgie menu to desktop with unexpected result.

### ISSUE THREAD

**Issue by henryzellie** [budgie-desktop/budgie-desktop#1108]
Solus 3
Budgie version 10.4

Dragging and dropping applications from Budgie menu onto desktop creates a generic gear icon, and the full name of the program file. Double clicking the icon causes a "Untrusted application launcher" dialogue to appear. Only after pressing "Trust and launch" does the expected icon and program name appear on the desktop.
![icon](https://user-images.githubusercontent.com/31156735/29485729-4847dcbe-84c6-11e7-8232-ba088842764f.png)
![untrusted applicaion](https://user-images.githubusercontent.com/31156735/29485731-4c588812-84c6-11e7-984f-0d243069cedb.png)
![after](https://user-images.githubusercontent.com/31156735/29485732-50156646-84c6-11e7-9ab8-a7b0b4ea6cb4.png)

**Comment by fossfreedom** [comment]
That is nautilus - it a recent change in the newer versions of nautilus done for security reasons.

As such I'll close this since it is not a budgie desktop issue per se.
