### ISSUE TITLE
Feature request: Ability to perform calculations from the Command menu or the Alt+F2 dialog

### ISSUE THREAD

**Issue by manasthakur** [budgie-desktop/budgie-desktop#1122]
Hello dear Devs,

Can we have the ability to perform calculations (without opening the calculator) from either the Command menu (GNOME does this), or the Run command dialog (Alt+F2)? It's sometimes very handy.

**Comment by fossfreedom** [comment]
lets keep ALT+F2 suggestions under the existing issue.  thanks

https://github.com/budgie-desktop/budgie-desktop/issues/265
