### ISSUE TITLE
Image files disappear from Files GUI

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1126]
**Operating System**: Solus 3
**Budgie version**: 10.4
**The issue encountered**

Sometimes recently added or even recently edited photos disappear from the listing in the Files app, as though they've been deleted. This is serious because selecting all and copying does not actually copy all the files. This appears to be due to a delay in thumbnail synchronization between the newly edited photo and its appearance in the Files GUI. It's as though, instead of just showing a temporarily outdated thumbnail, no thumbnail shows at all, which makes it look as though the photo was deleted.

**Steps to reproduce the issue**

Open a photo in an image editor. Expand it to something huge, say 100MB, then save it as a raw format like BMP. (The intention here is to create a lot of latency in the thumbnailing process.) Then go switch to Files and see if you see the file you just created. Maybe toggle between file listing and thumbnail display, or hit F5 to refresh. The behavior is sort of random, and often it "just works".

**Comment by fossfreedom** [comment]
This is not a budgie desktop issue per second ... Sounds like a files ... Totem / ffmpeg thumbnails the issue depending upon what you are using to create and display pictures in files.

Please report this on phabricator
