### ISSUE TITLE
Some app notifications in App-Indicator are too large. 

### ISSUE THREAD

**Issue by tushantin** [budgie-desktop/budgie-desktop#1131]
The App Indicator applet on Budgie seems to show some icons, such as that for Spider Oak, extremely large for some reason, taking up unnecessary amount of space. In order to present the screenshot, I added the applet to a temporary dock at the top position. 

![workspace 1_686](https://user-images.githubusercontent.com/5314015/29906321-c33e6626-8e31-11e7-80a7-ff6960e208c2.png)

**Operating System**: Ubuntu 16.04 LTS 
**Budgie version**: i.e. Budgie 10.4 via PPA as [described here](http://www.omgubuntu.co.uk/2017/08/install-budgie-desktop-10-4-on-ubuntu). 

Is there any workaround I can try to fix this issue?

**Comment by fossfreedom** [comment]
This isnt a budgie-desktop issue - please create an issue here https://github.com/UbuntuBudgie/budgie-indicator-applet

**Comment by ikeydoherty** [comment]
Looks like you need to forcibly scale to a given size if the pixmap is too large.
