### ISSUE TITLE
Cannot configure WiFi connection

### ISSUE THREAD

**Issue by abhishek-sinha3453** [budgie-desktop/budgie-desktop#1132]
**The issue encountered**
I cannot connect to WiFi nor can see any WiFi icon on the system tray. Wireless/WiFi option is also not present in the network settings.
 ...

**Comment by sharky009** [comment]
Sounds like a driver issue, have you tried to check the network card in the terminal?
Is the Card working or is it not present in linux?

**Comment by abhishek-sinha3453** [comment]
I think the same. 
It was working with lxde environment .
But now when I have installed solus,I cannot configure WiFi.

**Comment by fossfreedom** [comment]
This sounds more like a Solus specific issue rather than a budgie-desktop issue.

My suggestion is to report this on the correct issue tracker for Solus (phabricator)- https://dev.solus-project.com/maniphest/
