### ISSUE TITLE
Panel: group multiple instances of the same program

### ISSUE THREAD

**Issue by fbg13** [budgie-desktop/budgie-desktop#1133]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

Add an option to group multiple instances of the same program. The way it currently works is very chaotic. I pin a program so I expect it to be where I pinned it, but opening another instance adds it at the end of the list.

I suggest the Windows approach:

![windows](https://user-images.githubusercontent.com/6839895/29980759-d1560016-8f53-11e7-9275-e72580c8e543.gif)

Clicking/hovering the group shows a preview of the instances in a small window (while this window is hovered the full one is displayed), you can left click to select (maximize, focus, bring on top) the instance or you can middle click to close it.

Here is how KDE handles this, which in my opinion is worse.

![kde](https://user-images.githubusercontent.com/6839895/29980763-d482074e-8f53-11e7-9f8e-a334e5c2934e.gif)

No middle click to close here.

**Comment by Zaigenshi** [comment]
Budgie's lack of window grouping is still the biggest problem I have with it. Preview won't seemingly be implemented but if we could get something official similar to mussels attempt at it that would be pretty great imo. 

![e5f062e0-7047-11e6-973d-7005ba71dc06](https://user-images.githubusercontent.com/25939455/29987347-668e7130-8f2d-11e7-9ad8-d4e070c2caa5.png)

**Comment by fossfreedom** [comment]
linking this to the existing grouping issue.

https://github.com/budgie-desktop/budgie-desktop/issues/278

**Comment by mak3** [comment]
Will Ubuntu Budgie 18.04 LTS get this feature or we need update to 18.10?
