### ISSUE TITLE
Panel Size messed up by icons

### ISSUE THREAD

**Issue by ruffson** [budgie-desktop/budgie-desktop#1134]
**Operating System**: Ubuntu 16.04.3
**Budgie version**: Budgie 10.4

**The issue encountered**

 I just updated my budgie desktop under ubuntu to 10.4. And noticed that my top panel is not as small anymore as before. Rather, the OS icons scaled with the panel size, but the panel itself is rather fat.

It seems that some of the third-party icons are causing the panel to be larger, which was not the case before. I would expect that resizing the panel would either resize all the icons (they are rendered in some way budgie knows of) in the panel. Or reverting back to the original state where the panel would be made smaller and with that the margin around the third-party icons. 

This way is wasting a lot of screen estate. Here is a screenshot:
![panel size](https://user-images.githubusercontent.com/1185812/29997421-8c92bdc4-8fc7-11e7-8955-cc974f683ea0.png)

Is there anything I can do for now to get this fixed?

Update of two new observations:

- When starting something like steam which has a larger icon than others, the panel just increases to that ridiculous size.
- When you drag windows to the top they go through the extra panel-space until they are stopped by the set panel size. This panel management is seriously screwed up.

Here another screenshot: 
![panel2](https://user-images.githubusercontent.com/1185812/29997537-b6eea634-8fca-11e7-8836-617f2c300513.png)

**Comment by fossfreedom** [comment]
This issue is due to the icon-set you are using in-combination with the app-indicator.

For 17.10, ubuntu budgie is using pocillo, faba-mono-icons, moka in that order.  I'll look into backporting this for 16.04 at some point.

This is Ubuntu specific and hence not appropriate for this upstream issue tracker.  Check the ubuntubudgie/budgie-desktop-environment project where there is a similar issue already reported.

**Comment by ruffson** [comment]
So the changes made to budgie-desktop broke functionality of UbuntuBudgie because the changes require a new icon set that was not included in budgie-desktop?

**Comment by fossfreedom** [comment]
@ruffson no - its because Steam does not ship a 22px icon with the icon-set you are using.  We (Ubuntu Budgie) can resolve this.  Its not an upstream issue.

**Comment by ruffson** [comment]
Sorry, I don't want to write in two different threads, but the issue here is not that some icons do not fit into the panel, its that the new panel is giving however much room is needed for the icons to display where it previously just cut off the icons if they are too big which I find is much more stable behavior.
Otherwise whenever you have a icon that is too big, it just messes with your UI.
