### ISSUE TITLE
Canon MG5600 series WIFI printer not detected

### ISSUE THREAD

**Issue by swelch1951** [budgie-desktop/budgie-desktop#1135]
Operating System:  Solus 3
Budgie version:  Budgie 10.4 

Issue:  Printer setup does not detect Canon MG5600 WIFI printer. It is detected by Fedora, Unbuntu and Windows
 ...

Steps to reproduce the issue:  You'll need a Canon MG5600 series WIFI printer on a home network (FIOS) using WPA2. Try to connect using the printer setup tool.  It's not detected.  Works on every other Linux distro I've tried.

 ...

**Comment by fossfreedom** [comment]
Please report this on phabricator https://dev.solus-project.com/maniphest/.  This tracker is for budgie-desktop specific issues
