### ISSUE TITLE
Raven unable to find album cover image located in album folder.

### ISSUE THREAD

**Issue by sootstone** [budgie-desktop/budgie-desktop#1136]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**

Apologies if this is a Audacious/Solus issue: When playing audio in Audacious that does not have embedded artwork, but rather the artwork is stored as a single file in the album folder (`cover.png`), Raven will not display the artwork.

**Steps to reproduce the issue**

1. Create a folder containing an audio file and an image file named `cover.{jpg, jpeg, png}`,  `folder.{jpg, jpeg, png}` or `front.{jpg, jpeg, png}`. 
2. Play the file in Audacious.

**Comment by JoshStrobl** [comment]
Sounds more like an upstream issue with Audacious' support of MPRIS 2.

**Comment by sootstone** [comment]
There's been an update recently, nothing in the [changelog](http://audacious-media-player.org/news/42-audacious-3-9-released), I'll submit an issue with them if the update doesn't fix it.

Feel free to close this.
