### ISSUE TITLE
Any refresh rate other than 59 Hz produces blank screen.

### ISSUE THREAD

**Issue by csar4** [budgie-desktop/budgie-desktop#1143]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

Title says it all. When I go to display in the settings panel and change the BenQ XL2730Z monitor refresh rate higher than 59hz, the screen goes blank and tells me its out of range. I thought my display port cable might have gone bad or something because this worked just fine in previous Solus/Budgie versions, but I just installed Mate on Solus and I can change my refresh rate just fine in Mate, no blank screen. Other than 59 Hz, the other options available are 99 Hz, 119 Hz and 144 Hz (NTSC) in display settings.

**Comment by shrinjoy** [comment]
i know whats up............u need to upgrade your mouse when u tweak that hz thingy in mate it dsnt actually affect anything..............so to get more hz u need get a monitor with higher refresh rate

**Comment by csar4** [comment]
I'm sorry, I don't quite follow you.

**Comment by arcooke** [comment]
Translation:

> Hello fine sir, I know what the issue is with your thingy.  You need to upgrade your ~~mouse~~ monitor to a model which supports higher refresh rates in order to use those settings, otherwise changing those settings doesn't do anything.

He doesn't seem to know that your XL2730Z is a 144hz display

**Comment by csar4** [comment]
Thanks for the English translation. I solved this, btw. Just had to change the primary graphics adapter from auto to pcie in my mobo bios (doh!) Weird, because I have Solus installed on 2 PC's, and I'm pretty sure that setting is still auto on my 2nd PC, but the problem doesn't occur. Eh, whatever. Closing this now.
