### ISSUE TITLE
Opening and Closing Budgie Settings Leaves Ominous “Budgie Panel” Icon In Plank

### ISSUE THREAD

**Issue by jGleitz** [budgie-desktop/budgie-desktop#1146]
### Steps to reproduce

*  Download the [latest Ubuntu Budige 17.10 Build](http://cdimage.ubuntu.com/ubuntu-budgie/daily-live/current/HEADER.html) and run a live session
 * Open Raven and click on the cog to open Budgie Settings
 * Close the Budgie Settings Window
 * An icon stays at the bottom of Plank. Its title is “Budgie Panel”. Neither clicking on it nor right clicking on it and hitting “close” has any apparent effect. It will stay there until `budgie-panel` is restarted (e.g. by `killall budgie-panel`)

![budgie panel icon](https://user-images.githubusercontent.com/4305652/30242496-c32a9732-9597-11e7-9393-f86e4bf1505f.png)

**Operating System**: Ubuntu 17.04
**Budgie version**: Budgie 10.4

**Comment by fossfreedom** [comment]
@jGleitz fixed in git.

FYI - will be uploaded to UB 17.10

**Comment by fossfreedom** [comment]
huh? well included the patch in 17.10 and this problem still occurs.  reopening.

**Comment by fossfreedom** [comment]
ah - have to also set the StartupWMClass=budgie-desktop-settings for the .desktop file

lol - will do another PR.  sorry about that.

**Comment by genvir** [comment]
I have the same problem, when running budgie theme and changing the theme the icon continue to appear in plank

**Comment by iwilltry42** [comment]
This issue just appeared to me again after upgrading to UB 18.10.
The icon disappears when the plank is refreshed (e.g. when you change a plank setting back and forth).

**Comment by iwilltry42** [comment]
This issue just appeared to me again after upgrading to UB 18.10.
The icon disappears when the plank is refreshed (e.g. when you change a plank setting back and forth).
