### ISSUE TITLE
[Enhancement] Improve Alt+F2 runner

### ISSUE THREAD

**Issue by gabrc52** [budgie-desktop/budgie-desktop#1152]
**Budgie version**: Budgie 10.4

It could be improved in these ways:

- Directly run commands
- Make simple calculations
- Choose a different key binding, such as Alt+Space
- Search files

**Comment by fossfreedom** [comment]
lets keep suggestions in this area under the existing issue.

https://github.com/budgie-desktop/budgie-desktop/issues/265
