### ISSUE TITLE
Enhancement: more screen lock timeout choices

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1153]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: v10.3.1-404-g128a50a

**The issue encountered**

On the power menu, we can only choose screen lock timeouts up to 15 minutes.. This creates a problem in a lot of practical contexts. It would be best if we could enter the number of minutes, or at least choose from many more choices. For example, it would be nice to be able to make it through an hour meeting without accidentally locking yourself out because if you do, you may be unable to enter your password again due to the number of cameras in the room.

**Steps to reproduce the issue**

Go to the Power menu under System Settings. See "Blank screen" dropdown.

**Comment by fossfreedom** [comment]
This is not a budgie-desktop issue per se - Power menu stuff is provided by GNOME.

Thus, this should be reported upstream on GNOME bugzilla ... if it hasn't already.
