### ISSUE TITLE
[Enhancement] allow changing where notifications appear on the screen

### ISSUE THREAD

**Issue by o-alquimista** [budgie-desktop/budgie-desktop#1156]
The notifications appear right in front of where window buttons are positioned by default (the top right of the window). By being able to change where the notification is drawn, I can avoid the situation where I go to the Close button and a notification appears right on top of it and force me to either wait, close the notification or move the window away from it.

For example, I would change it to appear at the bottom right corner, where the clock is by default. But give choice.

Solus 3
budgie-desktop 10.4

**Comment by fossfreedom** [comment]
duplicate of this https://github.com/budgie-desktop/budgie-desktop/issues/613
