### ISSUE TITLE
Notifications privacy (and spam)

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#1157]
So currently Raven displays all notifications that are coming through any programme which is set to send notifications through the system tray area. By default many of these notifications only pop up shortly, however, they are visibly present in the Raven notification area even after the programme popovers have long disappeared. Is there any way to prevent Raven from receiving notifications from a particular programme? Is there a potential privacy issue when these notifications are cached in _Notifications_, either by physical access to the computer or by other programmes being able to read the notification cache? If Raven can "collect" these notifications, other programmes might be able to do so too. My specific concern are chat messages which are visible in Raven's notification area.

**Comment by gabrc52** [comment]
> If Raven can "collect" these notifications, other programmes might be able to do so too.

I’m not completely sure, but they might be able to collect them without Raven collecting them.

**Comment by ikeydoherty** [comment]
Raven doesn't "collect" anything. It owns the `org.freedesktop.Notifications` dbus name, which is used by all applications to send notifications to the user. They would appear on screen in any desktop. Other programs can also listen to messages being passed to Budgie on the well known bus name. Programs
should not be using it to send sensitive information.

In Budgie 11, we're going for a data driven approach. That is, the core processes will own these well known names and make them available to parts of Budgie, which will also allow filtering/blacklisting by application IDs, turning it off altogether, etc. Right now Raven/Budgie is too tightly coupled.

**Comment by baimafeima** [comment]
Not sure if I understood everything but if there is a way to implement a system-wide mechanism to prevent applications from spying on one another - simply the fact that they could is enough - then I am all up for it. Maybe there are some things that can be done on a system-level as well? I know there are some operating systems that do so through compartmentalization but the effect on resources is huge.

**Comment by ikeydoherty** [comment]
Well you couldn't stop them "spying" on each other, they're handled on dbus which is public to your session.

**Comment by baimafeima** [comment]
Unfortunately, I have to bump this thread and hope that they will be a temporary fix until Budgie 11 is ready. Is there any way to prevent `notifications spam` in Raven, especially from instant messaging applications? I literally have 100 unread notifications on a daily basis.

**Comment by fossfreedom** [comment]
to ask the obvious - if you regard instant messaging as spam - why dont you turn off in the app the notifications part?

**Comment by baimafeima** [comment]
I need to rely on the notifications when I am in a full screen video conversation. Not the IM notifications itself are spam but the fact that they are unnecessarily duplicated in Raven.

**Comment by JoshStrobl** [comment]
Closing, no actionable items.
