### ISSUE TITLE
Budgie is Broken on openSUSE Tumbleweed with Gnome 3.26

### ISSUE THREAD

**Issue by Isaac-Newt** [budgie-desktop/budgie-desktop#1165]
**Operating System**: openSUSE Tumbleweed (20170913)
**Budgie version**: 10.4

**The issue encountered**

Budgie is broken after the Gnome 3.26 update on openSUSE Tumbleweed. (Specifically budgie-wm, from what I can tell)

When installing the 3.26 update, conflicts between Budgie-wm and libmutter were encountered.  Attempting to run budgie-wm (with `budgie-wm --replace`) gives the following error:

`budgie-wm: error while loading shared libraries: libmutter-0.so.0: cannot open shared object file: No such file or directory`

I don't really have any technical guesses, but given the error output, I'm guessing this might be related to issue #1103 which describes changes in libmutter between 3.24 and 3.26
 ...

**Steps to reproduce the issue**

1. Install openSUSE Tumbleweed with the Gnome desktop
2. Install Budgie alongside Gnome
3. Update to Gnome 3.26
4. Attempt to log into budgie session
5. Attempt will fail, and send you back to the login screen
 ...

**Comment by fossfreedom** [comment]
@Isaac-Newt correct - you need to compile budgie-desktop against libmutter-1 - the mutter api/abi was bumped for gnome 3.26

**Comment by Isaac-Newt** [comment]
Ok.  I will check with the openSUSE maintainer(s) for budgie then.  It looks like the OBS repo was recently updated, so they may already be aware of this.  Good to know this has been addressed.  Thanks!

**Comment by fossfreedom** [comment]
@Isaac-Newt your maintainer should just do a "no change rebuild" - this will ensure budgie desktop is recompiled and it will automatically pick up the new mutter update.

**Comment by Isaac-Newt** [comment]
Seems to be fixed now.  Thanks for the help.

**Comment by showcheap** [comment]
I'm installing from official repo, but after switching to budgie desktop & type password on login screen, session send back to login screen.

* openSUSE Tumbleweed
* GNOME 3.28

Install from this following repo, but no luck.
**10.4-5.1** https://build.opensuse.org/package/show/openSUSE%3AFactory/budgie-desktop
**10.4-22.1** https://build.opensuse.org/package/show/X11:Solus/budgie-desktop

**Comment by fossfreedom** [comment]
@showcheap looks like Tumbleweed is missing patches due to the Nautilus transition.  Please contact your package maintainer.

For other issues please raise a separate thread.  Provide the logs you see when running `journalctl -ae --full`

**Comment by alunux** [comment]
@showcheap This commit https://github.com/budgie-desktop/budgie-desktop/commit/8d42293dd486e0c8fa448298854173884a3f7140 fix your issue. After you backport the patch, you need to add `-Dwith-desktop-icons=none` to your meson rpm macro (it looks like this in your SPEC: `%meson -Dwith-desktop-icons=none`)
