### ISSUE TITLE
Alt+Tab should work in proper order instead of being non-standard

### ISSUE THREAD

**Issue by emctague** [budgie-desktop/budgie-desktop#1166]
**Operating System**: Ubuntu 17.04
**Budgie version**: 10.2.9

**The issue encountered**

When using alt+tab to switch between windows, budgie switches in a single, linear order. On most other systems, the alt+tab order is re-ordered when switching: you can press alt+tab to switch to one window, then press alt+tab to switch back to the other. This makes alt+tab both unintuitive and inconvenient on Budgie, especially because there isn't support for alt+shift+tab either.

Obviously, this isn't so much a bug as it is a feature request, but it'd be a huge improvement to make it either behave in a standard way, or make it an option one can switch on and off.

**Steps to reproduce the issue**

1. install budgie
2. open 3 windows or more
3. alt+tab to switch to the next, then try to alt+tab back to the one you were just at. Instead, it moves to the next.

**Comment by fossfreedom** [comment]
this has been fixed in budgie desktop v10.4

Since you are using Ubuntu, you'll get the fix as part of your upgrade to 17.10.

Alternatively you can you use Ubuntu Budgie's backports PPA to upgrade now.
