### ISSUE TITLE
GNOME apps by default on Budgie 11?

### ISSUE THREAD

**Issue by bobby285271** [budgie-desktop/budgie-desktop#1170]
It is said that Budgie 11 no longer based on GNOME 3, so will any GNOME apps be used? Or will Nautilus be the default file manager, etc...?
If yes, will Bugdie 11 support GTK+ apps well? For example, we know that running GNOME apps on KDE is not a good idea...
If no, then which apps will replace the former GNOME apps, pcmanfm-qt, qterminal, and sth else? How to transfer to those new apps? manual intervention? Or make a new package that conflicts with the old apps and depends on the new one?

**Comment by bobby285271** [comment]
Sorry for my poor English :-/

**Comment by fossfreedom** [comment]
@bobby285271 This is a good read as to where we are going:

 https://budgie-desktop.org/2017/01/25/kicking-off-budgie-11/

So yes we love GNOME applications - the intention is to retain the same look and feel for GTK+ based apps.

Stay tuned for all new announcements - Research work that will inform and guide how budgie desktop v11 will evolve (no pun intended) is here https://github.com/budgie-desktop/budgie-rd
