### ISSUE TITLE
Window manager issues on workspace switching and wmctrl commands

### ISSUE THREAD

**Issue by Jacob-Vlijm** [budgie-desktop/budgie-desktop#1186]
Ubuntu Budgie 17.10
budgie-desktop 10.4, after latest mutter update 3.26.1

After startup, switching workspaces every now and then makes the background of the desktop go black. After a second or two, the wallpaper appears again. It appears to happen on workspaces that were not entered before, Afterwards the issue disappears. 
Additional issue is that wmctrl commands are every now and then executed with a delay of (also) a second or two.

Steps to reproduce the issue: see above. 

Both issues did not occur before the latest mutter update.

**Comment by fossfreedom** [comment]
resolved by the 3.26.1 mutter hotfix
