### ISSUE TITLE
Applets on panel log me out! 

### ISSUE THREAD

**Issue by X174517** [budgie-desktop/budgie-desktop#1195]
**Operating System:** Ubuntu 17.04 
**Budgie version**: 10.2.9

**The issue encountered:**
First click on applets in top panel does nothing, second click logs me out and the session is lost. 

**Further details:**
I installed ubuntu-budgie yesterday and tried to make it ready to work. Thus, I installed software I use the most (octave, python libraries, kile) and synapse.  Then I played around a bit with raven, customizing applets (change position, nothing special) and downloading [these](http://www.omgubuntu.co.uk/2017/06/5-awesome-budgie-desktop-applets).  When I tried "Places" for the first time I encountered the issue. 

I guess I'll just try installing the os again, but perhaps this report is useful for developers. I'm a newbie linux-wise so, I don't know what info could be helpful here. Please let me know any output or command or whatever that I can do to document the issue. Thanks!

**Comment by fossfreedom** [comment]
please describe how you "downloaded" the applet and how you installed these applets - i.e. command line statements.

If you just got the .deb from the PPA and installed these manually then yes - you will get crashes because those applets need the later version of budgie desktop which is also in that PPA.

**Comment by X174517** [comment]
I downloaded applets from terminal, with suggested commands:

sudo add-apt-repository ppa:ubuntubudgie/backports
sudo apt update && sudo apt install budgie-calendar-applet budgie-brightness-control-applet budgie-haste-applet budgie-screenshot-applet

**Comment by fossfreedom** [comment]
yep - the instructions in the blog are wrong

please run:

    sudo apt update && sudo apt upgrade

reboot.

Then all will be well.

**Comment by X174517** [comment]
That was it!!!  Thank you!
