### ISSUE TITLE
Print Screen Button Of Keyboard Not Woking

### ISSUE THREAD

**Issue by github-maverick** [budgie-desktop/budgie-desktop#1197]
**Operating System**: e.g. Solus 3
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**
Print Screen not working. I have tried Budgie both on Solus and Ubuntu Budgie. In both of them Prtsc button is just making beep sound(i.e. buttton is working) but not taking screenshots. It means the command for PrtSc is not exectuting. When I add custom shortcut with gnome-screenshot it works both on Solus and Ubuntu.
 
**Way to solve issue**
You have to change the inbuilt command for PrtSc button with gnome-screenshot and similarly with  other commands associated with PrtSc.

Thanks in advanced!

**Comment by fossfreedom** [comment]
#261 

This is a duplicate issue. Thanks
