### ISSUE TITLE
Bug icon of the red, 

### ISSUE THREAD

**Issue by vendettaboom** [budgie-desktop/budgie-desktop#1198]
When reporting issues for Budgie Desktop, ensure you read these guidelines and delete this first
introductory paragraph. If including build failures, or general tool output, please ensure they are
in English, i.e. `LC_ALL=C LANG=C`. If your issue is a Budgie *crash*, include a stack trace. (gdb)

**Operating System**: e.g. Solus 3
**Budgie version**: i.e. Budgie 10.4

El icono de red presenta problemas con con los themas despues de actualizar a gnome 3.26.1

    budgie-desktop --version

**The issue encountered**
Problemas con icono de red en gnome 3.26.1 en escritorio budgie 10.4
 ...

**Steps to reproduce the issue**

Al cambiar los themas el icono de red aparece de mala manera y afecta la estetica de la barra de notificaciones.

 ...

**Comment by alunux** [comment]
@vendettaboom what are you talking about? Speak english, please.

**Comment by fossfreedom** [comment]
google translate:

The network icon has problems with thems after updating to gnome 3.26.1
When changing themas the network icon appears badly and affects the aesthetics of the notification bar.

**Comment by fossfreedom** [comment]
Difficult to tell here - sounds like a theme and/or iconset issue.

Suggest change these to verify.

Screenshots would be useful I think.  Closing until more information is supplied.
