### ISSUE TITLE
Can't select themes located in ~/.themes

### ISSUE THREAD

**Issue by rotsix** [budgie-desktop/budgie-desktop#1202]
Hi guys!

**Operating System**: Arch, up-to-date: Linux lili 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux
**Budgie version**: budgie-desktop v10.4-8-gff09a510

**The issue encountered**

 In the gtk-theme choosing menu, i can't see the themes located in ~/.themes (default user's gtk themes place).

My bad or just not implemented?

Thanks!

**Comment by ikeydoherty** [comment]
Default theme location is `~/.local/share/themes`, Mutter/GTK started to break `~/.themes` some time ago.

**Comment by rotsix** [comment]
Aw, okep, then I close! thanks :)

**Comment by ikeydoherty** [comment]
:)
