### ISSUE TITLE
Printer Details dialog missing close button

### ISSUE THREAD

**Issue by snowkeeper** [budgie-desktop/budgie-desktop#1218]
Solus 3.26.1
Budgie 10.4
When changing settings of a printer the title bar is barely present.  The only way to close the dialog window is to right click at just the right spot to get a close option in the context menu.
![printer-dialog](https://user-images.githubusercontent.com/6615106/32076883-7793b194-ba6f-11e7-8a4c-a0275f6d1606.png)
 ...
1. Add a printer
2. Select Printer Details from the settings menu of the new printer
3. Dialog window opens without a proper title bar.

 ...

**Comment by tista500** [comment]
I am an author of Adapta-gtk-theme.
This is neither Budige-desktop issue nor user-themes, but upstream python codes of Gnome-Control-Center 3.26.x.
A commit for this upstream issue: https://github.com/adapta-project/adapta-gtk-theme/commit/b88d553f00835206b0f5f9b9091ce4fd688a91c0

Upstream said 'FIXED' though, for me, that was a workaround with High-Contrast theme. I really want them to stop bundling those codes. If they could not handle GtkHeaderBar properly, they should revert to ServerSideDecorations...
Related commit: https://git.gnome.org/browse/gnome-control-center/commit/?id=00a45b3d70c2016e24edaa442eab36d7b11aa6f3

**Comment by tista500** [comment]
Adapta release 3.92.1.33: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.92.1.33

Rev.33 still had some issues in case very large/small fonts were applied, but should work as I expected with the font-size from 9pt to 11pt ...

@ikeydoherty so sorry for inconvenience of Adapta... This issue is not related to Budgie at all.

Regards.

**Comment by fossfreedom** [comment]
thanks - we'll close this now on this issue tracker.
