### ISSUE TITLE
Request for the cursor to have a blue contour when Night Light is activated

### ISSUE THREAD

**Issue by Extarys** [budgie-desktop/budgie-desktop#1219]
**Operating System**: Solus 3, I guess
**Budgie version**:budgie-desktop 10.4

**The issue encountered**

Nightlight make the cursor contour blue

**Steps to reproduce the issue**

Activate Nightlight and make the color temperature @ 3500-4500 (To see the effect properly)

**Comment by Hangman228** [comment]
To clarify, Night Light doesn't work on the cursor, so it appears to be blue. When I take a screenshot, the cursor is same color as the rest of the screen (red)

**Comment by Extarys** [comment]
Oh I see. But shouldn't it affect the whole screen since the cursor also have colors and with this feature enable the cursor's contour pop up so much it make it hard to actually focus on the content of the screen (it is subjective I agree)

**Comment by JoshStrobl** [comment]
This should be reported upstream with the Mutter project, they're responsible for feature requests / issues with Night Light / Night Mode.

**Comment by Extarys** [comment]
Sorry, I abandoned trying to use budgie as it is so much complicated making a ticket when there is an issue - there is like 5 websites where we can report issues and everytime ther eis someone saying it goes somewhere else and nobody can agree :P.

Too bad it looked so cool!

**Comment by JoshStrobl** [comment]
Not sure what you're on about.

1. Budgie issues go here.
2. Issues not related to Budgie go to their respective trackers. Mutter is developed by GNOME, this isn't an issue that just affects Budgie, and thus would get reported to GNOME.
