### ISSUE TITLE
[RFE] cpu temperature applet

### ISSUE THREAD

**Issue by juhp** [budgie-desktop/budgie-desktop#122]
It would be very useful to have a cpu temperature applet for BD.

It should just be something simple like showing "45 C".

I read there are plans for AppIndicator support: does that mean Ubuntu only?

Some people might want a more detailed System Monitor applet too.
##

**Comment by JoshStrobl** [comment]
We believe this functionality should be implemented "out of tree" (external to Budgie core) by the community.
