### ISSUE TITLE
Remap Caps Lock to Ctrl

### ISSUE THREAD

**Issue by jpo-** [budgie-desktop/budgie-desktop#1220]
**Operating System**: Solus 3.26.1
**Budgie version**: 10.4

**The issue encountered**

There is no ability in the Keyboard settings to remap the Caps Lock key to the Ctrl key within the Keyboard settings tool.  Using gnome-tweak-tool 3.26.2 package to change this setting also had no effect.

**Steps to reproduce the issue**
Initial approach:
- Press Super Key
- Click on System Settings -> Keyboard
- No options for changing Caps Lock mapping found.

With GNOME Tweak Tool:
- Open Software Center
- Search for GNOME Tweak Tool
- Install GNOME Tweak Tool - 3.26.2
- Press Super Key
- Click on Utilities->Tweaks->Keyboard & Mouse->Additional Layout Options
- Expand Caps Lock behavior
- Select Caps Lock is also a Ctrl
- Open Terminal
- Press Caps Lock-C, result "C" instead of ^C

**Comment by casucci** [comment]
Using gnome-tweak-tool, expand Ctrl position and select Caps Lock as Ctrl. This should provide the functionality you are looking for.

**Comment by jpo-** [comment]
Thanks casucci for the response!  That did it.  Much appreciated.
