### ISSUE TITLE
Login screen is black after 17.04 upgrade to 17.10

### ISSUE THREAD

**Issue by LilyMaster** [budgie-desktop/budgie-desktop#1221]
**Operating System**: Ubuntu Budgie 17.10
**Budgie version**: Budgie 10.4

**The issue encountered**

After upgrade from Ubuntu Budgie 17.04 to 17.10, the login screen is completely black. The mouse shows and is responsive. I am able to blind-type the login password and login, but there is no way to change the user. 

I was able to see the login screen just after the upgrade, but after 1-2 restarts it never came back.

My home is encrypted and the login background is from within. But that posed no troubles by displaying a default background until I logged in. Tried changing the login wallpaper to one of the default ones, did not help.

Locking the PC, the password screen is working, with the default and home-based background.
By selecting the 'Switch User', the login screen comes. The user selection can now be seen and users can be selected. My own user has a black background while the rest of the users display the default blue one.

**Steps to reproduce the issue**

Have a login with password.

**Comment by fossfreedom** [comment]
the login screen is called slick-greeter.  This isn't an issue with budgie and as such I'll close this here.

Please raise the issue here: https://github.com/linuxmint/slick-greeter

thanks.

**Comment by fossfreedom** [comment]
Note - I may be wrong with slick-greeter here.  It may be a lightdm issue.  You can test this by switching from slick-greeter to lightdm-gtk-greeter.  If the issue still occurs then raise a bug report on launchpad.net against the lightdm project.
