### ISSUE TITLE
Software Center: Checking for Chrome updates ignores authentication

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1223]
**Operating System**: e.g. Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**

When you "Check for updates" on Chrome, Software Center asks for a password. But if you hit Esc to abort, it starts the usual "This may take some time..." Chrome update process anyway.

**Steps to reproduce the issue**

From "Third Party" in Software Center, install Chrome. Get it working just to make sure it's installed properly. Reboot. Go to Software Center. Do as described above.

**Comment by fossfreedom** [comment]
This issue tracker is for budgie-desktop issues.  For distro specific issue please use your distro issue tracker.  In this case - https://dev.solus-project.com/
