### ISSUE TITLE
Show menus from windows applet not working for Evolution

### ISSUE THREAD

**Issue by sliddjur** [budgie-desktop/budgie-desktop#1227]
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"

budgie-desktop --version
budgie-desktop 10.4
Copyright © 2014-2017 Budgie Desktop Developers

Widget theme: Flat-Plat-compact
Built-in theme: unchecked
```

**The issue encountered**

The global menu "show menus from windows" applet doesnt work for evolution. It did work before a reboot, now the top panel global menus are gone. (see screenshot below). I also disabled the menus through the app in the view menu. 

If I open the "compose message" window, the menus appear _both_ in the app, and also in the top panel global menu.

**Steps to reproduce the issue**

Install show menus from windows applet and open Evolution.

_Main window in evolution. Neither in app menu or top menu menus appears._
![evolution](https://user-images.githubusercontent.com/10002057/32163918-2edfd42c-bd5e-11e7-9bee-e7a9d2ce537c.png)

_Compose Message in Evolution. Top panel global menu works partitially. It still shows in app menu._
![screenshot from 2017-10-30 10-37-20](https://user-images.githubusercontent.com/10002057/32163966-57d4f06a-bd5e-11e7-8452-c3ac34b0866c.png)

**Comment by fossfreedom** [comment]
Hi - the correct issue tracker for  this external budgie applet is here:

https://github.com/rilian-la-te/vala-panel-appmenu

thanks

**Comment by rilian-la-te** [comment]
@fossfreedom, can you provide an info about some things:
1. What settings daemon is used for Budgie?
2. How to set appmenu relevant properties for it (if it is Budgie-specific)?

**Comment by rilian-la-te** [comment]
link for my issue: https://github.com/rilian-la-te/vala-panel-appmenu/issues/144
