### ISSUE TITLE
FTBFS Budgie Desktop 10.4 on Debian Unstable/ Ubuntu 18.04

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#1228]
**Operating System**: Debian Unstable, Ubuntu 18.04
**Budgie version**: Budgie Desktop 10.4

**The issue encountered**

FTBFS due to latest meson version - same issue as fixed here: 
 https://github.com/budgie-desktop/budgie-desktop/commit/3d6d71c167dd9742cd072e7e6a3453c23ebb2658

However, unfortunately, cannot use this fix since no external network access is permissible outside the build environment for Debian/Ubuntu i.e. cannot meson git clone the GVC project.

**Comment by ikeydoherty** [comment]
OK so - this change is in git not 10.4 (was issued after git tag) - are you actually saying you **need** that fix due to some build issue with plain 10.4? Because tbh it could even be worth kludging together a temporary tarball..

**Comment by ikeydoherty** [comment]
OK so @fossfreedom I don't know if this'll fly with Debian guys (maybe ask @jbicha) but I've created a new signed tarball from git here:

https://solus-project.com/sources/budgie/

It has 10.4+9 commits on top, and is signed using my GPG key. That might get you out of this mess?

**Comment by fossfreedom** [comment]
thanks.  Yes - likely need to have something to call on before someone kicks off a rebuild.  It has happened twice in the recent weeks due to stuff transitioning in Debian.

I'll have a look at the tarball soonest.  cheers.

**Comment by ikeydoherty** [comment]
aah ok - yeah can't have it looking bad in the queue :)

**Comment by ikeydoherty** [comment]
Problem is the cherry-picked patch is an update of a git submodule

**Comment by jbicha** [comment]
Ok, fossfreedom just needs to use a different filename for the .orig.tar.xz and update debian/changelog to match it.

**Comment by ikeydoherty** [comment]
```
budgie-desktop-10.4.tar.xz      budgie-desktop-v10.4+git-9-gf8118dc.tar.xz
budgie-desktop-10.4.tar.xz.asc  budgie-desktop-v10.4+git-9-gf8118dc.tar.xz.asc
```

just uploaded into the same directory

**Comment by fossfreedom** [comment]
Thanks @ikeydoherty - looks ok; there is an oddity which I'll mention on a separate issue. I'll close this.  cheers for your help.
