### ISSUE TITLE
Budgie Desktop  Top Panel  Calendar doesn't open

### ISSUE THREAD

**Issue by SLmanDR** [budgie-desktop/budgie-desktop#1244]
Reporting issue for Budgie Desktop:

**Operating System**:    OS: Solus x86_64, Kernel: 4.13.11-31.current

**Budgie version**:    WM: Mutter(Budgie), Theme: Adapta-Eta [GTK2/3], Icons: Paper [GTK2/3], budgie-desktop 10.4

**The issue encountered**
    Selecting the Calendar from within the Top Panel opens 2 tabs for untitled documents in gedit. 
 ...

**Steps to reproduce the issue**
    Click on "Time and Date in the Top Panel. Select "Calendar" in the dialog box. 
    Happens every time.
    Changing any / all of the preferences has no bearing on the results.

 ...

**Comment by casucci** [comment]
Setting "Calendar" as the default application for Calendar in gnome-control-center has worked for me. Open gnome-control-center or "Settings" from Budgie menu, select "Details" tab, "Default Applications". The pull-down menu should give the option for "Calendar" if it is installed.

**Comment by SLmanDR** [comment]
Yep, confirmed. My default "Open Calendar in" was Text Editor. The Default for what to open Calendar with should be Calendar.
