### ISSUE TITLE
Budgie menu label's font is different from the panel font

### ISSUE THREAD

**Issue by manasthakur** [budgie-desktop/budgie-desktop#1254]
Budgie Settings allow us to provide a custom image and label for the menu applet. However, the font of the label is drastically different from the panel font (Noto I guess). This doesn't look good. Can the label font be made to follow the default desktop font?

**Comment by fossfreedom** [comment]
have you got a screenshot? - the font here looks exactly the same.

**Comment by manasthakur** [comment]
Sure. Please zoom the image to notice the difference.
![screenshot from 2017-11-19 15-26-46](https://user-images.githubusercontent.com/5248710/32989545-68e5a8a0-cd3e-11e7-984e-bdf931e05d3a.png)

**Comment by tista500** [comment]
If Adapta specific, can be closed with that commit: https://github.com/adapta-project/adapta-gtk-theme/commit/306a0807fa9421502cb70da2aa919589adc53835

**Comment by manasthakur** [comment]
Yes, looks like it was adapta-specific (tried with adwaita and raleigh to cross-check). Should be solved with the mentioned adapta update in my OS (Solus). Thanks for the fast response 👍
