### ISSUE TITLE
For many filetypes, default application changes to 'last used application'

### ISSUE THREAD

**Issue by cameralibre** [budgie-desktop/budgie-desktop#1265]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4

**The issue encountered**

**1.** Filetypes which are not covered under the _Default Applications_ list (eg. .pdf, .md, .sif, .kdenlive) will not maintain a consistent default application - instead, they will always open with the **last application used**.

**2.** The _Default Applications_ list requires that all files classed as 'Photos' are opened in the same way - there does not appear to be a way to reliably set PNG & JPEG to open with Image Viewer, while having SVG open in Inkscape (it seems strange to class an SVG as a photo anyway).

![defaults](https://user-images.githubusercontent.com/15368010/33673195-6db161fa-daac-11e7-84d6-3172d0a90c88.png)

Forum post outlining this issue: [Open filetype with default application, not last application](https://solus-project.com/forums/viewtopic.php?f=8&t=10719)

 ...

**Steps to reproduce the issue**
[See reference video](https://cloud.cameralibre.cc/s/7t0ajqKuIuoUJWE)

1. Inkscape is the current default application for PDFs
2. I open the PDF by right-clicking and choosing 'Document Viewer' from the 'other application list'
3. Document Viewer is now the default for PDFs
4. Double-clicking opens the file in Document viewer.
5. I open the file with Inkscape.
6. Inkscape is now the default
7. Double-clicking opens it in Inkscape.

 ...

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue, this is a GNOME Control Center and its use of various GLib appinfo functions.

**Comment by cameralibre** [comment]
thanks for that - [bug filed](https://bugzilla.gnome.org/show_bug.cgi?id=792911) against GNOME Control Center
