### ISSUE TITLE
Issue changing audio output in raven menu

### ISSUE THREAD

**Issue by bwat47** [budgie-desktop/budgie-desktop#1276]
OS: Solus 3
Budgie Version: 10.4.0
Hardware: XPS 13 9360

I have a small USB dac that I use with my laptop.

When I plug it into my laptop, there's two outputs added:

Digital Output (S/PDIF) - PCM2706 stereo audio DAC

and

Analog Output - PCM2706 stereo audio DAC

In order to be able to control the volume, I need to have the Digital Output selected. 

However, if I try opening the budgie raven menu and changing the output to the digital one there, nothing happens. I check the box for the digital output and it just remains on the analog one.

If I go to gnome settings manager | sound tab and select it there it works fine.

**Comment by th3math3us** [comment]
Looks like this issue
https://github.com/budgie-desktop/budgie-desktop/issues/1102
