### ISSUE TITLE
In the file manager there is no possibility to create a file

### ISSUE THREAD

**Issue by Drovosek01** [budgie-desktop/budgie-desktop#1277]
Lang=ru
Solus 3

In the file manager there is no possibility to create a file, only create folder

**Comment by ICA3DaR5** [comment]
That is bugging me too!

**Comment by fossfreedom** [comment]
The file manager you are using is probably nautilus and as such is not a budgie desktop matter.  As such I will close this.
As an aside save a file type in your Templates folder and you will be offered to create this file type in nautilus.
