### ISSUE TITLE
The problem with change language during installation

### ISSUE THREAD

**Issue by Drovosek01** [budgie-desktop/budgie-desktop#1278]
Lang=ru
Solus 3 Budgie

During installation I selected Russian language and Russian keyboard layout. When it was necessary to enter the computer name/host I was not able to change the language to English. I tried to enter different combinations and Alt+Shift and Ctrl+Space and Super+Space, but the language has not changed.

**Comment by ICA3DaR5** [comment]
Select English as the keyboard language during installation.

Change that after installation to Russian.

**Comment by fossfreedom** [comment]
Please raise this matter on your distro installer issue tracker. This is for budgie desktop matters. Many  thanks.
