### ISSUE TITLE
Bug, add theme

### ISSUE THREAD

**Issue by LinuxVieLoisir** [budgie-desktop/budgie-desktop#1282]
Hello,

I installed budgie desktop on my arch linux and I found a bug when we add a theme (ex : vertex)
On the budgie menu. 
![bug](https://user-images.githubusercontent.com/29429483/34558310-df22559a-f13d-11e7-9fe1-f0b8d8aa4307.png)

We have of black on the menu when we have not a lot of application in the categorys.

Best regards.

**Comment by fossfreedom** [comment]
GTK based themes need to have extra budgie desktop styling.  Vertex probably hasnt yet caught up with the extra styling required for budgie v10.4

Please bring that up on the vertex issue tracker.

**Comment by Vistaus** [comment]
@fossfreedom How exactly do you include styling for Budgie? 'Cause I did look at the wiki but I found it to be a bit vague.

**Comment by fossfreedom** [comment]
Easiest way is to study themes that have complete budgie styling built in such as adapta material and pocillo themes. Have a look at the budgie.scss file or similarly named to see what the extra styling elements are needed to complete budgie.

**Comment by Vistaus** [comment]
@fossfreedom Thanks, will do! :)

**Comment by Vistaus** [comment]
@fossfreedom Hmm, I can't find anything about Budgie in Adapta (I know it supports it as it's the default Solus theme, but I can't find the styling elements in the Adapta code).

**Comment by alunux** [comment]
@Vistaus how about this? https://github.com/adapta-project/adapta-gtk-theme/search?q=budgie&unscoped_q=budgie

**Comment by fossfreedom** [comment]
@Vistaus if it helps - this is the budgie specific stuff I developed for Pocillo https://github.com/UbuntuBudgie/pocillo-gtk-theme/blob/master/src/gtk-3.0/3.22/sass/apps/_budgie.scss

**Comment by Vistaus** [comment]
@alunux Thanks! I added it to the theme I'm editing, but after adding, all windows become transparent :/

**Comment by Vistaus** [comment]
@fossfreedom Same: after adding, all windows become transparent :/
