### ISSUE TITLE
[Feature Request] Automatically Inhibit Suspend During Media Playback

### ISSUE THREAD

**Issue by hfel** [budgie-desktop/budgie-desktop#1287]
The title is pretty self-explanatory...

**Comment by ICA3DaR5** [comment]
You can install the **budgie-caffeine-applet**, does exactly that.

**Comment by hfel** [comment]
Caffeine only enables manual user control AFAIK, what I'd like to see is the DE doing this automatically whenever some media is playing.

**Comment by ikeydoherty** [comment]
Budgie itself doesn't play media. Applications do and they should talk to org.gnome.Session to add an inhibit when doing so, just like Google Chrome does.

**Comment by hfel** [comment]
Not at all important, but I'd like to know if with Budgie 11 moving to Qt the mechanism for this will change as well.
