### ISSUE TITLE
Pt-BR translation issues

### ISSUE THREAD

**Issue by th3math3us** [budgie-desktop/budgie-desktop#1293]
**Operating System**: e.g. Solus 3.26.2
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**

https://i.imgur.com/ZFUaWi6.jpg

https://i.imgur.com/H8TV3BA.jpg

**Comment by fossfreedom** [comment]
Its not very clear from your pictures - but I suspect you are possibly right clicking the desktop?  Any you are showing gnome-control-center Settings?

If so, it means that these areas have not been translated by the relevant GNOME software components.

This doesnt look like a  budgie desktop issue.

**Comment by th3math3us** [comment]
It should be in brazilian portuguese
The first one happens right clicking on Firefox in the panel
The second happens when I change the resolution

**Comment by JoshStrobl** [comment]
Neither of those are Budgie issues. One is likely missing translations in the software itself (GNOME Control Center) and the other (menu) is likely non-existent translations in a desktop file, none of which we're responsible for.
