### ISSUE TITLE
Default Applications displays firefox twice.

### ISSUE THREAD

**Issue by Siriusval** [budgie-desktop/budgie-desktop#1297]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4.150

**The issue encountered**
In Default Applications, the Web drop-down list displays Firefox twice.

![screenshot from 2018-01-24 21-26-12](https://user-images.githubusercontent.com/35781555/35355936-3d4b8774-014f-11e8-8eac-7f30fd182efa.png)

**Steps to reproduce the issue**
Settings > Details > Default Applications.

**Comment by fossfreedom** [comment]
That is a GNOME app not budgie.  Suggest raise a query on your distro issue tracker - phabricator I think for Solus.
