### ISSUE TITLE
Budgie Desktop crashing with WINE

### ISSUE THREAD

**Issue by cbstryker** [budgie-desktop/budgie-desktop#1299]
**Operating System**: Ubuntu Budgie 17.10
**Budgie Desktop version**: 10.4
**Graphics Card**: GTX 1050 ti
**Nvidia Driver**: 390.12
**Proc**: Xeon E3-1230 v5
**Memory**: 32GB

**The issue encountered**

This is happening with both PlayOnLinux and Crossover. After launching Steam and it being open for about 10 seconds to a minute, the Budgie panel will flicker a few times (seems like it's crashing and restarted very rapidly multiple times). Then after another 10 seconds the entire desktop crashes and I get kicked out of my session. Here are the relevant lines from syslog: [Pastebin](https://pastebin.com/cUwyHUdZ).

I have tried completely purging both PlayOnLinux and Crossover, then reinstalling Crossover but the issue persists.

**Steps to reproduce the issue**

I do not know how the issue arose, but the issue occurs consistently when launching the Windows version of Steam in WINE. I have not tested any other Windows applications in WINE.

**Comment by fossfreedom** [comment]
Sounds more like a WINE issue - your log says "The program 'budgie-panel' received an X Window System error." - so the flickering is because WINE is poking the panel with something it should never receive.

**Comment by cbstryker** [comment]
After further testing and reading of logs, I think this might be a graphics driver issue. I reverted to NVidia's 387 driver and the situation is different now. I get the flickering, but the desktop session is no longer crashing. Thanks for responding @fossfreedom
