### ISSUE TITLE
Screen doesn't lock until after resume

### ISSUE THREAD

**Issue by bwat47** [budgie-desktop/budgie-desktop#1304]
Solus 3 with all updates
Budgie 10.4 desktop

Steps to Re-create:
1. Settings | Privacy | enable automatic screen lock with the 'screen turns off' setting
2. Close laptop lid to suspend

Expected: suspend should be inhibited until screen is locked. upon resume you should immediately see the lock screen

Actual: upon resume, instead of seeing the lock screen you see your desktop, and the lock screen activates a second or so later.

After the lock screen activates, it then turns your screen off so you need to move your mouse to show the lock screen

**Comment by timotk** [comment]
I have the same issue on the latest Solus. I believe this is a gnome-screensaver issue since I had the exact same problem on Ubuntu.

**Comment by fossfreedom** [comment]
Duplicate https://github.com/budgie-desktop/budgie-desktop/issues/1374

**Comment by bwat47** [comment]
Just in case anyone comes cross this issue in a search, I've found the following workaround for this issue:

Create the file /usr/lib/systemd/system-sleep/resumepre.sh

With the contents:

#!/bin/sh
case $1 in
pre)
/usr/bin/xset -display :0 dpms force off
;;
esac

Make the file executable:

chmod 755 /usr/lib/systemd/system-sleep/resumepre.sh

Then, create the file /usr/lib/systemd/system-sleep/sleep.sh

With the contents:

#!/bin/sh
case $1 in
pre)
/bin/sleep 2
;;
esac

Make the file executable:

chmod 755 /usr/lib/systemd/system-sleep/sleep.sh


This does two things: shuts the screen off prior to suspend, and delays suspend for 2 seconds (so that the screen has time to shut off). On my system, with these scripts I no longer see the contents of my desktop before the lock screen activates, and I no longer have the issue where my screen turns off after resume. When I resume I see a black screen, and then the lock screen (and my screen stays on) as expected.
