### ISSUE TITLE
Can't switch languages when in Super menu

### ISSUE THREAD

**Issue by thumos333** [budgie-desktop/budgie-desktop#1306]
Hi,
It isn't possible to switch between keyboard layouts when the Super key menu is open. In my case, the languages are English and Russian, while Alt + Space and Shift + Alt + Space are the combinations used to switch to next / previous input source.
Would appreciate very much if this issue is addressed.

Solus version is 3.26.2.
Budgie version is 10.4.

**Comment by JoshStrobl** [comment]
Duplicate of #420

**Comment by thumos333** [comment]
I believe this doesn't duplicate thread #420 . The issue is that I can switch languages when in Super menu, although it remains open.

**Comment by odmin4eg** [comment]
I agree with the author, I have the same problem, it causes significant inconvenience to using DE
