### ISSUE TITLE
[Remmina] Doesn't start minimized

### ISSUE THREAD

**Issue by bobblkabb** [budgie-desktop/budgie-desktop#1310]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4 Release 150

**The issue encountered**
Remmina is set up to start automatically after every system start. Even though it's configured in remmina it starts maximized.

**Steps to reproduce the issue**

1. Remmina settings -> Applet -> 'start remmina in tray icon at user logon'
2. Budgie settings -> Autostart -> add remmina

**Comment by ikeydoherty** [comment]
1) What is Solus 3.26.2..?

2? Budgie isn't responsible for the code in Remmina, I'm not sure why you believe this to be a Budgie issue, and not a Remmina issue?

**Comment by bobblkabb** [comment]
Okay. Will open a remmina ticket.

**Comment by bobblkabb** [comment]
...Info's showing 'Version 3.26.2'. I know it's Solus 3 but - again - Info says '**name** of the os: Solus 3' (translated from German).
So 3.26.2 is the only reference to a version number.

**Comment by ikeydoherty** [comment]
It shows the GNOME version as 3.26.2 - I'll nuke that from the info pane :)

Does Remmina do this on other desktops on Solus..?

**Comment by bobblkabb** [comment]
Oha! You're right. Started my old Laptop with Linux Mint. The same! 
Bastards! ;-)

**Comment by bobblkabb** [comment]
> We support Remmina 1.2+ versions only.
> Please do not report bugs occurring on older versions!

We've got 1.1.2..

**Comment by ikeydoherty** [comment]
Guess we should update that, assuming they finally put out a new stable tag.

**Comment by bobblkabb** [comment]
@ikeydoherty Shall I open an issue on dev.solus-project.com?
