### ISSUE TITLE
Allow Terminal in Software Center

### ISSUE THREAD

**Issue by boustanihani** [budgie-desktop/budgie-desktop#1311]
Please allow the user to see the terminal output when installing packages through the software center.

Another issue, when installation starts, the progress is at the very bottom of the software center and one may not notice this, the installation progress should be made more visible to the user.

**Comment by fossfreedom** [comment]
Please raise non-Budgie Desktop issues on your distro tracker.  This tracker is only for the desktop interface itself. 

thanks.

**Comment by boustanihani** [comment]
isn't the Budgie-Software-Center part of the Budgie-Desktop?

**Comment by fossfreedom** [comment]
@boustanihani no - that is part of your distro - Solus, Ubuntu, Manjaro ... whatever you are using.

**Comment by boustanihani** [comment]
okay thanks
