### ISSUE TITLE
Keyboard shortcuts open apps in the background, not the foreground

### ISSUE THREAD

**Issue by Iiari** [budgie-desktop/budgie-desktop#1314]
When reporting issues for Budgie Desktop, ensure you read these guidelines and delete this first
introductory paragraph. If including build failures, or general tool output, please ensure they are
in English, i.e. `LC_ALL=C LANG=C`. If your issue is a Budgie *crash*, include a stack trace. (gdb)

Ubuntu Budgie 17.10 (but happened in Solus 3 too)
Budgie 10.4

Frequently, when pressing a keyboard shortcut that opens an app (Nautilus, terminal, etc) the app will open behind other running windows, rather than the foreground.  It occasionally will open in the foreground too, it's really a tossup what it does.  

Reported also in '16: https://github.com/budgie-desktop/budgie-desktop/issues/723

**Comment by cj-sv** [comment]
Yep, confirmed here as well. Though, not the case for the default terminal shortcut.

- Ubuntu 17.10
- Budgie 10.4

**Comment by fossfreedom** [comment]
given that #723 covers this issue as well ... we'll close this as a duplicate to keep the issues list as tidy as possible.  thanks
