### ISSUE TITLE
Night mode deactivate after black screen for inactivity

### ISSUE THREAD

**Issue by Nariod** [budgie-desktop/budgie-desktop#1315]
**Operating System**: Solus 3.26.2
**Budgie version**: budgie-desktop 10.4

**The issue encountered**

The night mode option no longer works after the screen went black (because of inactivity).

**Steps to reproduce the issue**

Turn on "Automatic Night mode", let your screen turn black because of inactivity. Night mode is no longer working, but the option is enabled in Settings.

To make it work again, you need to deactivate and reactive night mode.
 ...

**Comment by fossfreedom** [comment]
Duplicate issue https://github.com/budgie-desktop/budgie-desktop/issues/1284
