### ISSUE TITLE
Cannot resume from hibernation

### ISSUE THREAD

**Issue by TehDaniel37** [budgie-desktop/budgie-desktop#1320]
**Operating System**: Solus 3.26.2
**Budgie version**: Budgie 10.4 

**The issue encountered**

Nothing happens when resuming from hibernation, the screen just stays black. Waited ~ 5 minutes before giving up.

I figured the kernel command line wasn't configured for hibernation so I followed [these](https://solus-project.com/articles/troubleshooting/boot-management/en/#appending-kernel-parameters-to-solus-boot) instructions to add `resume=UUID=491fefcf-70e8-47cc-a70b-680e5fa49f05` (Where `491fefcf-70e8-47cc-a70b-680e5fa49f05` is my swap partitions UUID) to the kernel command line. After updating the bootloader and rebooting, `dmesg | grep "Kernel command line:"` gave:

```
[    0.000000] Kernel command line: initrd=\EFI\com.solus-project\initrd-com.solus-project.current.4.14.18-51 root=PARTUUID=bb73ddab-0b7d-dd4a-8601-d5d45407e4ad quiet loglevel=3 splash systemd.show_status=false rw radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 resume=UUID=491fefcf-70e8-47cc-a70b-680e5fa49f05
```  

So that seemed to have worked. But I still cannot resume from hibernation, I still just get a black screen. Any ideas?

Edit: Oh, and I forgot to mention: My swap partition is 6GB in size, for a machine that has 6GB of RAM. And was using < 2GB when I was trying to hibernate. So I don't think it's the size of the swap partition that is the problem.

**Steps to reproduce the issue**
1. Create file `/etc/kernel/cmdline` with contents "resume=UUID=[UUID of swap partition]"
2. run `sudo clr-boot-manager update`
3. reboot
4. When logged in, press power widget on panel and select hibernate.
5. Boot machine after hibernation finishes

**Comment by fossfreedom** [comment]
This is more like a kernel issue rather than a budgie desktop issue.  I would suggest you raise this on your solus distro issue tracker

**Comment by TehDaniel37** [comment]
Okay, I'll submit the issue to the Solus development portal then. Thanks for the quick reply!
