### ISSUE TITLE
problem with the dropdown menu of some apps

### ISSUE THREAD

**Issue by subrms** [budgie-desktop/budgie-desktop#1321]
**Operating System**: Solus 3
**Budgie version**:  Budgie 10.4

**The issue encountered** :
There is  UI problem with drop-down menu of some apps. 
I encountered the problem with two applications : Visual Studio Code and LibreOffice. 

Visual Studio Code : 

<a href="https://ibb.co/bvCN6S"><img src="https://thumb.ibb.co/bvCN6S/Capture_du_2018_02_10_16_22_59.png" alt="Capture_du_2018_02_10_16_22_59" border="0"></a>

LibreOffice : 

<a href="https://ibb.co/e3P5t7"><img src="https://thumb.ibb.co/e3P5t7/Capture_du_2018_02_10_16_24_04.png" alt="Capture_du_2018_02_10_16_24_04" border="0"></a>
 
**Steps to reproduce the issue :** 

- Visual Studio Code : Clic on "display" in the drop-down menu 
- LibreOffice : Clic on all the drop-down menu except "help" and "window".

**Comment by rilian-la-te** [comment]
But this menus is big. May you have a small screen?
Do you have a more problems with menu except scrollbuttons?

**Comment by subrms** [comment]
I have a 14'' screen. 
Yes, I think that it happens with big menus with scrollbutons, that's the problem ans this is unpleasant

**Comment by rilian-la-te** [comment]
I man resolution) I also have a 14" screen, but 1920x1080.

**Comment by subrms** [comment]
Ok, so it's because of my 1366x768 screen resolution .. So i close the issue ?

**Comment by fossfreedom** [comment]
This is not a budgie desktop issue. The apps have large menus and they are trying to compensate with your limited vertical resolution through scroll menus. This is normal behaviour.

**Comment by nextgensparx** [comment]
@subrms I already reported the issue with LibreOffice [on their bug tracker](https://bugs.documentfoundation.org/show_bug.cgi?id=113713) in case you are interested.
