### ISSUE TITLE
Add gnome-control-center as dependency for desktop.budgie?

### ISSUE THREAD

**Issue by lucascnunes** [budgie-desktop/budgie-desktop#1325]
Hi, I am using Solus for a while now and was using the mate desktop environment.
Just now I installed the Budgie desktop using the command that is listed on the website.

`sudo eopkg install -c desktop.budgie`

the installation went all the way, no problem but the only dependencies when prompted the confirmation were:
```
budgie-caffeine-applet  budgie-calendar-applet           
budgie-desktop          budgie-desktop-branding          
budgie-haste-applet     budgie-screenshot-applet         
gnome-app-templates     vala-panel-appmenu-budgie-desktop

```

After the installation the system control center wasn't working, I've founded the problem here in the budgie github but I would like to make a suggestion, maybe put the `gnome-control-center` as dependency?

Now everything is working as it was supposed to.

Sorry if I'm being redundant.

**Comment by cybre** [comment]
This is not a Budgie issue. The issue should have been raised on the Solus dev portal. Remember that eopkg components are not metapackages.
