### ISSUE TITLE
Buttons not reachable on some windows

### ISSUE THREAD

**Issue by Staudey** [budgie-desktop/budgie-desktop#1329]
**Operating System**: Solus 3
**Budgie version**: Budgie 10.4

**The issue encountered**
On my low resolution laptop display (1366x768), I can't reach the buttons on some dialogue windows, like the Hexchat preferences windows (also somewhat depending on the Widget theme). The buttons are below the bottom panel, and I can't move the window further up than the top of the display, which is not enough to move the buttons above the height of the panel. This makes it impossible to reach the buttons with the mouse in some cases. See screenshot: [https://i.imgur.com/PJZfBd2.png](https://i.imgur.com/PJZfBd2.png) (Buttons should be on the bottom right, but are hidden below the panel)

**Steps to reproduce the issue**
1. Set resolution to 1366x768.
2. Set Budgie widget theme to e.g. Adapta.
3. Open Hexchat.
4. Open Hexchat Preferences.
5. Try to reach the buttons on the bottom right.

**Comment by JosephMcc** [comment]
You should be able to use Alt + mouse drag to move the window so you can get to the buttons. You should probably bring this up to the Hexchat devs.

**Comment by Staudey** [comment]
No, one cannot move the window further up than the top of the display, which is not enough to make the buttons appear.
Are you sure this isn't a Budgie issue?

**Comment by JosephMcc** [comment]
I'm not on budgie this second but putting the mouse in the middle of the window, holding Alt and left click and dragging the window doesn't let you move the window further up?

**Comment by Staudey** [comment]
No, that doesn't actually let me move the window at all. But for example right-clicking the title bar, selecting "Move" and then moving with the arrow buttons doesn't let me move it further than the top of the display either.

**Comment by fossfreedom** [comment]
This isnt a budgie-issue per se.  Hexchat needs to reduce the size of their dialog.  Raise this on the hexchat issue tracker.  

Check if making the panel autohide will give you just enough pixels to see and  press the buttons on the hexchat dialog.

I'll close this to keep things tidy.

**Comment by Staudey** [comment]
Alright, will put this on the HexChat issue tracker. Even with the panel hidden I can't reach the buttons.
