### ISSUE TITLE
Gnome Calendar segmentation fault on launch

### ISSUE THREAD

**Issue by wheeljack73** [budgie-desktop/budgie-desktop#1332]
Budgie Desktop version: 10.4
Solus 3
Gnome 3.26.2
Evolution 3.26.5

**The issue encountered**

 Gnome-Calendar segmentation fault on launch.  Can't get Calendar open.
Calendar in Evolution working correctly.  Launched Calendar from terminal so I could see the crash as otherwise on desktop calendar comes up for a second then closes straight away.

**Steps to reproduce the issue**

Launch Gnome-Calendar (through terminal or launcher) and it will close every time.  I don't open Calendar often, so unsure as to when the issue started.

**gdb output**
~ $ gdb -q gnome-calendar
Reading symbols from gnome-calendar...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/gnome-calendar 
warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib64/libthread_db-1.0.so
line to your configuration file "/home/jamie/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/jamie/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: File "/usr/lib64/libstdc++.so.6.0.24-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
[New LWP 3277]
[New LWP 3278]
[New LWP 3279]
[New LWP 3280]
[New LWP 3281]
[New LWP 3282]
[New LWP 3283]
[New LWP 3284]
[New LWP 3285]
[New LWP 3286]
[New LWP 3287]
[New LWP 3288]
[New LWP 3289]

** (gnome-calendar:3273): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(gnome-calendar:3273): Gtk-WARNING **: Theme directory  of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/actions of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/animations of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/apps of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/categories of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/devices of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/panel of theme EvoPop has no size field
(gnome-calendar:3273): Gtk-WARNING **: Theme directory 22x22@2x/places of theme EvoPop has no size field

[New LWP 3302]
[New LWP 3303]
[New LWP 3304]
[LWP 3302 exited]
[LWP 3303 exited]
[LWP 3304 exited]
[New LWP 3308]
[New LWP 3309]
[New LWP 3310]
[LWP 3308 exited]
[LWP 3309 exited]
[LWP 3310 exited]
[New LWP 3314]
[New LWP 3315]
[New LWP 3316]
[LWP 3314 exited]
[LWP 3315 exited]
[LWP 3316 exited]
[New LWP 3320]
[New LWP 3321]
[New LWP 3322]
[LWP 3320 exited]
[LWP 3321 exited]
[LWP 3322 exited]
[New LWP 3340]
[New LWP 3342]
[New LWP 3344]

Thread 1 "gnome-calendar" received signal SIGSEGV, Segmentation fault.
0x000000000044a789 in icaltime_to_datetime ()
(gdb) backtrace
#0  0x000000000044a789 in icaltime_to_datetime ()
#1  0x000000000043a4a2 in gcal_event_widget_sort_events ()
#2  0x00007ffff716dc13 in  () at /usr/lib/libglib-2.0.so.0
#3  0x000000000041ea0a in  ()
#4  0x00007ffff724f559 in g_cclosure_marshal_VOID__OBJECTv () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff724c5a6 in  () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff7267e04 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff72683ef in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7939a35 in gtk_container_add () at /usr/lib/libgtk-3.so.0
#9  0x000000000041d1ad in  ()
#10 0x000000000044f899 in  ()
#11 0x0000000000450097 in  ()
#12 0x00000000004520e7 in  ()
#13 0x00007ffff724f412 in g_cclosure_marshal_VOID__POINTERv () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff724c5a6 in  () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff7267e04 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff72683ef in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff70f1f7c in  () at /usr/lib/libecal-1.2.so.19
#18 0x00007ffff7172365 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff7172730 in  () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff71727bc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff733221d in g_application_run () at /usr/lib/libgio-2.0.so.0
#22 0x000000000041b464 in main ()
(gdb)

**Comment by fossfreedom** [comment]
This isn't a budgie-desktop issue per se. It is something with your current setup on your distro. Please raise this on the Solus issue tracker. 

I will close this here to keep the budgie desktop issue list tidy. Thanks.
