### ISSUE TITLE
New Papirus Budgie Settings icon lower resolution than matching Settings icon

### ISSUE THREAD

**Issue by thephonypope** [budgie-desktop/budgie-desktop#1333]
Solus 3
Budgie version 10.4

**Issue**
Icon for "Budgie Settings" noticeably lower resolution than other icons including the (nearly) identical icon for "Settings"

**How to reproduce**
Install latest version of papirus-icon-theme 20180214

![screenshot from 2018-02-16 18-42-44](https://user-images.githubusercontent.com/36553938/36334139-9dfbe2da-1351-11e8-8f92-cedb8f2dbfa8.png)

**Comment by fossfreedom** [comment]
So this is a papirus icon theme issue?  Please report it on that issue tracker.

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
