### ISSUE TITLE
Slick-Greeter displaying desktop wallpaper instead of lockscreen wallpaper

### ISSUE THREAD

**Issue by theCalcaholic** [budgie-desktop/budgie-desktop#1334]
**Operating System**: Ubuntu Budgie 17.10
**Budgie version**: 10.04

It would be a lot more intuitive if slick greeter displayed a users lock screen background image instead of the desktop background. If that's not possible it would at least be very convenient to provide a override option (to set the background for slick greeter explicitly).

**Comment by JoshStrobl** [comment]
We don't develop slick-greeter, thus this isn't a Budgie issue.

**Comment by fossfreedom** [comment]
@JoshStrobl FYI - this isn't a slick-greeter issue per se - desktops such as budgie, mate can interact with lightdm via dbus.  So desktops can tell lightdm "use this wallpaper".

This request though is kind of a moot point - apparently GNOME 3.28 are redesigning the gnome-control-center background screen - the ability to change the lock screen wallpaper is being removed.

**Comment by theCalcaholic** [comment]
Ok, thank you for your responses.
