### ISSUE TITLE
Screenshot Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by 8bitcoderookie** [budgie-desktop/budgie-desktop#1339]
Solus3; all updates installed; Version: budgie-desktop 10.4
As [suggested in the Solus Forums](https://solus-project.com/forums/viewtopic.php?f=14&t=11452) I report this as an budgie-desktop issue:
The Screenshot section in the keyboard shortcuts list looks like
![keyboard-screenshots](https://user-images.githubusercontent.com/5789697/36564374-64b12046-181d-11e8-8f4c-62c6351a2f85.png)
But none of the screenshot keyboard shortcuts is working with budgie-desktop

Thanks!

**Comment by fossfreedom** [comment]
This is covered by this issue. https://github.com/budgie-desktop/budgie-desktop/issues/261

Thanks.  I'll tidy up by closing this since its a duplicate.

**Comment by 8bitcoderookie** [comment]
Sorry, I filtered all issues before writing, but did not found issue 261
Thanks!
