### ISSUE TITLE
Software Center hangs on retry of third party updates

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1342]
**Operating System**: Solus 3.26.2
**Budgie version**:  Budgie 10.4

**The issue encountered**

(See title.)

**Steps to reproduce the issue**

When updating ("Check for updates") a third party app in Software Center, it just shows a pingponging progress bar (which is quite uninformative to begin with). If you click the "Check for updates" button again in the middle of this process (because you think maybe the pingponging doesn't represent actual progress), then you'll get a dialog that says:

[u'cannot invoke setopt() - perform() is currently running']

which is equally uninformative. The entire Software Center then freezes and becomes uncloseable.

**Comment by fossfreedom** [comment]
This is not a budgie-desktop issue per se - its a issue that should be raised on your Solus distro issue tracker.

thanks.
