### ISSUE TITLE
[Feature request] MPRIS control applet

### ISSUE THREAD

**Issue by jakewithaflake** [budgie-desktop/budgie-desktop#1345]
I think it would be nice to have MPRIS controls on the panel, and maybe an option to make the applet auto-hide when there are no media players running.

**Comment by rilian-la-te** [comment]
But what about RAVEN. AFAIK when I use Budgie, there are MPRIS in RAVEN builtin.

**Comment by fossfreedom** [comment]
Agreed.  This isn't really in scope - MPRIS control is well covered via the notification and Raven.

A third-party is welcome to create such an applet.
