### ISSUE TITLE
Application prevents workspace switching

### ISSUE THREAD

**Issue by rorycurtis** [budgie-desktop/budgie-desktop#1346]
**Operating System**: Ubuntu 17.10
**Budgie version**: 10.4

I installed DB Browser for SQLite via software centre. When switching workspaces with SQLite DB Browser running, the desktop always goes back to the workspace that SQLite DB Browser is using. It's as though the app is grabbing the focus when the workspace switch is fired.

1. Open some apps on workspace 1.
2. Open DB Browser for SQLite on workspace 2
3. Try and switch back to workspace 1. The desktop switches for a second and then reverts back to DB Browser for SQLite on workspace 2. There is no way to get the desktop to stay on another workspace, without stopping DB Browser for SQLite. At that point, normal workspace switch resumes.

I haven't reproduced this with any other app yet. If I do, I'll add the details here.

**Comment by YoyPa** [comment]
Same on Manjaro but it seems related do the app itself not to budgie-desktop
https://github.com/sqlitebrowser/sqlitebrowser/issues/934

If you click ```View -> Edit Database Cell (CTRL+E)``` you will be able to change workspace again (work for me).

**Comment by fossfreedom** [comment]
Thanks for the confirmation.  Closing since this is an app specific issue and should be tracked via the application issue tracker.

**Comment by rorycurtis** [comment]
Great find @YoyPa. Thanks for the tip.
