### ISSUE TITLE
Texture in corner of GUI applications

### ISSUE THREAD

**Issue by irieas** [budgie-desktop/budgie-desktop#1347]
Operating system: Solus 3.99
Budgie version: 10.4

A texture is constantly displayed in the left corner of the title bar of some GUI apps (screenshot). 
From the ones I checked, only Gnome-Terminal and apps of the Libre Office Suite have this graphic bug.

![budgie-window-bug](https://user-images.githubusercontent.com/37031384/36941402-b9b0f32a-1f5a-11e8-9650-171abd44e0f5.png)

**Comment by JoshStrobl** [comment]
My guess is youo have gnome-icon-theme installed, probably tried out MATE? :smile: It borks the icons.

**Comment by irieas** [comment]
I don't have gnome-icon-theme installed and never tried out MATE but I do have gnome-themes-standard and gnome-themes-standard-32bit installed. I first tried to reinstall these packages and now I removed them but I still see this bug.

I forgot to mention that this happened afterdeleting the Windows partition on my SSD and appending the free space to /home. So this moving around and resizing of partitions might be responsible here. 
Guess it's not a big deal, just wondered whether I'm the only one with this issue.

**Comment by JoshStrobl** [comment]
@irieas Should you  try running `sudo usysconf run -f` and restarting?

**Comment by irieas** [comment]
```
$ sudo usysconf run -f
Passwort: 
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
 [✓] Updating clr-boot-manager                                          success
 [✓] Registering QoL migration on next boot                             success
 [✓] Running depmod on kernel 4.15.7-60.current                         success
 [✓] Updating hwdb                                                      success
 [✓] Updating graphical driver configuration                            success
 [✓] Updating system users                                              success
 [✓] Updating systemd tmpfiles                                          success
 [✓] Reloading systemd configuration                                    success
 [✓] Compiling AppArmor profiles                                        success
 [✓] Compiling glib-schemas                                             success
 [✓] Rebuilding font cache                                              success
 [✓] Updating mimetype database                                         success
 [✓] Updating icon theme cache: HighContrast                            success
 [✓] Updating icon theme cache: Papirus                                 success
 [✓] Updating icon theme cache: default                                 success
 [✓] Updating icon theme cache: breeze-cursor                           success
 [✓] Updating desktop database                                          success
 [✓] Rebuilding dconf database                                          success
 [✓] Updating GTK2 input module cache                                   success
 [✓] Updating GTK3 input module cache                                   success
 [✓] Updating manpages database                                         success
 [✓] Updating SSL certificates                                          success
```

This didn't solve the issue, unfortunately.

**Comment by irieas** [comment]
One of the recent updates fixed the issue. Now the icon in the top left corner is the same sized as in every other GTK application.
Thanks.
