### ISSUE TITLE
How to remap Budgie shortcuts?

### ISSUE THREAD

**Issue by diadochos** [budgie-desktop/budgie-desktop#1355]
**Operating System**: Ubuntu 16.04.4 LTS (Xenial Xerus)

**Budgie version**: budgie-desktop 10.4

**The issue encountered**
I personally map `<Super>+N` to opening new windows.
However, [Budgie shortcuts](https://solus-project.com/articles/budgie/shortcuts/en/) for opening Raven (in the notifications section) is preventing me from using the mapping.

I have looked into dconf-editor under `org.gnome.desktop.wm.keybindings` but I was unable to locate a related entry.

** Question **
- Where is the configuration for [Budgie shortcuts](https://solus-project.com/articles/budgie/shortcuts/en/) stored?
- How could I remap these?

**Comment by fossfreedom** [comment]
I guessing here since I haven't tried - but the raven keyboard bindings are here (via dconf-editor)

/com/solus-project/budgie-wm

Suggest change the `<Super>N` to something else, logout, login and then hopefully you can then bind your custom keybinding to `<Super>N`

**Comment by diadochos** [comment]
Thanks a lot @fossfreedom ! I was able to remap it.
