### ISSUE TITLE
budgie-desktop-settings not starting up

### ISSUE THREAD

**Issue by cooler9711** [budgie-desktop/budgie-desktop#1360]
**Operating System**: Arch Linux, fully updated
**Budgie version**: budgie-desktop v10.4-8-gff09a510

**The issue encountered**
Trying to open budgie-desktop-settings restarts budgie, then attempting to open it again fully crashes budgie.

**Steps to reproduce the issue**
Try to open budgie-desktop settings.

**Comment by cooler9711** [comment]
The most recent update for Budgie for arch fixed this problem. Closing

**Comment by Icemole** [comment]
This issue has returned. I'm using Budgie Desktop 10.5 from the AUR package `budgie-desktop-git`. The core of the issue remains the same: executing `budgie-desktop-settings` from the terminal once does nothing (it restarts Budgie, as you said on your issue description). The second time `budgie-desktop-settings` is executed, the session is closed and I am thrown to the login page.

**Comment by shymmq** [comment]
This is still happening for me in Budgie Desktop 10.5.2. Any way to fix this?
