### ISSUE TITLE
An obscure error from src/theme/meson.build, line 31

### ISSUE THREAD

**Issue by akerka2** [budgie-desktop/budgie-desktop#1363]
**Operating System**: Mint 18.3
**Budgie version**: 10.4

Hello. I got such a message, when tried to build Budgie:

> Meson encountered an error in file src/theme/meson.build, line 31, column 0:
> The "dependencies" argument of gnome.compile_resources() can not
> be used with the current version of glib-compile-resources due to
> <https://bugzilla.gnome.org/show_bug.cgi?id=774368>

In the line 31 of meson.build is:

> theme_resources = gnome.compile_resources(
>    &nbsp;&nbsp; 'budgie-theme-resources',
>   &nbsp;&nbsp;  'budgie-theme.gresource.xml',
>   &nbsp;&nbsp;  source_dir: meson.current_build_dir(),
>   &nbsp;&nbsp;  dependencies: theme_deps,
>   &nbsp;&nbsp; c_name: 'budgie_desktop_theme',
> )

To reproduce this error I just need to open terminal, change directory to budie-desktop-master  and to enter "meson builddir"

Could you please explain me way to fix it and to continue building. Thank you!

**Comment by fossfreedom** [comment]
You need to ensure the dependencies are met for ubuntu 16.04

Meson needs to be v0.40 or later.

**Comment by akerka2** [comment]
fossfreedom, the version is 0.40.1-1~ubuntu16.04.1
It's not simple to study out, which dependencies to install. If I undestand right, theme_deps is vector. I'm not familiar with meson to debug content of this variable. Then have no idea, what it wants...

**Comment by fossfreedom** [comment]
Ah... Ok. Yeah you have to patch things to get it to work with gtk 3.18.

Have a look here for the patches I have to carry for budgie remix 16.04

https://github.com/UbuntuBudgie/budgie-desktop/blob/debian10.4-xenial/debian/patches/318

On Fri, 30 Mar 2018, 16:38 akerka2, <notifications@github.com<mailto:notifications@github.com>> wrote:

fossfreedom, the version is 0.40.1-1~ubuntu16.04.1
It's not simple to study out, which dependencies to install. If I undestand right, theme_deps is vector. I'm not familiar with meson to debug content of this variable. Then have no idea, what it wants...

**Comment by fossfreedom** [comment]
ok - I presume this has now been dealt with.  Closing.
