### ISSUE TITLE
network-manager-applet no pop up password input

### ISSUE THREAD

**Issue by LoveChocoCat** [budgie-desktop/budgie-desktop#1369]
**Operating System** 
Anarchy Linux (Arch)
**Budgie Version**
budgie-desktop v10.4-34-gd6f3519f
**The Issue encountered**
When I click at the network manager applet and try to connect to a wifi there is no pop up to ask for the password
**Steps to reproduce the issue**
Explained

**Comment by fossfreedom** [comment]
Given the distro you are using I would first look at  if your network manager has been recently uplifted. 

Maybe the version you are using has had the legacy system tray capability stripped from it.

**Comment by LoveChocoCat** [comment]
Then how to re enable this functionality. Is it just reinstalling my linux
with non modified version of budgie? my linux is not really important
though but it will be more convenient to just add this functionality in
later version of budgie. and i want to ask is there any problem with budgie
in arch just like mine?

**Comment by LoveChocoCat** [comment]
sorry for my bad english

**Comment by fossfreedom** [comment]
I know Ikey was working on a native budgie network manager capability but that seems to have been parked.

Thus you are really left to look at your distro's version of network-manager and working out what you need to-do to get it working.  I don't know anything about arch and what you need to-do to rollback/investigate stuff.

Hopefully an Arch user can pipe up here and help out. 

This isnt really a budgie matter though.

**Comment by LoveChocoCat** [comment]
So in your experience there is no bug like mine in arch or there is a lot
of them? i wanna there are people who encountered bug like i did
my distro is basically a vanilla arch just with name change to anarchy. i
wanna know how about solus is there any problem like mine

**Comment by LoveChocoCat** [comment]
Should I pull request for native network-manager-applet?
