### ISSUE TITLE
No desktop icons

### ISSUE THREAD

**Issue by ominds** [budgie-desktop/budgie-desktop#1370]
**Operating System**: Antergos
**Budgie version**: v10.4-34-gd6f3519f

**The issue encountered**

I can't see any desktop icons, no right click, nothing. Raven doesn't have an option to show desktop icons, gnome tweaks doesn't have an option. In dconf editor, show desktop icons is already enabled (but has no effect). Nautils is installed, gnome shell is installed... donno what else to try.

**Comment by fossfreedom** [comment]
Please check the version of nautilus you are running

If you are running v3.28 then GNOME have removed desktop icons capability.

**Comment by ominds** [comment]
Right. It seems to be nautilus issue (3.28.0.1)

Any workaround at the moment?

**Comment by fossfreedom** [comment]
Downgrade to nautilus 3.26

 Or try the suggested solutions here

https://gitlab.gnome.org/GNOME/nautilus/issues/158

**Comment by ominds** [comment]
Thanks! For anyone facing this, install nemo-desktop from AUR. The steps for configuring nemo-desktop in the link by @fossfreedom doesn't work on Antegroes (and probably all of arch in general)

**Comment by fossfreedom** [comment]
If the steps for configuring does not work please can you help others by describing what you did to get stuff working?
