### ISSUE TITLE
No "Desktop" preferences on Budgie Desktop Settings

### ISSUE THREAD

**Issue by tulliana** [budgie-desktop/budgie-desktop#1376]
This window had a desktop preferences, I can not see it now

Distribution: Archman (Arch based)
Budgie Desktop: budgie-desktop  10.4+34+gd6f3519f-1
![ekran goruntusu_2018-04-14_06-53-50](https://user-images.githubusercontent.com/2324162/38764116-74938a88-3fb1-11e8-8dae-49124b7b78db.png)

**Comment by fossfreedom** [comment]
That is most probably because Archman has upgraded to Nautilus 3.28 which has removed all of the desktop handling stuff.

**Comment by tulliana** [comment]
Yes right, Archman using nautilus version 3.28

Are you going to work for nautilus 3.28?

**Comment by fossfreedom** [comment]
GNOME Devs have removed all of the desktop handling stuff.

For the moment, distros will themselves how best to move forward - e.g. keep with nautilus 3.28, somehow patch nautilus 3.28 to put back desktop handling, use nemo for desktop handling, drop desktop handling etc.

**Comment by ikeydoherty** [comment]
You can keep with 3.26 or go to 3.28. If you go with 3.28 you'll need to compile Budgie from git with `-Dwith-desktop-icons=none` to forcefully disable this behaviour. Also this behaviour wasn't removed by us in git until very recently with the switch, so its nice to know we have random downstream patches never making it upstream to us.

**Comment by ikeydoherty** [comment]
(Note in future we'll flesh out `budgie-desktop-icons` to provide a replacement to Nautilus desktop icons)
