### ISSUE TITLE
workspace switcher opacity

### ISSUE THREAD

**Issue by Geert1959** [budgie-desktop/budgie-desktop#1377]
Unstable
After the update of friday 13th the workspace switcher had no opacity anymore and has turned into black
https://i.imgur.com/JpLvhGz.png

**Comment by fossfreedom** [comment]
What distro is called unstable? Debian?

**Comment by tista500** [comment]
I've now reverted that design change... It's not the Budgie issue anyway.

**Comment by fossfreedom** [comment]
thanks @tista500
