### ISSUE TITLE
Workspace wsvisualizer tweak

### ISSUE THREAD

**Issue by JustPerfection** [budgie-desktop/budgie-desktop#1392]
I want to tweak workspace OSD. Please tell me where is the css file for that.

**Operating System**: Ubuntu Budgie 18.04
**Budgie version**: i.e. Budgie 10.4

**Comment by fossfreedom** [comment]
This is the wrong issue tracker. Please raise issues about Ubuntu budgie first on the support channel https://discourse.ubuntubudgie.org and we will advise you where the appropriate place to raise your issue. Thanks.
