### ISSUE TITLE
Always hide panel

### ISSUE THREAD

**Issue by JustPerfection** [budgie-desktop/budgie-desktop#1393]
How can I have always hide panel?

**Operating System**: e.g. Ubuntu 18.04
**Budgie version**: i.e. Budgie 10.4

**Comment by fossfreedom** [comment]
Why would you want to always hide the panel? You do have the autohide option for a panel in budgie settings.

**Comment by JustPerfection** [comment]
I know about auto hide, but It doesn't work just like what I want. I want a panel that only shows when I do mouse over on that area.

**Comment by fossfreedom** [comment]
Duplicate of https://github.com/budgie-desktop/budgie-desktop/issues/1257
