### ISSUE TITLE
Files misbehaves Icon Task List with Window grouping

### ISSUE THREAD

**Issue by metrovania** [budgie-desktop/budgie-desktop#1396]
**Solus 3.9995**
**budgie-desktop v10.4-55-g995e85e5**

**The issue encountered**

 When using the Icon Task List in the panel with "Window grouping" enabled, Files doesn't behave as expected. If Files isn't pinned to the Icon Task List, it doesn't appear there when launched, and if it is pinned, it blinks for about 10 seconds, but never shows it as active.

**Steps to reproduce the issue**

It was just like this after rebooting into version 3.9995 for the first time. 

**Steps taken to mitigate the issue**

The problem seems to go away if you delete the Icon Task List in Budgie Settings, and create a new one.

[edit] actually, this workaround only worked because I had Files open when I deleted the Icon Task List. When I closed Files, the problem re-emerged. The only workaround I've found is to disable "Desktop Icons" in "Budgie Desktop Settings."

**Comment by hfel** [comment]
Have the same issue.

**Comment by ma-renaud** [comment]
I also have this issue and, like for hfel, the workaround is not working.

**Comment by metrovania** [comment]
For the workaround to work, you need to disable Desktop Icons in the "Desktop" tab in "Budgie Desktop Settings". Hadn't realised this when I wrote it.

**Comment by clauded** [comment]
I confirm that @metrovania workaround fixes the issue.

**Comment by bsucker98** [comment]
same here,
It seems, if u want Window grouping, u have to give up on Desktop Icons & if u want Desktop Icons u have to give up on Window grouping, 
I think when they come up with budgie-desktop-icons as nautilus 3.28 won't have it, it would solve all this...

**Comment by bsucker98** [comment]
let ur work make the noise #solusdevteam
latest update fixed the issue, budgie 3.9996...
