### ISSUE TITLE
System tray icons flickering on high DPI display

### ISSUE THREAD

**Issue by alecbcs** [budgie-desktop/budgie-desktop#1397]
**Operating System**: Solus 3.9995
**Budgie version**: Budgie 10.4.55

**The issue encountered**
After updating to the latest version of Solus my System icons began [flickering on my high DPI display](https://www.dropbox.com/s/481kla76ui8u2su/simplescreenrecorder-2018-04-30_09.45.39.mkv?dl=0).

**Steps to reproduce the issue**

Not completely sure other than updating to Solus 3.9995 and having a high DPI display. I've found that toggling the location of the bar will temporarily fix the flickering.

**Comment by 7-King** [comment]
I have the same issue. Intel® HD Graphics 515 (Skylake GT2)

**Comment by marcbone** [comment]
Same issue, also on Intel Graphics, also HiDPI Display.  I found out you can temporarily fix it with choosing a different screen resolution and switching back to the normal resolution again.

**Comment by meborc** [comment]
Confirmed on my Dell XPS13 HiDPI screen.

**Comment by Rabrg** [comment]
Happens on my Dell XPS 15 4k display

**Comment by ikeydoherty** [comment]
Fixed today (also could only reproduce on HiDPI) 

https://github.com/budgie-desktop/budgie-desktop/commit/f3ce3a619b225447d733982af927b3968f9a28f0

Will be in tomorrows sync in Solus
