### ISSUE TITLE
Dock-Icons wrong size after reboot

### ISSUE THREAD

**Issue by JonnyCodewalker** [budgie-desktop/budgie-desktop#1402]
**Solus 3.9995**
**10.4.--55-g995e85e5**
**The issue encountered**
After update the icons defaulted back to the initial size. Upcon reducing the dock by one pixel and then increasing it again they got the according size. This happens after every reboot.
 ...

**Steps to reproduce the issue**
- reduce dock size to 30 pixel
- set to dock mode
- reboot

**Comment by ikeydoherty** [comment]
Fixed in git, having multiple icon tasklists caused them to fight

**Comment by JonnyCodewalker** [comment]
After the newest updates the issue still persists.
