### ISSUE TITLE
Windowed Chrome Apps Missing icons in Icon Task List

### ISSUE THREAD

**Issue by joshua-r-andress** [budgie-desktop/budgie-desktop#1403]
Operating System: Solus 3.9995

Budgie version: budgie-desktop v10.4-55-g995e85e5

**The issue encountered**

After updating Solus today the Google Chrome Apps that I had pinned to the icon task list applet lost their associated icons. They are still present and accessible but the icons are missing. Window Grouping is off.
 ...

**Steps to reproduce the issue**

Open Google Chrome and navigate to chrome://apps/ and right click any app. Click open as Window. Right click again and click create shortcuts. Make sure desktop is toggled off and Application menu is toggled on and click create. Launch the app you just made those changes to. A active space appears in the icon task list complete with the blue active dot but the icon is missing. I updated to Google Chrome 66 last week and the issue I'm experiencing did not present itself until today after updating Solus. I launched Solus in a VM and ran today's update but I omitted the Budgie Desktop from updating. The issue I'm reporting did not occur in the VM. 

![screenshot from 2018-04-30 19-49-23](https://user-images.githubusercontent.com/29024477/39455658-abe5a06a-4caf-11e8-9b66-80e6078779e5.png)

 ...

**Comment by bsucker98** [comment]
same here,
**Window grouping enabled | Desktp icons disabled**
it seems firstly opened chrome app(including google chrome) is acting as other chrome apps, I know you may didn't get it, 
i.e say I opened a chrome app, then opened another(be it google chrome, no exception), it(second one) would open up as the firstly opened chrome app and grouped with that(first one's) window.
**Note:** if the secondly opened app is pinned, it would keep blinking & u have to close related apps & then hve to re-open it to stop blinking

**Window grouping enabled | Desktp icons enabled**
same as above

**Window grouping disabled | Desktp icons enabled**
works perfect

**Window grouping disabled | Desktp icons disabled**
works perfect

jst thought to mention with Desktop icons, cause when it comes to this https://github.com/budgie-desktop/budgie-desktop/issues/1396 it makes different..

**Comment by joshua-r-andress** [comment]
I have Windows Grouping disabled for the icon task list applet and the issue I am experiencing is still present. The icons for individual Chrome Apps are either missing or disproportionate. I've attached a screen shot bellow. In the Screen shot I'm using the task list applet. All of the individual Chrome Apps have their own windowed instance and each one has it's proper icon. The second attached screen shit is when I add the Icon Task List applet and disabled Windows Grouping. You can see the icon for Plex is disproportionate in size to the other applications while the icon for Google+ and Google Play Music is missing. I can confirm the issue you described as well. If window grouping is enabled it is almost as if it can't distinguish between say Google+ and Google Photos. If you open Google+ first and Google Photos second it gives Google Photos the Google+ icon.

![screenshot from 2018-05-05 09-26-28](https://user-images.githubusercontent.com/29024477/39663719-782b9974-5046-11e8-8774-d53881282146.png)

![screenshot from 2018-05-05 09-28-08](https://user-images.githubusercontent.com/29024477/39663738-ae3944f8-5046-11e8-85ab-3e14e4d1b266.png)

**Comment by bsucker98** [comment]
> @joshua-r-andress The icons for individual Chrome Apps are either missing or disproportionate. 

same here mate, chrome app icons are disproportionate for some apps..and well said 

> if window grouping is enabled it is almost as if it can't distinguish between say Google+ and Google Photos

that's really clear :)

**Comment by joshua-r-andress** [comment]
Today's update to the budgie desktop resolved the issue I was having. Thanks guys.

![screenshot from 2018-05-05 13-29-38](https://user-images.githubusercontent.com/29024477/39665868-b590812c-5068-11e8-9c28-eaa92dd4ab3c.png)

**Comment by bsucker98** [comment]
fixed the icons issue, unfortunately pretending as the same app still exist :\
