### ISSUE TITLE
Dock Tray Icons wrong size after reboot

### ISSUE THREAD

**Issue by JonnyCodewalker** [budgie-desktop/budgie-desktop#1408]
Kernel: 4.15.17-65.current x86_64 
Desktop: Budgie 10.4-62-g269740af  
Distro: Solus 3.9995

Theme: Adapta-Noko-Eta
Dark theme enabled, Build-in theme disabled.

**The issue encountered**
After rebooting the Icons in the Dock are in the wrong size. It seems like they apply default size instead of beeing scaled down if the dock-size got reduced.

https://imgur.com/a/6SMd2l8

**Steps to reproduce the issue**
 - Have Signal or Thunderbird run in Autostart
 - Set Dock to Position: Bottom, Size: 30, hide: Intelligent, Transparancy: Always
 - Enable Dock mode
 - Reboot

**Comment by ikeydoherty** [comment]
This *should* be fixed now with latest updates right?

**Comment by JonnyCodewalker** [comment]
Appears to be fixed. Thank you very much :)
