### ISSUE TITLE
Wifi icon corrupt

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1410]
**Operating System**:  Solus 3.9995
**Budgie version**: 10.4

**The issue encountered**

I just happened to notice that my wifi icon on the taskbar, and no other icon, is now corrupt. It's splintered into like 10 pieces, all within the original icon's square area, although I can still see the resemblance to the original icon. Restarting doesn't fix it. Looks like a rendering issue.

**Steps to reproduce the issue**

Just boot up and look at the taskbar.

**Comment by ikeydoherty** [comment]
Fixed in https://github.com/budgie-desktop/budgie-desktop/commit/f3ce3a619b225447d733982af927b3968f9a28f0
