### ISSUE TITLE
Touchpad right+middle click are registering left clicks

### ISSUE THREAD

**Issue by swprojects** [budgie-desktop/budgie-desktop#1411]
Operating System: Solus 3.9995
Budgie version: 10.4

**The issue encountered**

After update today, I tried to right click and it behaves like left click.

**Steps to reproduce the issue**

Test touchpad click buttons.

**Comment by ikeydoherty** [comment]
Not a Budgie issue, actually a GNOME schema issue.

Resolved in https://dev.solus-project.com/R1070:b7446a775adc906bfb0d52d89e8592475e1052a3 - will arrive in tomorrows sync
