### ISSUE TITLE
Things are pushed too far, rendering them inaccessible.

### ISSUE THREAD

**Issue by rtyb96** [budgie-desktop/budgie-desktop#1415]
**Operating System:** Solus 3.9995
**Budgie version:** Budgie 10.4-62-g269740af

**The issue encountered**
Items on the panel get pushed too far to the right (or any side) when having too much open.

**Steps to reproduce the issue**
Just open a bunchload of windows of anything, and it'll happen.
![bug1](https://user-images.githubusercontent.com/38988846/39644936-df519ea4-4f93-11e8-8152-899bc2c0d8ab.png)

**Comment by ikeydoherty** [comment]
OK I know this is a duplicate. of about 15 bugs. :)

**Comment by rtyb96** [comment]
Thanks and sorry Ikey, I did try to look for the same bug, but I guess my keywords didn't match.
