### ISSUE TITLE
Software Center doesn't count files correctly

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1429]
**Operating System**: Solus 3.9995
**Budgie version**: i.e. Budgie 10.4
**The issue encountered**

When Software Center is downloading files in some cases, it starts displaying nonsense like "27 of 16" files downloaded. This might be more than just an aesthetic problem if it means that some data structure has underbudgeted space.

**Steps to reproduce the issue**

This doesn't occur with all software packages, and maybe not even with the same one each time, so I guess you just have to install random ones until it occurs. It seems to happen like 10% of the time.

**Comment by fossfreedom** [comment]
The software centre isn't a budgie desktop GUI issue. Solus issue tracker would be better!
