### ISSUE TITLE
Expose applet does not work with Alt+Shift + Tab

### ISSUE THREAD

**Issue by asfernandes** [budgie-desktop/budgie-desktop#1431]
**Operating System**: Ubuntu Budgie Bionic 18.04
**Budgie version**: 10.4

I have installed the applet "Expose - show overview of windows" and it works great when I press Alt+Tab.

But when I'm visualizing it and press Alt+Shift+Tab to return back for a window, then the other (non Expose) switcher appears inside Expose.

**Comment by Jacob-Vlijm** [comment]
Thanks, currently, this is the intended behaviour see: https://github.com/UbuntuBudgie/budgie-extras/issues/72, of which this is a dupe.

**Comment by fossfreedom** [comment]
@asfernandes closed since this is a downstream issue.
