### ISSUE TITLE
Budgie-desktop-setting

### ISSUE THREAD

**Issue by tellsela** [budgie-desktop/budgie-desktop#1432]
I am new in budgie

I want to make some change  /usr/bin/budgie-desktop-setting , But i can not edit the file throw nano Or vim.
could it be another way to do?

thanks

**Comment by fxdave** [comment]
It's a binary, you can't modify it (you can with a disassembler, but you really don't want). If you want to make some changes you should open it and set your changes via GUI. If you are not satisfied with the settings, then I have two options for you: 
1) make your own GTK theme, or download another.
2) fork the budgie-desktop, change for your needs, and build it.

**Comment by fossfreedom** [comment]
Closing this issue since it has been resolved - thanks @fxdave for the help here.
