### ISSUE TITLE
Main panel doesnt contain applet with running apps (windows).

### ISSUE THREAD

**Issue by wennaspeedy** [budgie-desktop/budgie-desktop#1441]
Ubuntu Budgie 18.04 LTS

I cant find applet which could appear running apps (windows) like in xfce/cinnamon/...etc in main panel. It is possible? I dont want use plank...

**Comment by fossfreedom** [comment]
Add the icon-tasklist-applet to your panel via budgie-settings

**Comment by wennaspeedy** [comment]
Sorry, but it isn't the right applet. This one shows me favorite apps only.
![screenshot from 2018-05-17 09-33-39](https://user-images.githubusercontent.com/10447994/40162838-6b3f5c50-59b5-11e8-9236-6ba46b916bb1.png)

**Comment by wennaspeedy** [comment]
OK, thank you, I know this applet, but shows me favorite apps only. But reboot solved this.
