### ISSUE TITLE
application name incorrect for caffeine panel applet notification

### ISSUE THREAD

**Issue by lallenfrancisl** [budgie-desktop/budgie-desktop#1695]
**Operating System**: e.g. Solus 3.9999
**Budgie version**: budgie-desktop 10.5 (git-8a710056664f860224d4260b566d248948866a90)

**The issue encountered**
Notification send by caffeine indicator has application name as notify-send and not caffeine
![screenshot from 2019-01-02 20 54 31](https://user-images.githubusercontent.com/21018348/50598585-2e584000-0ed1-11e9-9c4e-22cd68cb6b05.png)

**Steps to reproduce the issue**
turn on caffeine indicator budgie panel applets

**Comment by yursan9** [comment]
Need to add a line in `src/applets/caffeine/CaffeineWindow.vala`. By appending `--app-name="Budgie Desktop"` or `--app-name="Caffeine"` to `cmd` before being invoked.

**Comment by JoshStrobl** [comment]
@yursan9 I'm completely rewriting the applet, schema bits, etc. so should be addressed when I push that to master in next couple days.

**Comment by yursan9** [comment]
@JoshStrobl cheers! I'm kinda feel responsible for my own applet, so I'm kinda upset when I couldn't help solving the issue.
