### ISSUE TITLE
[Problem] Unstable work at Solus (may 2021)

### ISSUE THREAD

**Issue by wizerer** [budgie-desktop/budgie-desktop#2137]
## Description
Good day!
After an update a few weeks ago, the stability of the system has severely deteriorated. This includes the following problems:

- (The most frequent) When opening several programs or windows of the same program, spontaneous session termination may occur. Another option (more likely): restarting the desktop environment. The result of this item is a screen for entering the user name and password.

_Repeatability:_ random. When opening the same applications, the bug may or may not happen at all.
 
- If you quickly change the scale of the text on a page (e.g. in a pdf-document), the application will terminate.

_Repeatability:_ regular.
 
- The system may spontaneously crash when performing any operation. Most common when trying to check for updates in the Software Center. The combination of keys `Ctrl + Alt + F1` does not lead to any result.

_Repeatability:_ random.

In the current situation it is almost impossible to work in the system. It seems necessary for updates to be more stable, or at least to have version rollbacks when significant bugs appear.

## Budgie version
10.5.3

## Operating system
Linux solus 5.11.16-178.current

**Comment by JoshStrobl** [comment]
These issues aren't related to Budgie Desktop, but if you are confident that there is a specific segfault in Budgie, you are welcome to provide a backtrace. https://github.com/solus-project/budgie-desktop/wiki/Providing-Backtraces

**Comment by wizerer** [comment]
It seems to me that the problem is complex, and it should be considered together distribution + desktop environment. I'm not sure if the problem is not with the Budgie DE, which is why I published a post about it. ¯\_(ツ)_/¯
