### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ghost** [budgie-desktop/budgie-desktop#2174]
Unable to install some application like Cisco Packet Tracer.

**Comment by guillotjulien** [comment]
Software installation isn't related to Budgie. If you are using Solus, Packet Tracer is not in the package repository due to its licence (https://dev.getsol.us/T1767) but you can still install it manually.

**Comment by JawadNamal** [comment]
Sir, what should be the procedure if i want to take part in development and
improvement of Solus.
