### ISSUE TITLE
Re-add the ability to change budgie menu icon in settings.

### ISSUE THREAD

**Issue by Justinzobel** [budgie-desktop/budgie-desktop#250]
We used to be able to change the menu icon on old Budgie, can't now.
##

**Comment by geckolinux** [comment]
For some reason it is using an Ubuntu icon on the budgie-desktop that I compiled for openSUSE. :)

**Comment by geckolinux** [comment]
Meanwhile is there any way for me to manually change the icon? What's the default Budgie menu icon name?

**Comment by ikeydoherty** [comment]
It's defined by default in the gschema for Budgie Menu Applet

```xml
    <key type="s" name="menu-icon">
      <default>'start-here-symbolic'</default>
      <summary>Menu button icon</summary>
      <description>The icon to display on the main menu button</description>
    </key>
```

The appropriate way to provide a vendor override is to provide the gschema override file in your distribution:

```ini
[com.solus-project.budgie-menu]
menu-icon = your-sexy-menu-icon
```

This should be named `/usr/share/glib-2.0/schemas/com.solus-project.budgie-menu.gschema.override`

Alternatively you can patch `panel/applets/budgie-menu/com.solus-project.budgie-menu.gschema.xml`

**Comment by ikeydoherty** [comment]
It's now `view-grid-symbolic` per our old defaults

**Comment by geckolinux** [comment]
``````````
[com.solus-project.budgie-menu]
menu-icon = 'your-sexy-menu-icon'
``````````
Nice, thanks for the explanation, I never would have figured that out. The only change is that `'your-sexy-menu-icon'` needs to be in quotes.

**Comment by erikdubois** [comment]
Just changed the icon... there is an other way.
In sardi icon theme there is a collection of start-here-symbolic alternatives
You can choose the solus icon as start up. Rename any icon you like to start-here-symbolic.svg
![solus](https://cloud.githubusercontent.com/assets/10594806/19896552/0c144b16-a055-11e6-9507-da5e62b3e81e.png)

**Comment by Vistaus** [comment]
I agree that this functionality should be brought back in the GUI.

**Comment by ikeydoherty** [comment]
+1/Agree/Bump comments bring nothing new to the conversation. I know it needs to come back. Please stop bumping the thread

**Comment by ikeydoherty** [comment]
Well this is fixed even if the commits don't want to show up ..
