### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by X0rg** [budgie-desktop/budgie-desktop#268]
On the old README.md, there was this line:
`Wayland support, complete it, and validate on Intel NUC (v9)`

With Budgie Desktop 10.1, I'm unable to run Budgie on Wayland properly:
- some files for Wayland session are missing
- budgie-panel seems totally broken (see attached screenshot)
  ![wayland-screenshot](https://cloud.githubusercontent.com/assets/2873785/12050164/2cd94500-aef1-11e5-80ad-6054976b68cd.png)

I can start budgie-wm from a VT with command `budgie-wm --wayland --display-server`.
##

**Comment by ikeydoherty** [comment]
The files are missing because it's unsupported. Budgie isn't broken, the completely unnecessary sweeping changes in Wayland broke Budgie on Wayland.

Things we can't do:

 [ ] Set X11 window placement
 [ ] Reserve panel struts
 [ ] Share knowledge on active display server window list

Just off the top of my head ^ It'll be a while yet before we support it (it's milestone for Solus 2)

**Comment by jwl-crosse** [comment]
bychance, would you like help with wayland support? I am no wayland jedi, but i can probably get some  code that will help it start. maybe even support Windows in the future? (because Vala is opensource?)

**Comment by X0rg** [comment]
Some people takes code from Weston, the reference compositor for Wayland, to write a Wayland compositor.
Maybe [Libweston](http://cgit.freedesktop.org/wayland/weston/tree/README) can helps to do it. :)

**Comment by ikeydoherty** [comment]
@X0rg ignore the above comment, the user has been banned from GitHub with good reason

**Comment by rawsh** [comment]
@ikeydoherty Solus 2 is out now, any planned work on Wayland?

**Comment by ikeydoherty** [comment]
No it's not. Solus uses a rolling release model, Solus 2 never happened (and won't.). 

See: https://budgie-desktop.org/2017/01/25/kicking-off-budgie-11/

Closing this as a non-bug as its a roadmap item for Budgie 11 (Which is Q2)
