### ISSUE TITLE
Clock Applet has no accessible settings

### ISSUE THREAD

**Issue by ikeydoherty** [budgie-desktop/budgie-desktop#285]
Even though we integrated into the core GNOME settings for the display of the clock, we expose no UI to alter these. Make an applet configuration UI for the Clock Applet
##

**Comment by JoshStrobl** [comment]
Options:

1. Show date.
2. Show seconds.
3. Enable 12-hour time (AM / PM). Not sure if this is pulled from locale or some other factor, but would be nice if it could be enabled separately.

This eliminates the need to use the Top Bar section of Tweak Tools (specifically item 1 and 2).

Note: Enabling Show Seconds can result in the width of the clock applet changing sizes and thus moving slightly. I'd recommend setting a minimum width to eliminate the jerkiness.

**Comment by mrohnstock** [comment]
A small addition:

* 1. Show date.
  * a. Add ability to modifiy display-format of the date

For me it's useless to display the current year all the time and it's using to mutch space ;). Day + Month is all I really need (maybe the day of week would be great, too).

**Comment by ikeydoherty** [comment]
Clock now has settings
