### ISSUE TITLE
Clicking on panel settings in raven makes the sidebar smaller

### ISSUE THREAD

**Issue by hackis** [budgie-desktop/budgie-desktop#300]
When I login to budgie desktop and open the raven panel for the first time, it has a specific size (not sure how many px) but after going to settings and clicking on the panel tab, the raven panel shrinks in horizontal size several pixels.
##

**Comment by david1603** [comment]
I can't reproduce this on Budgie 10.2.9 - is this still affecting you?

**Comment by JoshStrobl** [comment]
Closing issue. If this still occurs on latest Solus w/ Budgie 10.3/10.3.1, feel free to re-open.
