### ISSUE TITLE
Some Applets Request.

### ISSUE THREAD

**Issue by javashin** [budgie-desktop/budgie-desktop#310]
would be nice to have sensors applet , netspeed and cpufreq changer
thanks so much for the nice work and well done of this new and fresh desktop.
##

**Comment by heberjeur** [comment]
also,we need xampp applet like cinnamon

**Comment by ikeydoherty** [comment]
"need" is a bit of a strong word. if you mean [this](http://cinnamon-spices.linuxmint.com/applets/view/146) then it's only really suitable
as an out-of-tree module

**Comment by JoshStrobl** [comment]
We believe this functionality should be implemented "out of tree" (external to Budgie core) by the community.
