### ISSUE TITLE
Re-introduce autohide of panel

### ISSUE THREAD

**Issue by Justinzobel** [budgie-desktop/budgie-desktop#315]
As per previous budgie, please re-introduce panel autohide.

Requested by https://solus-project.com/forums/viewtopic.php?f=14&t=986
##

**Comment by angelojulioth** [comment]
Yes please, I can't stand the way the panel works panel :( ...is there any way to disable it right now?

**Comment by quesada** [comment]
Me too.

**Comment by ikeydoherty** [comment]
Please do not "me too" issues, you just push them back.

**Comment by fossfreedom** [comment]
this was fixed in budgie v10.4
