### ISSUE TITLE
Budgie Menu closes when clicking on category headers and borders

### ISSUE THREAD

**Issue by ghost** [budgie-desktop/budgie-desktop#326]
What the title say, better explained by [this video](https://youtu.be/C1I_6ODXF1k).
##

**Comment by starquake** [comment]
I'm running 10.2.2 on Arch and I'm not having the problem. Are you running 10.2.2?

**Comment by feskyde** [comment]
10.2.2 and [`0596e73`](https://github.com/solus-project/budgie-desktop/commit/0596e73177f74911eb93ccd6eca952c79b88f25f)

**Comment by johnfraney** [comment]
I'm able to reproduce this bug in Arch running 10.2.3-3 from AUR. The menu closes when clicking on category headers that aren't visible when the menu is first opened.

**Comment by JoshStrobl** [comment]
Issue has since been resolved

**Comment by JoshStrobl** [comment]
Okay apparently when scrolling it does indeed have that issue.

**Comment by ikeydoherty** [comment]
Fixed in git by replacing `GtkPopover` with our new `BudgiePopover` type. This will feature in the next release
