### ISSUE TITLE
Allow wine/playonlinux apps to be pinned and run from the panel

### ISSUE THREAD

**Issue by Anachron** [budgie-desktop/budgie-desktop#353]
When I pin the app to the panel it looks fine: 
![2016-03-02-235725_1920x39_scrot](https://cloud.githubusercontent.com/assets/589800/13478705/969383e4-e0d2-11e5-9963-aa80a8304572.png)

But as soon as I close the app it will change the symbol and I cannot launch the app anymore:
![2016-03-02-235738_1920x39_scrot](https://cloud.githubusercontent.com/assets/589800/13478719/a58c3800-e0d2-11e5-8557-f50ade5b0cbd.png)

**Comment by ikeydoherty** [comment]
What application can I test with using just Wine? Otherwise I can't fix it :D

**Comment by JoshStrobl** [comment]
Closing due to lack of response from original poster. Almost a year is plenty of time to formulate a reply :smile:
