### ISSUE TITLE
applets should be split into their own folders

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#384]
Hi,

  I've been looking at writing some plugins for budgie-desktop.

One concern I have is that all the plugins under /usr/lib/budgie-desktop/plugins and all located  within that one folder.

In rhythmbox and gedit which both use Libpeas - all plugins are within their own subfolders

i.e. /usr/lib/budgie-desktop/plugins/StatusApplet/StatusApplet.plugin
/usr/lib/budgie-desktop/plugins/LockKeysApplet/LockKeysApplet.plugin

Can I suggest that the rhythmbox and gedit approach to plugins folder structure be adopted.  It will make third-party plugin installation much easier to split apart.

**Comment by ikeydoherty** [comment]
I'm gonna level with you - I didn't even know you could do that. :)

**Comment by JoshStrobl** [comment]
Since resolved. Example: `/usr/lib64/budgie-desktop/plugins/org.budgie-desktop.applet.budgie-menu/BudgieMenu.plugin`
