### ISSUE TITLE
Better Budgie Menu search

### ISSUE THREAD

**Issue by theSoenke** [budgie-desktop/budgie-desktop#397]
Hi,

i think the search results in the budgie menu could be improved. For most applications it would be enough to type 1 or 2 characters, but i often have to type at least 4 characters until it's the first result. The search in gnome or even the rundialog work a lot better.

Maybe the categories should also be removed from the search. Because of the categories programs often appear multiple times in the results

I'm running 10.2.5 on arch

Thanks

**Comment by Redneckita** [comment]
The categories can already be removed, they are under panel settings in Raven; You can customize all applets from there

**Comment by ikeydoherty** [comment]
Categories won't be removed by default.

**Comment by theSoenke** [comment]
Totally fine with that. Found the setting to turn off the categories. 
But the search results have definitely some room for improvement.

**Comment by ikeydoherty** [comment]
Ya not gonna argue with that.

**Comment by ikeydoherty** [comment]
Better searching is now in git and works like Brisk

**Comment by zfmaster** [comment]
Why not to rank items by popularity or last run? For example, I'm using Chrome and Chromium web browsers, but Chrome more often. I used to press Super key, type 'Ch' and Enter. On Albert launcher after some days of use it's enough even 'C'. It's 3 keys pressed to run app. But now I need to type 'chr' and after that move cursor down and only after to hit Enter. 
Another example is Shutter. I'm using it very often, but when I'm typing 'Shu' I'm getting Shutdown. 
![tooltip_171](https://user-images.githubusercontent.com/10129233/39464869-9f3086e0-4d28-11e8-9203-3ab1630ba7f2.jpg)
![tooltip_170](https://user-images.githubusercontent.com/10129233/39464870-9f570770-4d28-11e8-8614-8016647b2c6c.jpg)
