### ISSUE TITLE
Switching keyboard layout when Budgie menu is open closes it

### ISSUE THREAD

**Issue by IlyaBizyaev** [budgie-desktop/budgie-desktop#420]
In my case, that's Alt+Shift combination.

**Comment by ikeydoherty** [comment]
Not sure I see the bug here? A global modifier took focus from the menu

**Comment by IlyaBizyaev** [comment]
Well, it's probably not a bug report, but an enhancement proposal. Can't remember that exactly now, but it seems to me that other DEs don't close the menu in this case, which seems more logical to a user (don't have to reopen), not to a developer. Sorry if I'm mistaken here.

**Comment by ikeydoherty** [comment]
Nope - that's all I was trying to clarify. Whether it was a bug or not :) Doesn't mean I won't fix it.

**Comment by ikeydoherty** [comment]
In the new system the menus own exclusive grab over X11 keyboard and mouse, thus its no longer possible (in git) to close with shortcuts like this.

**Comment by ahmedflix25** [comment]
also you can't change Power+Space to Alt+Shift from the settings you need to set it from the dconf-editor
