### ISSUE TITLE
[Fedora 23] gsettings will only set background to a picture of bricks

### ISSUE THREAD

**Issue by TheInitializer** [budgie-desktop/budgie-desktop#442]
When I run 

```
gsettings set org.gnome.desktop.background picture-uri <path to image>
```

it just sets the background to a picture of bricks.

**Comment by ikeydoherty** [comment]
Given that I don't know what you're setting as the path, I can't possibly know that you're not just setting the image to a picture of bricks.

Make sure you use "file://" in the URI, and not just a path. Also make sure its an image and not a .xml, and then get back to me.

**Comment by TheInitializer** [comment]
1. The image is not a picture of bricks
2. I am using file://
3. It's a .jpg image
4. It does this for multiple images

The image is on a seperate partition, if that affects anything...

**Comment by ikeydoherty** [comment]
Dumb question but is the same thing happening via gnome-control-center?

**Comment by TheInitializer** [comment]
No.

Except, at least the first time I logged in to budgie, gnome-control-center couldn't set the background to the default Fedora wallpaper - it would just show a black wallpaper. It worked for all the other ones though...

I'm going to log out of gnome and back into budgie to do some more testing

**Comment by ikeydoherty** [comment]
What version of GNOME is this?

**Comment by TheInitializer** [comment]
I use GNOME 3 for my daily work and installed budgie alongside it.

**Comment by TheInitializer** [comment]
So I logged back in to budgie and it's working now... weird

**Comment by TheInitializer** [comment]
Ah, so I figured out the problem.

When you use gsettings once to change the background, it works.

When you use it again, it stays at that background.

When you use GNOME settings to change the background, it changes to that background.

Then when you use gsettings again, it goes to the original background.

**Comment by TheInitializer** [comment]
Here's exactly what I did:

- put certain image at background.jpg
- run gsettings to change background to that image
 - it works
- overwrite background.jpg with other image
- run gsettings again
 - background stays the same
- use GNOME settings to change background to other image
 - background changes to that image
- use gsettings again to try and change background to new background.jpg
 - background changes to original image at background.jpg
-log out and log back in
 - background finally changes to new background.jpg

Maybe some sort of cache thing?

**Comment by ikeydoherty** [comment]
I'm redoing the handling of the wallpapers right now

**Comment by TheInitializer** [comment]
Thx. I'll test again when it's finished

**Comment by ikeydoherty** [comment]
Ah ok we need file monitor and background cache implemented. No biggy

**Comment by ikeydoherty** [comment]
This is going to be a 3-part change.
This is the first change https://github.com/solus-project/budgie-desktop/commit/acbae131038564f75da6bcd0840dccf28ebae575

**Comment by JoshStrobl** [comment]
@TheInitializer Please confirm as to whether or not this issue is resolved in latest Budgie and Fedora.

**Comment by TheInitializer** [comment]
@JoshStrobl 

Wow, this is a really old issue :P 

I'm no longer using Fedora - I switched to Arch a few months ago. However, I can reinstall Budgie and test it again if you like

**Comment by JoshStrobl** [comment]
> Wow, this is a really old issue :P

Yea I'm going through and triaging.

> However, I can reinstall Budgie and test it again if you like.

That'd be appreciated.

> You can follow my steps above if you want to try it yourself.

Seeing as I've never had this issue (least, as far as I can remember, May 2016 was a long while ago), would probably be best for you to try to reproduce it :smile:

**Comment by TheInitializer** [comment]
Sorry for the delay.

It appears that the issue is still present. I'm using Arch this time, but the exact same thing is happening. If it has the same filename as the previous background image, the background doesn't change.

**Comment by ikeydoherty** [comment]
We use a background cache with the filename which was previously not being allocated. Now you'll need to set the wallpaper again (possibly away and back) and the new texture will be used. This is fixed in git master and will be in the next release
