### ISSUE TITLE
Maximize windows do not take the whole available height

### ISSUE THREAD

**Issue by nlaplante** [budgie-desktop/budgie-desktop#473]
When I maximize a window, it does not take the whole available height. There's an empty gap which seems to be of equal height as the panel. The gap resizes when I resize the panel via the settings.

![screenshot from 2016-06-14 10-14-19](https://cloud.githubusercontent.com/assets/141054/16046023/efa22566-3218-11e6-83a3-a04a9695eb07.png)

Solus 1.2

**Comment by feskyde** [comment]
It happens only with GNOME Terminal or with all applications?

**Comment by ikeydoherty** [comment]
Sorry, 1.2? That's not even out, so....

**Comment by nlaplante** [comment]
It happens with all apps.

Installed 1.1 yesterday and did a ```eopkg upgrade```.

```
nicolas at maestoso in ~
$ cat /etc/solus-release 
Solus 1.2
```

**Comment by ikeydoherty** [comment]
You only have the version file because we had to push security updates out :) If you look at /etc/image-version it paints a different story.

Next question, what graphics and resolution?

**Comment by nlaplante** [comment]
@ikeydoherty got it! sorry!

I have dual GPU: Intel and nVidia. I run exclusively on the Intel GPU.

Resolution: **1920x1080**. Happens both on laptop screen and external monitor.

**If I only use the laptop screen and set it to its native resolution (4k), the problem does NOT happen.**

```
$ lspci
00:00.0 Host bridge: Intel Corporation Haswell DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Haswell PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Haswell Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Haswell HD Audio Controller (rev 06)
00:04.0 Signal processing controller: Intel Corporation Device 0c03 (rev 06)
00:14.0 USB controller: Intel Corporation Lynx Point USB xHCI Host Controller (rev 05)
00:16.0 Communication controller: Intel Corporation Lynx Point MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation Lynx Point USB Enhanced Host Controller #2 (rev 05)
00:1b.0 Audio device: Intel Corporation Lynx Point HD Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation Lynx Point PCI Express Root Port 1 (rev d5)
00:1c.2 PCI bridge: Intel Corporation Lynx Point PCI Express Root Port 3 (rev d5)
00:1c.3 PCI bridge: Intel Corporation Lynx Point PCI Express Root Port 4 (rev d5)
00:1c.4 PCI bridge: Intel Corporation Lynx Point PCI Express Root Port 5 (rev d5)
00:1d.0 USB controller: Intel Corporation Lynx Point USB Enhanced Host Controller #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation Lynx Point LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation Lynx Point 6-Port SATA AHCI Controller (rev 05)
00:1f.3 SMBus: Intel Corporation Lynx Point SMBus Controller (rev 05)
00:1f.6 Signal processing controller: Intel Corporation Lynx Point Thermal Management Controller (rev 05)
02:00.0 3D controller: NVIDIA Corporation Device 0ff6 (rev a1)
06:00.0 Network controller: Broadcom Corporation Device 43b1 (rev 03)
07:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device 5249 (rev 01)
```

**Comment by ikeydoherty** [comment]
So its specific to 4K detection?

**Comment by nlaplante** [comment]
I don't know if it's specific, but as soon as I use a different resolution than 4k on the laptop screen or use an external display which is not 4k, then the problem occurs.

**Comment by nlaplante** [comment]
FYI, I deleted the default panel and created another one with the same widgets. Problem gone.

**Comment by nlaplante** [comment]
And, after loggin out and back in, the problem is back.

**Comment by ikeydoherty** [comment]
hidpi panel reservations were fixed
