### ISSUE TITLE
Disabling shadow from panel should also disable it from raven

### ISSUE THREAD

**Issue by villekivela** [budgie-desktop/budgie-desktop#480]
For consistencys sake it would make sense to disable the shadow from raven when you disable it from panel.
![raven-shadow](https://cloud.githubusercontent.com/assets/5814559/16356619/7c03b7e6-3ae7-11e6-8bab-e4c0c1ca319f.png)

**Comment by ikeydoherty** [comment]
The setting is per panel, it would have to be a new setting

**Comment by villekivela** [comment]
Right, should there be a tab for Raven settings? Raven is an side panel so in that sense the settings for it could be featured under the panel settings tab.

If you are planning to feature applets for Raven it could have different tab to feature the options for it. It would have more room for all the options and would differentiate it better from the basic panels.

**Comment by ikeydoherty** [comment]
Raven applets are planned, per the TODO list

**Comment by ikeydoherty** [comment]
We support 4 panels now so Raven is most definitely not a panel. The appearance of Raven should be controlled only by the theme
