### ISSUE TITLE
Budgie menu - repeating items

### ISSUE THREAD

**Issue by TheAifam5** [budgie-desktop/budgie-desktop#512]
Budgie menu shows multiple launchers for GitKraken
On ALT+F2 shows only one.

![repeating-items](https://cloud.githubusercontent.com/assets/2192274/17098186/607fa124-5261-11e6-83ac-32791057d23d.png)
![alt](https://cloud.githubusercontent.com/assets/2192274/17098260/b573801a-5261-11e6-9630-1f430c2ff1b7.png)

**Comment by ikeydoherty** [comment]
That's because GitKraken is in multiple categories

**Comment by TheAifam5** [comment]
Would be good to add filter if budgie menu is set to "Compact Mode" without "Show headers" enabled :)

**Comment by niyasc** [comment]
I'm experiencing same problem with `gnome-tweak-tool`. As @TheAifam5 suggested it would be nice to have a filter that check for unique entries when *Compact Menu* is enabled without headers.

**Comment by ikeydoherty** [comment]
OK let's not turn this into a "me too" fest :)

**Comment by andresclari** [comment]
Probably we need a "smart" way to select a proper default category, and only shot it in 1 place. Honestly having a launcher present the same app in multiple categories doesn't "feel" right. Even though it may be useful in certain occasions I suppose.

So I'd propose by default fix it to only show 1 launcher per program, and at most a toggle to disable that in settings somewhere.

**Comment by ikeydoherty** [comment]
Fixed in 86a6fe770f4fb9c4cf26062dc4d564ab7223a8e9
