### ISSUE TITLE
calendar doesn't work

### ISSUE THREAD

**Issue by danboid** [budgie-desktop/budgie-desktop#517]
If I click on the Budgie clock and choose 'calendar', nothing happens.

If this is an Arch packaging error and this depends upon a GNOME component I've not got installed, it would be good if Budgie could print an error or notification prompting the user to install the required thing.

**Comment by ikeydoherty** [comment]
Install gnome-calendar.

**Comment by danboid** [comment]
I've installed gnome-calendar now and it works if I run it from a terminal but it doesn't get launched if I select Calendar from the clock menu.

**Comment by JoshStrobl** [comment]
Not able to reproduce as of latest Budgie (10.2.9).
