### ISSUE TITLE
Display day and date on clock mouseover

### ISSUE THREAD

**Issue by danboid** [budgie-desktop/budgie-desktop#518]
I would like Budgie to display the day and date on hovering the cursor over the clock for a second or two please.

**Comment by ikeydoherty** [comment]
Display it where?

**Comment by danboid** [comment]
I would like it to be displayed just below the clock if the panel is along the top and just above the clock if the panel is on the bottom of the desktop.

Thanks

**Comment by ikeydoherty** [comment]
How's it gonna fit?

**Comment by danboid** [comment]
I wasn't intending it would be displayed within the panel but it would appear as a small pop-up running along the appropriate edge of the panel. Not a window - I'm unsure what GTK calls 'em TBH. LIke a window but without any decorations, usually yellow in colour :)

**Comment by danielpinto8zz6** [comment]
Hey danboid, I added what you asked in my calendar applet, check if it's that:
https://github.com/danielpinto8zz6/budgie-calendar-applet

**Comment by danboid** [comment]
Tool tip?

**Comment by ikeydoherty** [comment]
@danboid oh a tooltip, yeah sorry having an Irish moment here. Can easily add.

**Comment by danboid** [comment]
Thanks for your response Daniel but I'm rooting for this feature to be a standard thing. Everyone needs to know the date! :)

**Comment by danboid** [comment]
Thanks Ikey! It's a celtic thing, obvs! :)

**Comment by ikeydoherty** [comment]
I keep getting this feeling we need a secondary kind of widget for this extra info.. not quite a popover.. some kind of more persistent rounded window thing.. Instead of just boring tooltips..

And probably need it in a few places.. the idea is slowly cooking..

**Comment by andresclari** [comment]
Something around the same design you did for the volume popover, with about half the text size of the clock, yet larger than tooltip.. With the color scheme we're sporting should look quite cool.

Having it show without delay, or perhaps some 230ms or so, would make it nice.

**Comment by ikeydoherty** [comment]
@andresclari yeah I still haven't settled on the final idea yet, it's within reach.. ^^ It needs to be visually distinct from notifications though..

**Comment by JoshStrobl** [comment]
Given we now support enabling date for the clock applet as our preferred method for date displaying, marking this as resolved.
