### ISSUE TITLE
Clock applet is not properly aligned with other applets

### ISSUE THREAD

**Issue by feddasch** [budgie-desktop/budgie-desktop#523]
Clock applet is a bit down (or other applets are a bit up):
### Budgie 10.2.6:

![screenshot from 2016-08-02 07-54-07](https://cloud.githubusercontent.com/assets/20542037/17331833/fa057e76-58a2-11e6-9a0d-c54a27d9763b.png)
### Budgie (latest commit):

![screenshot from 2016-08-02 10-36-32](https://cloud.githubusercontent.com/assets/20542037/17331800/d7e2c27c-58a2-11e6-8704-5ba3353c9350.png)

**Comment by ikeydoherty** [comment]
Well spotted :) Just note to be cautious when using master, it tends to break a lot ^^

**Comment by feskyde** [comment]
Sorry, accidentaly closed, fuck those Android clients :stuck_out_tongue_closed_eyes:

**Comment by feskyde** [comment]
Another little issue like this but less noticeable, application icon and name in "Task List" is a bit closer to the top of the panel (or the bottom if you're using the panel at the top)

![screenshot from 2016-08-10 22-55-38](https://cloud.githubusercontent.com/assets/20542037/17576934/8d01a7f2-5f4e-11e6-9484-7e8a252104d1.png)

It should be at the same height as Menu applet, at least the icon
