### ISSUE TITLE
top panel - add option to move to sides

### ISSUE THREAD

**Issue by Gibbz** [budgie-desktop/budgie-desktop#541]
The top panel is rather limiting in its choices.
It would be great to see an option to have it on the left and right.

**Comment by ikeydoherty** [comment]
"top panel" can also go to the bottom..

Its more than just "on the left and right" anyway, it's also a problem of orientation and how you correctly display your applets in that manner.

**Comment by kq01526** [comment]
Can you please make this a high priority?

Using panels/taskbars on the side for years. Having them on the top or bottom makes no sense with widescreen monitors.

If you would implement [task grouping and window preview thumbnails](https://github.com/budgie-desktop/budgie-desktop/issues/278) and would allow to have the panel oriented vertically on the sides, it would be awesome.

**Comment by ikeydoherty** [comment]
Budgie 11 is the priority. We've already planned to have sidepanels there. Budgie 11 has a place in the priority list though, and that is after LDM is completed in Solus.

**Comment by ikeydoherty** [comment]
This has been implemented in git and will be available in the next release.
