### ISSUE TITLE
Allow customisation of window decoration placement

### ISSUE THREAD

**Issue by ikeydoherty** [budgie-desktop/budgie-desktop#563]
Follow up from this conversation on Twitter: https://twitter.com/joaojotta/status/773100412966666240

Given that we actually use a non-default schema for our button layout, its not actually controllable by external tools. We need to make that an option.
Similarly, we need to ensure X11 Apps respect this, by overriding it as part of Budgie.

This actually entails some of the issues noted in #261

**Comment by joaojotta** [comment]
AWESOME!!!!

**Comment by JoshStrobl** [comment]
Customization of window button location since resolved in Budgie 10.3.
