### ISSUE TITLE
Wrong icons for pinned chrome apps & other applications

### ISSUE THREAD

**Issue by mussel** [budgie-desktop/budgie-desktop#571]
Applications that set different icons per window have different icons for their _IconButton_ when closed (pinned) vs when opened (pinned or not). I believe that this happens because the _PinnedIconButton_ always uses the icon specified by the application in _DesktopAppInfo_. However, once the application is opened the _update_icon_ function (_IconButton_) changes the button's icon to the window's icon.
I observed this issue with the following applications: Slides and Sheets(chrome apps), Image Viewer, Evince, Gimp.

Here are some screenshots. First, when the applications are pinned but closed:
![pinned_closed2](https://cloud.githubusercontent.com/assets/1262461/18412001/2a2ece0a-775b-11e6-82fa-1d830328d6f2.png)

And now after opening them:
![pinned_opened2](https://cloud.githubusercontent.com/assets/1262461/18412007/399eac70-775b-11e6-89bb-9bfffbf26476.png)

This issue also affects the code in PR #551 and there it is even worse because multiple windows can share the same IconButton.

My suggestion is to change the update_icon function to choose the applications' icon by default and only revert to the window's icon if there is no _DesktopAppInfo_ object. Moreover, I _think_ that this change would eliminate the need for the _has_derpy_icon_ function, because its purpose is tell IconButton to use the application's icon.

**Comment by ikeydoherty** [comment]
We use the derp list to filter out somethings that shouldn't update that don't use the icon themes. There are valid GTK apps that override the icon using the GTK+ icon theme, sending a pixmap. An example of this is gnome-control-center, which, as expected, updates the icon when navigating between sections.
It's also what makes dynamic Chrome app icons in the first place.

**Comment by mussel** [comment]
I see. So my suggestion would break this icon update behavior of gnome-control-center. But what about the applications that I showed above? Is this behavior of setting the icon based on their content desirable? I would say that for those applications it is not. **Specially when we begin to group multiple windows under just one IconButton** (which icon, based in which window's content, should we use?)
What do you think?

To prevent just those applications from doing this we could simply use the derp list.

**Comment by ikeydoherty** [comment]
Would it not be a case of displaying the *active* button image ?

**Comment by mussel** [comment]
Personally, I think that having the application's icon in the tasklist and perhaps the window's icon in the window dropdown list, makes it more "readable". 

That been said, your suggestion is reasonable and it is the one that would require the least amount of change on how the applet works. So I implemented it as you suggested. As we start to use the window grouping feature, if we feel that this approach is not the best we could perhaps revisit this topic.

Thanks for the feedback.

**Comment by ikeydoherty** [comment]
Fixed in git because we no longer let X11 icons override `.desktop` icons
