### ISSUE TITLE
Starting files with Launcher

### ISSUE THREAD

**Issue by nexus86** [budgie-desktop/budgie-desktop#580]
So today i noticed that the launcher starts everything if you type the name and hit enter except files. I tried it in the latest Solus release 1.2.0. I know i can create a shortcut for launching the home folder.

**Comment by ikeydoherty** [comment]
I just launched it now on my system. Locale issue.. ?

**Comment by feskyde** [comment]
I think he means opening files and folders directly from the Budgie Menu, like in Cinnamon

**Comment by ikeydoherty** [comment]
Oh. Damn you GNOME Files. lol.

@nexus86 please clarify what it is you're requesting or reporting as clearly I don't get it. :p

**Comment by nexus86** [comment]
I made a small video to show you what i mean xD

[launcherBug.zip](https://github.com/solus-project/budgie-desktop/files/468936/launcherBug.zip)

**Comment by nexus86** [comment]
I also noticed that files is opening after a few tries.

**Comment by GladOSkar** [comment]
I reproduced it. For everyone who does not want to download the Video:

When using the "Run Dialog"

**Comment by ikeydoherty** [comment]
Not downloading random zip from github sorry.. Please reverify when I push 10.2.8 out

**Comment by GladOSkar** [comment]
Reverified. Still behaves the way i explained. 

> When using the "Run Dialog" Launcher, search for "files" and hit enter/click it it does not open the "Files" (nautilus) Application.

BUT after booting, if you start "files"/nautilus via Budgie-Menu once, it then also works via the "Run Dialog"-Launcher.

**Comment by ikeydoherty** [comment]
Yeah turns out this was dbus activation stuff fixed in 10.2.9
