### ISSUE TITLE
Budgie panel length and sidebar location not respecting DPI scaling

### ISSUE THREAD

**Issue by gregflynn** [budgie-desktop/budgie-desktop#585]
Screenshot: http://imgur.com/rEIqtem

When scaling it seems that height and width of the panel are multiplied by scaling factor which results in a thick enough bar, but a very wide panel that juts off the screen :smile: 

I think this is the offending code, but this is the first time I've looked at Vala and I just grepped around for names: https://github.com/solus-project/budgie-desktop/blob/master/panel/panel.vala#L932

System:
Debian stretch (testing)
Budgie 10.2.6-1

Settings toyed with:
`Gdk/WindowScalingFactor` via gnome-tweak-tool (the one budgie seems to care about)
org.gnome.desktop.interface.scaling_factor via dconf-editor (google chrome cares about this one)

**Comment by ikeydoherty** [comment]
Struts are invisible. Everything is literally twice the size as what the code thinks it is when HiDPI scaling is enabled (because its frankly a bit retarded), so we have to accommodate for that in the strut reservation.

**Comment by gregflynn** [comment]
Right, I think width should be half, no? My screen at native resolution is 2880x1800 (MacbookPro11,5). So at 2x the effective resolution is 1440x900, so either a scaled up width or unadjusted width would extend past the edge of the screen, but again I'm just spitballing here.

**Comment by ikeydoherty** [comment]
Right but the width reports at half the actual size, so the X11 struts don't obey hidpi and we multiply them

**Comment by gregflynn** [comment]
¯\_(ツ)_/¯ well that was my only idea

**Comment by ikeydoherty** [comment]
Please confirm with 10.2.8 otherwise I'll need to invalidate the issue

**Comment by gregflynn** [comment]
Ok, I'll take another look later on tonight

**Comment by gregflynn** [comment]
Sorry for the long delay on my part on this, because of this bug I use Gnome 3 full time. Still with debian testing Budge was updated to 10.2.8-1 but the problem still persists

**Comment by gregflynn** [comment]
I couldn't stand gnome-shell crashing anymore on my laptop and gave budgie another go, this issue seems to be fixed as of 10.2.9-2 on debian-testing

thank you again @ikeydoherty for a great alternative gtk3 environment
