### ISSUE TITLE
Make "Alt+F2" Run-Dialog order Items like Budgie-Menu

### ISSUE THREAD

**Issue by GladOSkar** [budgie-desktop/budgie-desktop#591]
For people who would rather use the "Alt+F2" Run-Dialog as Launcher.

Description:
Budgie-Menu "Learns", that when i type "chr" i want to open "Google Chrome", not "Chrome Remote Desktop".

Could you implement the "Alt+F2" Run-Dialog to do the same?

Also, maybe it would make sense to completely unify the functionality of the two launchers and just make them  two different GUIs to the same search "backend", with a Setting in the Raven/Budgie Settings? But that is for you guys to decide :)

**Comment by JoshStrobl** [comment]
Marking wontfix. We're actually changing Budgie Menu's logic to be..well logical and not have a crazy sorting method.
