### ISSUE TITLE
Blacklist Firefox Developer Edition From Changing its Icon

### ISSUE THREAD

**Issue by Flat** [budgie-desktop/budgie-desktop#595]
Currently Firefox Developer Edition changes its own icon, this overrides the current icon theme and provides no extra functionality i.e. current website favicon or other.

**Comment by ikeydoherty** [comment]
What's the `.desktop` file name btw?

And the `xprop` output for the Firefox window, specifically WM_CLASS line(s)

**Comment by Flat** [comment]
Desktop file is ```firefox-developer.desktop``` 
wmclass:```WM_CLASS(STRING) = "Navigator", "firefox-developer"```

**Comment by ikeydoherty** [comment]
Fixed in git because we no longer let X11 icons override `.desktop` icons
