### ISSUE TITLE
Android Studio pin to panel

### ISSUE THREAD

**Issue by skmlcd** [budgie-desktop/budgie-desktop#602]
**Operating System**: Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

**The issue encountered**
Android Studio can't be pinned to panel. Installed from [3rdParty](https://wiki.solus-project.com/3rdParty#Android_Studio).

![android studio budgie pin to panel](https://cloud.githubusercontent.com/assets/10860015/18609496/e2ccb122-7d03-11e6-8ce5-f0ce8c554ab6.png)

Android Studio desktop file (/usr/share/applications/):

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Icon=/opt/android-studio/bin/studio.png
Exec=android-studio %f
Comment=IDE for Android Development
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-android-studio
```

**Comment by shansurat** [comment]
**Solus Version: ** 3.999
**Budgie Version: ** 10.4

Is this still an issue? I can already pin Android Studio to panel.

**Comment by fossfreedom** [comment]
Thanks for the confirmation

**Comment by Mjafko** [comment]
Well I still dont have option to Pin it...

**Comment by shansurat** [comment]
I think we have to open this issue again. I observed that **it can be pinned to panel** if the Android Studio is installed using the official Linux installation from the [Android Studio Installation in Linux](https://developer.android.com/studio/install#linux), but if Android Studio is installed by the installation procedure from [Solus Third Party Softwares](https://solus-project.com/articles/software/third-party/en/), **it cannot be pinned to panel**.
