### ISSUE TITLE
v10.2.7 on latest openSUSE Tumbleweed - Many new issues

### ISSUE THREAD

**Issue by geckolinux** [budgie-desktop/budgie-desktop#624]
Hi there, I distribute openSUSE builds with Budgie. I tried updating to v10.2.7 on openSUSE Tumbleweed on the same release that also upgraded to GTK and Gnome 3.22. There are quite a few issues with the panel. I assume this is due to the GTK upgrade, since v10.2.7 on the older openSUSE Leap base doesn't have most of these issues that are present with Tumbleweed:

1. No raven icon (happens on both Leap and Tumbleweed builds)
1. Menu icon is scaled wrong
1. New panel items always get added in the center
1. Panel items can not be moved. It seems that the up/down arrows are on a layer underneath the session buttons and are not clickable.
1. Panel items can not be configured. Again I suspect this is because the configure button is on a layer underneath the Budgie session buttons. It is visible but not clickable.
1. Previously configured desktop and lockscreen wallpaper disappeared, and can not be selected from the Budgie settings. The desktop right-click wallpaper chooser also does not actually change the wallpaper. I was able to change it with Gnome Tweak Tool.

![screenshot from 2016-09-24 11-52-15](https://cloud.githubusercontent.com/assets/2692138/18809887/9c6d1f60-824d-11e6-826e-2292d9cb1958.png)

Thanks for the help!

**Comment by JannikHa** [comment]
Yes, I've recently discussed this probem (GTK 3.22 - Theme Fix) with Ikey, he immediately fixed this problem.

To all of you points, please reinstall **budgie-desktop** and report back if your problem is still occuring. Also, try the **build-in** theme, maybe it fixes the panel-problems.


To your point 3: New panel item are **always** added in the center of the panel, not a bug, it's just how it is.

To the other points, as I said, please first try to reinstall budgie-desktop, most, if not all of your points should be fixed by now actually.

**Comment by ikeydoherty** [comment]
Honestly the theme fix won't help unless you're using a *rebuilt* theme too. This is done in git, not by the build system

**Comment by ikeydoherty** [comment]
> Previously configured desktop and lockscreen wallpaper disappeared, and can not be selected from the Budgie settings. The desktop right-click wallpaper chooser also does not actually change the wallpaper. I was able to change it with Gnome Tweak Tool.

That's a GNOME thing, not a Budgie thing. We also don't have a lockscreen in Budgie

**Comment by geckolinux** [comment]
Thanks a lot for the replies, I'm just now getting around to trying to rebuild my GeckoLinux spins with Budgie. @ikeydoherty  Would it be possible to update the OBS to 10.2.8 for openSUSE? Thanks a lot!

**Comment by ikeydoherty** [comment]
Yeah just got your emails

**Comment by ikeydoherty** [comment]
I give up dealing with the weird shit between opensuse + fedora and their inability to agree on a single macro. If I fix one, the other breaks, or one version of one of them breaks. It's a nightmare.

**Comment by geckolinux** [comment]
Nice work Ikey! I really appreciate you taking the trouble to package Budgie for other distros, especially openSUSE. I have a separate spin for all the desktop environments, and Budgie is actually one of the most popular.

It looks like you managed to pull it off, because 10.2.8 is looking to be almost flawless!

![screenshot from 2016-10-29 07-42-05](https://cloud.githubusercontent.com/assets/2692138/19829642/91d4e068-9dac-11e6-9e66-a8ca6a7b4ac6.png)

Thanks again.

**Comment by ikeydoherty** [comment]
Are you sure? Looks like no Budgie I ever seen - rather it looks like you disabled internal theming and are using a theme that doesn't support Budgie :/ I've only managed to get *some* of the updates into OBS - the rest are failing and I don't believe I will be able to continue maintaining the OBS repos anymore.

Budgie is in the main repos for Arch Linux, Debian, Ubuntu, Manjaro, Sparky Linux, and others. It is only absent from Fedora and openSUSE now. With the major architectural changes due for `11.0.0`, downstreams should consider pushing for their distros to include Budgie in their repos, and not have me maintain them any longer. It's simply not feasible for me to maintain other distros as well as Solus, the OBS repo has only ever been intended as a staging repo until maintainers appeared, which in 3+ years they have not.

**Comment by geckolinux** [comment]
> Are you sure? Looks like no Budgie I ever seen - rather it looks like you disabled internal theming and are using a theme that doesn't support Budgie

Hi Ikey, correct, I disabled the internal theme, and it's just using Numix. To me it looks and works fine. :) I have the following packages installed from your OBS repo:

` budgie-desktop-10.2.8-2.1.x86_64.rpm`
` typelib_1_0-Budgie-0_1-10.2.8-2.1.x86_64.rpm`

Sorry for the packaging frustrations. I know that openSUSE usually tries to throw the burden of packaging on others, i.e. nobody there wants to assume responsibility for new packages. But if you contact somebody on the Factory mailing list or possibly the other users that are packaging Budgie maybe somebody could step up. It would be a pity to lose Budgie for openSUSE.
