### ISSUE TITLE
Panel not hidden by fullscreen applications

### ISSUE THREAD

**Issue by Flat** [budgie-desktop/budgie-desktop#630]
Arch Linux - Linux 4.7.6-1
Budgie v10.2.7.r20.gce60991 (commit: ce609910d7678e8f51e60f09d4cf9c10f77f4b39)
GNOME 3.22

Full screen applications do not cover the budgie panel

 ...

1) build budgie from git master
2) launch fullscreen application - e.g. Games, mpv fullscreen
![2016-10-01-17 50 01](https://cloud.githubusercontent.com/assets/2048861/19017209/c7832052-87ff-11e6-83d0-e5bcc76c8b57.png)
![2016-10-01-17 50 17](https://cloud.githubusercontent.com/assets/2048861/19017210/c9c0a3d0-87ff-11e6-8df4-3e1a5b7641a1.png)

**Comment by Snisser** [comment]
Having the same issue aswell.

**Comment by ikeydoherty** [comment]
Fuck GNOME 3.22... so much...

**Comment by Flat** [comment]
They sure made a bunch of lovely breaking changes didn't they?

**Comment by r3pek** [comment]
FWIW

[[mutter] removal of META_LAYER_FULLSCREEN causes WINDOW_TYPE_HINT_DOCK and fullscreen apps to overlay](https://bugzilla.gnome.org/show_bug.cgi?id=772937)

**Comment by Flat** [comment]
Fixed in upstream mutter commit [bfb46ff85041b04538d899c581056c77214e3ae0](https://git.gnome.org/browse/mutter/commit/?id=bfb46ff85041b04538d899c581056c77214e3ae0)

**Comment by ikeydoherty** [comment]
Cheers - kudos to the Mutter developers to fixing the issue, and to those who would report and chase it upstream :)
