### ISSUE TITLE
budgie-panel crash when searching after something has just been installed

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#632]
**Operating System**: Ubuntu 16.10
**Budgie version**:  Budgie 10.2.7 + patches https://github.com/budgie-remix/budgie-desktop/tree/debian/debian/patches

**The issue encountered**
budgie-panel crash
 ...

**Steps to reproduce the issue**
Install any app via command line (e.g. sudo apt install giggle) and then open the menu and press a key to initiate a search - the panel crashes

trace:
http://paste.ubuntu.com/23265744/

**Comment by fossfreedom** [comment]
bit more trace:

 http://paste.ubuntu.com/23266001/

**Comment by fossfreedom** [comment]
https://github.com/solus-project/budgie-desktop/blob/master/panel/applets/budgie-menu/BudgieMenuWindow.vala

line 496 or 501 - parent_menu is invalid ?

**Comment by fossfreedom** [comment]
going to do some more testing - but I think the panel does NOT crash if the budgie-menu properties "show header" is not ticked.

**Comment by ikeydoherty** [comment]
See: 0fe1b23fe576f191176794939fb5d84e10b36a35

I'm now looking into the header part of the issue

**Comment by ikeydoherty** [comment]
Actually yeah almost certain of it - the weak references affect `parent_menu`

**Comment by fossfreedom** [comment]
ok - have applied the patch above onto 16.04 ubuntu.  Menu headers are off.

Further crash reports:

http://paste.ubuntu.com/23345306/

http://paste.ubuntu.com/23345313/

**Comment by ikeydoherty** [comment]
So hard to debug because it's in a .so - gonna try a standalone build and get back to you

**Comment by ikeydoherty** [comment]
@fossfreedom can you see if you get the issue in this test?
https://github.com/ikeydoherty/budgie-menu-underp

And any stack trace would be beautiful thank you

**Comment by ikeydoherty** [comment]
Run `./build.sh`, then run `./debug.sh` to start the menu window in debug mode


Run `./test.sh` to then thrash files into /usr/share/applications, remove them, and fire the update triggers, and let's see if you get any bugs. I'm not getting it on Solus

**Comment by ikeydoherty** [comment]
Even when invoking with:

```bash
for i in `seq 1 100`; do ./test.sh ; done
```

I cannot reproduce..

**Comment by fossfreedom** [comment]
thanks ikey for looking into this.

this is the stacktrace for crufttest

http://paste.ubuntu.com/23345856/

**Comment by ikeydoherty** [comment]
Interesting, please also post the autogenerated .c files

**Comment by fossfreedom** [comment]
http://paste.ubuntu.com/23345866/

http://paste.ubuntu.com/23345868/

**Comment by ikeydoherty** [comment]
OK I've now added a `mkubuntu.sh` and `mksolus.sh` for comparison between the Vala outputted C files. There are definitely differences.

Can you see if you can run the SolusTest binary and whether you get the same issue there?

**Comment by fossfreedom** [comment]
did you add SolusTest to the test repo? - I don't see it.

**Comment by ikeydoherty** [comment]
./mksolus.sh to create SolusTest

**Comment by fossfreedom** [comment]
hmm - when I run ./mksolus.sh I get the following output

http://paste.ubuntu.com/23346045/

**Comment by ikeydoherty** [comment]
Highly suspect. Fixed in https://github.com/ikeydoherty/budgie-menu-underp/commit/f83be10266eb9bfb72fb4b4447c2fe3c879d6098

**Comment by fossfreedom** [comment]
k  - thanks

http://paste.ubuntu.com/23346077/

**Comment by ikeydoherty** [comment]
```
#line 180 "BudgieMenuWindow.vala"
			_tmp2_ = self->priv->tree;
#line 180 "BudgieMenuWindow.vala"
			gmenu_tree_load_sync (_tmp2_, &_inner_error_);
```

What if you run with latest pull?

`./build.sh/`
`./debug.sh` etc

**Comment by ikeydoherty** [comment]
To be blunt I don't see this being fixed in time for `10.2.8` as two things are wrong here:

1) Vala is doing different things on both our systems. We're rewriting to C and this just reenforces that..
2) libgnome-menus is clearly decrepit.

**Comment by fossfreedom** [comment]
aye - totally agree with you.

CruftTest does still keel over.  Do you want another stacktrace?

**Comment by ikeydoherty** [comment]
Honestly don't think there's anything we can do until the rewrite tbh :/

**Comment by fossfreedom** [comment]
maybe its the way debian/ubuntu installs/uninstalls apps - is there a possibility the refresh event is getting called too quickly - there is a very quick install/uninstall event being fired - and the menu is in the middle of being dismantled/recreated and hence the memory issues?

**Comment by ikeydoherty** [comment]
That's the thing though we actually guard against that, we have a check for whether we're reloading and it's protected with a mutex

**Comment by fossfreedom** [comment]
sigh ... ok - thanks.  I'm going to crash.  Cheers for your help tonight.  much appreciated.

**Comment by ikeydoherty** [comment]
No longer Ubuntu specific, it finally reared it's ugly head on Solus:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3a8678cfb4 in g_settings_get_value ()
   from /usr/lib64/libgio-2.0.so.0
(gdb) bt
#0  0x00007f3a8678cfb4 in g_settings_get_value () at /usr/lib64/libgio-2.0.so.0
#1  0x00007f3a6db62017 in budgie_menu_window_apply_scores (self=self@entry=0x238d0d0) at BudgieMenuWindow.c:1257
#2  0x00007f3a6db622db in ___lambda4__gsource_func (self=0x238d0d0)
    at BudgieMenuWindow.c:657
#3  0x00007f3a6db622db in ___lambda4__gsource_func (self=0x238d0d0)
    at BudgieMenuWindow.c:665
#4  0x00007f3a861a9794 in g_main_context_dispatch ()
    at /usr/lib64/libglib-2.0.so.0
#5  0x00007f3a861a9b58 in  () at /usr/lib64/libglib-2.0.so.0
#6  0x00007f3a861a9ea2 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#7  0x00007f3a87d2c10d in gtk_main () at /usr/lib64/libgtk-3.so.0
#8  0x000000000040ba1f in _vala_main (args=<optimized out>, args_length1=<optimized out>) at main.c:120
#9  0x00007f3a85b9a481 in __libc_start_main (main=
    0x40b6e0 <main>, argc=2, argv=0x7ffdf77ecc18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdf77ecc08)
    at ../csu/libc-start.c:289
#10 0x000000000040b7ba in _start () at ../sysdeps/x86_64/start.S:120
(gdb) 
```

**Comment by fossfreedom** [comment]
Hi Ikey,

  have applied the patch but still crashing on 16.04.  At one point I thought it was due to the clock applet - I was seeing the last bit in coredumpctl showing the update procedure in the clock applet.

I removed the clock applet and everything was stable.  Then I rebooted and I'm back with the original crash in giomenu.

Given that the problem is shifting around there is most probably memory corruption issues of some-sort - just that ubuntu 16.04 seems to suffer much more than any other distro.

**Comment by ikeydoherty** [comment]
Yeah it's definitely an issue with dangling pointers

**Comment by fossfreedom** [comment]
finally understand this one.  Traced to one specific patch in gnome-menus that canonical devs made for Unity.  Need to work out what to-do next by contacting those devs.

thanks.

**Comment by ikeydoherty** [comment]
Oh? Link to patch please? This one has had me scratching my head big time..

**Comment by fossfreedom** [comment]
http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-menus/gnome-menus_3.13.3-6ubuntu4.debian.tar.xz  patch file debian/patches/80_file_monitor_delayed.patch

Created apparently in response to this LP bug about Unity: https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1506744
