### ISSUE TITLE
English not working in budgie search

### ISSUE THREAD

**Issue by rawsh** [budgie-desktop/budgie-desktop#635]
**Operating System**: Solus 1.2.0.5
**Budgie version**:  Budgie 10.2.7

Weird characters in search

![image](https://cloud.githubusercontent.com/assets/7035671/19044961/20cfed40-895c-11e6-8e93-4a35ffdfcdb1.png)

**Comment by ikeydoherty** [comment]
What locale is it using?

**Comment by rawsh** [comment]
> What locale is it using?

English

**Comment by fossfreedom** [comment]
actually - I've also seen that ... albeit very briefly before the panel crashes on ubuntu - it occurs for me when you switch on menu headers and you either install or uninstall apps and then open the menu and search for the item.

**Comment by ikeydoherty** [comment]
We'll need to see this retested with the new release

**Comment by JoshStrobl** [comment]
Closing as the original reporter has not tested this against 10.2.8 or 10.2.9.
