### ISSUE TITLE
"Pin to panel" do not appear in the Web browser Pale Moon (Solus 1.2.1)

### ISSUE THREAD

**Issue by fu-sen** [budgie-desktop/budgie-desktop#659]
I have upgraded the Solus to 1.2.1.
but the menu of Pale Moon is still "Pin to panel" does not exist.

![screenshot from 2016-10-19 15-13-58](https://cloud.githubusercontent.com/assets/5434159/19507767/fdefaebc-960f-11e6-87ff-ab9c99ccc931.jpg)

I opened this issue again:
#575 "Pin to panel" do not appear in the Web browser Pale Moon

**Comment by ikeydoherty** [comment]
OK - we'll get you an update out soon, and put the patch directly into Solus

**Comment by JoshStrobl** [comment]
Since resolved in Budgie 10.2.8+
