### ISSUE TITLE
[Suggestion] Desktop Icon Grid

### ISSUE THREAD

**Issue by iachopolo** [budgie-desktop/budgie-desktop#670]
I believe that the desktop would look much better and neater if the icons were ordered in a sort of "grid" with vertical and horizontal rows, not only columns. Both Windows and iOS have this...

**Comment by fossfreedom** [comment]
It is Nautilus that is providing the desktop icons capability not budgie-desktop.

**Comment by iachopolo** [comment]
But it could be an idea for the budgie-desktop, isn't it?

**Comment by diazbastian** [comment]
@iachopolo You can write a report directly to [Nautilus](https://bugzilla.gnome.org/page.cgi?id=browse.html&product=nautilus) developers (or the file manager you use).

**Comment by iachopolo** [comment]
Actually, it already exists as a bug for Nautilus, like this one: https://bugzilla.gnome.org/show_bug.cgi?id=129937. But it's been there since 2003. And again a similar one from this year: https://bugzilla.gnome.org/show_bug.cgi?id=765560
It looks like it's not a priority for them.
Perhaps you guys want to make something about it :)

**Comment by ikeydoherty** [comment]
For us to do anything about it would involve replacing Nautilus, at least so far as the desktop icons.

**Comment by iachopolo** [comment]
I understand, in the future maybe. There are some other cool stuff that could be added, like organize by type, by modification date, and icon sizing.
Thanks for your answers :)

**Comment by JoshStrobl** [comment]
Closing as an upstream Nautilus issue.
