### ISSUE TITLE
Places indicator: Open the file manager while trying to mount an encrypted device

### ISSUE THREAD

**Issue by haevalencia** [budgie-desktop/budgie-desktop#673]
**Operating System**: Solus 1.2.1
**Budgie version**: Budgie 10.2.8

**The issue encountered**
When trying to open an encrypted device on Places indicator applet, it displays an error: "G_MOUNT_OPERATION_HANDLED but got 2"
In these cases it is better to open the file manager and being entrusted it to display a dialog to enter a password or add a layer of integration with budgie.

**Steps to reproduce the issue**
- Select an encrypted partition/flash drive/SD/external hdd
- Try to mount/open with Places indicator applet

**Comment by diazbastian** [comment]
@haevalencia You could add in the title "indicator places" to alert @cybre

**Comment by ikeydoherty** [comment]
> to enter a password or add a layer of integration with budgie.

The Places Indicator is part of Budgie I'm not quite sure how much more integrated it could be. Can you show me a screeshot or recording of what happens?

**Comment by cybre** [comment]
I can confirm that this is an issue. I'd rather not handle decryption in the applet but leave it to nautilus.

**Comment by cybre** [comment]
Looks like there's an easy way to unlock encrypted devices with UDisks. 
https://lazka.github.io/pgi-docs/UDisks-2.0/interfaces/Encrypted.html#UDisks.Encrypted.call_unlock

**Comment by haevalencia** [comment]
> Can you show me a screeshot or recording of what happens? 

![encrypted](https://cloud.githubusercontent.com/assets/17348259/19628184/5a9cc4f8-992e-11e6-9df4-2ee4a3c6d7f1.png)

This occurs when trying to mount an encrypted partition from the "place indicator applet". As @cybre says, a level of integration is that the applet mount an encrypted disk, displays a dialog to enter a password and mount the disk correctly. On the other hand, I mentioned that any file manager correctly handles this task and would be better than trying to open a disk of these characteristics, is the file manager that is responsible.

**Comment by ikeydoherty** [comment]
Modal dialogs are a big issue for the panel atm

**Comment by cybre** [comment]
I was thinking of having the password entry in the applet itself.

**Comment by ikeydoherty** [comment]
Just be wary of focus issues, I know the current Popover system makes that a bastard
