### ISSUE TITLE
Moving applet to "end" area moves clock to right

### ISSUE THREAD

**Issue by DerpyCrabs** [budgie-desktop/budgie-desktop#676]
If i move any applet to "end" area clock will move to right.
Steps to reproduce:
1. Add any applet to panel
2. Move it to "end" area
3. Clock will move to right
4. You can restore it position by moving Raven sidebar control up and then down.
Clock has wrong position after moving places applet on this picture.
![Clock has wrong position after moving places applet](https://cloud.githubusercontent.com/assets/9917318/19628181/20571e8e-9982-11e6-95f1-2313b9da3ad0.png)
I can reproduce this bug on 10.2.8 and git versions.

**Comment by tristan957** [comment]
If you log out and log in is your problem fixed? This has been a bug for a while that I think the devs said they had fixed but I continue to notice my applets reorder when I move the workspaces applet to end. It fixes itself though after re-logging in/relaunching the panel.

**Comment by ikeydoherty** [comment]
I can't reproduce for existing applets, i.e. those initialised from settings. Trying with new applet now

**Comment by ikeydoherty** [comment]
Yeah this is only happening for newly added applets. Super weird. I suspect it's being moved across with the incorrect pack index

**Comment by tristan957** [comment]
Glad we could bring it to your attention

**Comment by JoshStrobl** [comment]
Resolved, at some point, likely many releases ago.
