### ISSUE TITLE
workspaces stack up after reboot

### ISSUE THREAD

**Issue by Mikedigitizetoo** [budgie-desktop/budgie-desktop#682]
When reporting issues for Budgie Desktop

**Operating System**: Solus 1.2.1
*_budgie-desktop 10.2.8
*_

I use 5 workspaces with one program on eatch. After a startup of system all 5 programs are all stacked up on workspace 1. Is there a way (simple) to make them stay put (in adviced worspace) after a reboot (like in KDE)?

 ...
/Mike

**Comment by JoshStrobl** [comment]
Closing in favor of #734 due to its expanded details on functionality.
