### ISSUE TITLE
Themes with large buttons causes overlaping in raven

### ISSUE THREAD

**Issue by Malmz** [budgie-desktop/budgie-desktop#688]
**Operating System**: Solus 1.2.1
**Budgie version**: Budgie 10.2.8

**The issue encountered**
Turning off the Built-in theme option and using a theme with large buttons, like Adwaita, causes the menu options to overlap with the power, lock and settings button.

![screenshot](https://cloud.githubusercontent.com/assets/1337808/19772431/7a5ce922-9c66-11e6-99e6-60fe206a9520.png)

**Steps to reproduce the issue**
- Open raven and press the cog.
- Turn off Built-in theme.
- Switch widget theme to Adawita.

**Comment by fossfreedom** [comment]
hmm - adwaita doesnt provide full budgie-desktop support - hence the issues you see.  

Suggestion it would be nice for someone in the community to-do a pull request with the adwaita devs to add the budgie-desktop components such as theming the panel and raven.

Apart from Arc, Adapta and Paper GTK themes do provide budgie-desktop support.

**Comment by Malmz** [comment]
Have not tried Paper but i have the same issue with Adapta. 
![screenshot](https://cloud.githubusercontent.com/assets/1337808/19773499/10ff464c-9c6a-11e6-89ca-cce0c44e0849.png)
My solution would be to make that menu scrollable.

**Comment by ikeydoherty** [comment]
Can't really see Adwaita devs supporting other desktops, Adwaita is the GNOME theme :)

**Comment by tista500** [comment]
@Malmz,

Adapta is NOT for lower-resolution LCDs and large font-sizes, use `Adapta-Eta` or `Adapta-Nokto-Eta` instead... ;(

**Comment by fossfreedom** [comment]
@tista500 any recommendations for the vertical screen resolution to decide whether to use Adapta or Adapta-Eta?  e.g. anything below 1024 vertically should use Adapta-Eta ?

**Comment by tista500** [comment]
@fossfreedom,

Just my thoughts, FHD (1080p) already became LOW resolution today. And Adapta is scaling Gtk+ theme, it means spacing depends on your font-size and font-scaling-factor. In Material Design, 13px(9.75pt) or 14px(10.5pt) are recommended as standard widget font-size in case if your `-gtk-dpi` was set to 96. So Adapta uses `13.33px` (10pt) as nominal font-size for px-to-rem conversion.

It means 12pt or 13pt font-family are completely unmatch with my theme (I don't have any ideas when we need such large fonts as widget standard).

**Comment by fossfreedom** [comment]
damn ... I'm running 1366x768!!

Ok - cheers for the info - very useful.

**Comment by kyrios123** [comment]
I'm a little out of topic, but I have the feeling that when large fonts are enabled in the accessibility, the clock in the panel is not properly aligned with the icons that are next to it.
Could anyone confirm?

**Comment by fossfreedom** [comment]
Correct me if I'm wrong but this was fixed in budgie desktop 10.4
