### ISSUE TITLE
Replace places icon with folder icon

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#690]
**Operating System**: Solus 1.2.1
**Budgie version**: Budgie 10.2.8 

Places icon looks weird. So maybe replace it with folder icon? 

![Alt Text](http://i.imgur.com/TZ4UaCN.png)

**Comment by tristan957** [comment]
I think this is on an icon theme by theme basis. I am using the paper icon theme and my icon is an icon of a hard drive. You'd probably need to submit an issue with the Moka/Arc icon themes. Not sure which icon theme provides it.

**Comment by ikeydoherty** [comment]
https://github.com/budgie-desktop/budgie-desktop/blob/master/src/panel/applets/places-indicator/PlacesIndicator.plugin.in#L8

Didn't think about it before but yeah it uses a hard drive icon. Wouldn't say it's "weird" - but perhaps there is a more appropriate choice.

**Comment by ikeydoherty** [comment]
Assigning to @cybre for consideration of this change

**Comment by ikeydoherty** [comment]
Fixed with PR #1028
