### ISSUE TITLE
Enable finer grain iconography for battery levels

### ISSUE THREAD

**Issue by zi007** [budgie-desktop/budgie-desktop#691]
Better if battery indicator show same info when 30% and after 20 and 10%
Now I can hear something only if 7% and it is not good because after instant action needed.

Operating System:  Solus 1.2.1
Budgie version: 10.2.8

**Comment by tristan957** [comment]
Sorry. You're English is a little hard to understand. Do you mean that the battery icon looks the same for areas between 33%-10%. I have also been kind of bothered with this. I have noticed the battery icon updates at 75%, 33%, and 10%. I would love for the icon to update maybe every 10% so I get a better feel for my battery life. Unfortunately I think this is a GNOME issue because the same thing occurs on the GNOME desktop.

**Comment by zi007** [comment]
Sorry!:) I mean that I do not watching indicator every time. In this moment he signal me only when is 7% to plug electricity.  Better would be if it signal me before(in 30,20 and 10 or 7%. Because now I need to do something instant and I have no time reserve. If I do something ealse maybe something can be lost from pc in this situation.

**Comment by zi007** [comment]
Or maybe design of indicator need to change to see % like in Android phones...

**Comment by tristan957** [comment]
Oh now I get you. Good idea!

**Comment by goniz** [comment]
this needs to be addressed soon...
the current battery indicator is useless in its current state

**for example:**

![example](https://user-images.githubusercontent.com/976803/27741896-3d916ffc-5dbf-11e7-9928-f109e930792d.png)

**Comment by tristan957** [comment]
I believe this is a GNOME issue @goniz . If you have ever used GNOME shell, the same thing happens there. You would have more luck filing a bug against gnome-shell or gnome-control-center, or some other GNOME program. Not sure which.

**Comment by ikeydoherty** [comment]
If we have the icons we can do it, but we don't - so we can't. The spec doesn't specify that level of granularity.

**Comment by goniz** [comment]
What about some kind of alternative percentage view?

**Comment by ikeydoherty** [comment]
Details..?

**Comment by goniz** [comment]
An opt-in feature like on Android:
![screenshot_20170630-211738](https://user-images.githubusercontent.com/976803/27748907-ed852b5a-5dd9-11e7-80ae-7d1b11059b82.png)

**Comment by ikeydoherty** [comment]
Oh. Yeah that's easy doable.

**Comment by ikeydoherty** [comment]
I'll do that tonight

**Comment by goniz** [comment]
> Oh. Yeah that's easy doable

That's why I don't understand how it's never been solved before..

> I'll do that tonight

Thank you for the fast response, looking forward to this!

**Comment by tristan957** [comment]
You and me both

**Comment by ikeydoherty** [comment]
Tada

![screenshot from 2017-06-30 21-52-42](https://user-images.githubusercontent.com/164489/27753773-dc879086-5dde-11e7-8447-d4608e7a1da9.png)

**Comment by goniz** [comment]
Awesome! 
Looking forward to the next sync to stable :)

Thank you

**Comment by ikeydoherty** [comment]
We'll need to do a proper release of Budgie for this stuff @goniz  - lots changed! :)

**Comment by goniz** [comment]
Sounds like a new blog post is approaching @ikeydoherty ;)
Hope it can be released sooner rather than later.

**Comment by ruffson** [comment]
Is there an update when this comes to budgie? Just checked out 10.4 on Ubuntu LTS but was sad not to find it there. Really one of the most-haves for me.

**Comment by ikeydoherty** [comment]
Unless someone makes the icons @ruffson its not gonna happen - said that a couple of times in this thread.

**Comment by ruffson** [comment]
@ikeydoherty I mean the percentage indicator that you showed here.

**Comment by ikeydoherty** [comment]
That's in 10.4. Click the battery icon, and the popup menu shows

**Comment by ruffson** [comment]
Not for me: 
![battery](https://user-images.githubusercontent.com/1185812/30004948-cca0a618-908c-11e7-99f4-934fe4fc48c4.png)

Is this maybe an issue with UbuntuBudgie?

**Comment by fossfreedom** [comment]
![selection_076](https://user-images.githubusercontent.com/996240/30005129-86189a56-90d3-11e7-8fe5-e5873c53957b.jpg)

you should be seeing the above.  Very odd that you are not.

**Comment by ruffson** [comment]
Weird, is there anything additional I have to install?

**Comment by fossfreedom** [comment]
ah - yeah - the "show battery percentage" functionality isn't available in GTK+3.18 distros such as Ubuntu 16.04 - sorry about that.

https://github.com/budgie-desktop/budgie-desktop/blob/10503dd06553ef01fab8cbbd4969b16fb4359400/src/applets/status/PowerIndicator.vala

**Comment by ruffson** [comment]
Oh okay, thank you.

**Comment by fossfreedom** [comment]
@ruffson try my budgie-sysmonitor-applet - edit what is shown to show the "Battery" sensor - percentage battery level.  Open budgie-welcome - software - budgie-applet to install.

code is here - https://github.com/fossfreedom/indicator-sysmonitor
