### ISSUE TITLE
Make Run dialog pinnable to the panel

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#692]
I like the simplicity of the modified run dialog a lot (`ALT+F2`) and use it on a daily basis. Is it possible to make it pinnable to the Budgie panel and show an icon on the panel when it is active? 
Issue on Phabricator: https://dev.solus-project.com/T1190

**Comment by ikeydoherty** [comment]
> modified run dialog

What is modified? I wrote it

The problem you would have is trying to pin it in the first place. It disappears when it loses focus. It also deliberately skips the tasklist + pager. So yes it'd be possible to allow the rundialog to show in the panel area, which isn't the worst thing in the world, but when you right click the icon, it would lose focus, and hide again..

Not sure the best approach for this.

**Comment by baimafeima** [comment]
> What is modified? I wrote it

I didn't know you wrote it from scratch. It looks so much better than the cluttered run dialog versions I see in other distributions :)

> It disappears when it loses focus.

This is actually very nice. Do you think a permanent button/icon in Raven is a better idea?

**Comment by tristan957** [comment]
Not to bring other desktops into this but macOS has the spotlight search as a search icon in the top right. Windows has the cortana launcher/search thing in the taskbar. I think this would best be implemented as a budgie applet that could look like this. Sorry not good at doctoring images so here is a drawing.

![20161027_231748](https://cloud.githubusercontent.com/assets/11936772/19794862/c04fb402-9c9b-11e6-8952-70a684fad4a2.jpg)

Here is a super crude idea of what it could do. As you type the applets move down to make room for Applications that match the search. Thoughts? Seems like it could be hard to implement.

**Comment by ikeydoherty** [comment]
> I didn't know you wrote it from scratch. It looks so much better than the cluttered run dialog versions I see in other distributions :)

Budgie is written from scratch :P It isn't a distribution level thing, the rundialog is a Budgie component

**Comment by ikeydoherty** [comment]
@tristan957 we should be receptive to ideas from other desktops imo - they've had a long time to think about it

**Comment by tristan957** [comment]
@ikeydoherty yea I was just pointing out other implementations that could be possible ideas. Wasn't trashing them :P. Then I added my own idea. So if the world had a currency of ideas, we'd be pretty rich in ideas :)

**Comment by baimafeima** [comment]
> I think this would best be implemented as a budgie applet that could look like this.
I thought about this again and I think I would favour a budgie panel widget implementation with a nice search icon on the panel. When clicking on it, I would still prefer the actual run dialog to be centered, preferably to be centered in the upper middle of the screen, that is, roughtly at the height of how your eyes look at the screen (ergonomic reasons) instead of making it dependent on the actual widget position in the panel.

**Comment by ikeydoherty** [comment]
OK TL;DR this should be a new applet and not in the panel as the run dialog is a separate process.
