### ISSUE TITLE
Flash in live cd/dvd/flash

### ISSUE THREAD

**Issue by zi007** [budgie-desktop/budgie-desktop#694]
If I use live image, I have no possibility to watch something in flash without full system installation.

**Comment by ikeydoherty** [comment]
Sorry this repository is for the Budgie Desktop, not Solus. Solus issues should be reported over @ https://dev.solus-project.com/

However in your case you only need to install `flash-player-nonfree`:

```
sudo eopkg it flash-player-nonfree
```

Also note that the absence of flash in the live image is not a bug, but a security decision. Flash is notorious for security issues, so while we keep it updated in the repo, it will never be in a live image of ours.
