### ISSUE TITLE
Dconf items are not cleaned when removing applets from the panel

### ISSUE THREAD

**Issue by nazar-pc** [budgie-desktop/budgie-desktop#696]
**Operating System**: Ubuntu 17.04
**Budgie version**: Budgie 10.2.8

**The issue encountered**
Applets have few places in dconf related to them. The first one if `/com/solus-project/budgie-panel/applets/{APPLET_UUID}` and the second is `/com/solus-project/budgie-panel/panels/{PANEL_UUID}:applets`.

This issue is more aesthetic, since I prefer to control my system and keep it clean.

When applets are removed, they only seem to be removed from `/com/solus-project/budgie-panel/panels/{PANEL_UUID}:applets`, but applets themselves are still present in `/com/solus-project/budgie-panel/applets/{APPLET_UUID}`.
The same about `budgie-menu` instances, `icon-tasklist` and even panel itself - they are all kept forever, even though not visible in user-facing UI.

**Steps to reproduce the issue**
* add panel
* add few applets to it
* remove all applets
* remove panel itself
* observe garbage under `/com/solus-project/budgie-panel` in dconf-editor

**Comment by ikeydoherty** [comment]
So the issue with removing toplevel panels was resolved. https://github.com/budgie-desktop/budgie-desktop/commit/15c254682400fe6aa4c01cd5bf62acb6df725e94

**Comment by ikeydoherty** [comment]
Yeah I've just tried this, added a new panel at the bottom, added the Budgie Menu, went and ensured I made settings for it by forcing compact mode and launching apps. Then removed the applet, and there
is no trace of it in dconf. You must be running an outdated clone of Budgie

**Comment by nazar-pc** [comment]
I've just did `dconf reset -f "/com/solus-project/budgie-panel/"` and:
* started budgie-panel
* tweaked budgie-menu and spacer back and forth
* configured the rest as on screenshot

![2016-10-30 07-34-40](https://cloud.githubusercontent.com/assets/928965/19834704/92f40fd8-9e73-11e6-9874-92400d223961.png)

And now screenshot from dconf-editor:
![2016-10-30 07-36-16](https://cloud.githubusercontent.com/assets/928965/19834706/982534d2-9e73-11e6-87c1-859ff5634a22.png)

All of the old applets alongside with config of their instances are still present.

I'm using whatever was stable at the moment of 10.2.8 release.

**Comment by ikeydoherty** [comment]
I'm talking about git, not 10.2.8. Also git now has a `budgie-panel --reset --replace&` method to reset the panel

**Comment by nazar-pc** [comment]
OK, I'm closing this then.
Will reopen if it happens in next release.
