### ISSUE TITLE
Panel or Raven Widget: Air Quality Index

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#700]
Operating System: Solus 1.2.1
Budgie version: 10.2.8

As far as I know there is currently no desktop environment (or operating system) which has an applet for hourly (or real-time) air quality index readings. A lot of air monitoring apps already exist for mobile phones but I prefer to get this kind of data onto my desktop. It'll be awesome if Budgie can do that. 

World Air Quality Index: 
- http://waqi.info/
- http://aqicn.org/city/shanghai/
- http://aqicn.org/faq/2015-03-15/air-quality-nowcast-a-beginners-guide/
- http://aqicn.org/sources/

**Comment by fossfreedom** [comment]
Ikey may or may not agree with me ... I think this would be something for an enterprising developer to create and maintain via their own repository rather than as a core component of budgie-desktop.

here is a link which is very useful to help you/someone to create budgie-desktop applets:

 - https://github.com/solus-project/budgie-desktop-examples

**Comment by baimafeima** [comment]
I think an AQI applet is essentially just an extended weather app so it may as well be integrated with an upcoming Budgie weather applet. I have a few more ideas regarding the AQI implementation. In addition to what I have outlined above, I am currently in contact with a company which sells air quality monitoring devices. These devices have Wifi capabilities and what I have in mind is a way to be able to access the data from each device (which could be placed at different locations, in different cities, etc.) through a native Budgie applet. At the moment there is a mobile phone app which can do that, so why shouldn't it be possible for an applet to provide the same kind of data? 

AQI readings are not only relevant for those living in China or India but also for everyone who is interested in keeping an eye on indoor air pollution. I will update this as soon as I have more information. If anyone is interested in helping to develop this, please let me know.

**Comment by JoshStrobl** [comment]
We believe this functionality should be implemented "out of tree" (external to Budgie core) by the community.
