### ISSUE TITLE
When task list becomes too big (>4 applications) the text will come behind the system panel

### ISSUE THREAD

**Issue by erikdubois** [budgie-desktop/budgie-desktop#703]
Solus 1.2.1
Budgie 10.2.8

When task list becomes too big (>4 applications) the text will come behind the system panel
![taskbar_behind_system_tools](https://cloud.githubusercontent.com/assets/10594806/19956400/6d60e7fc-a18c-11e6-90c7-cf634084cbe5.png)
As a test I opened even more applications and you can not click on them any more and they will fall off the taskbar.Tasklist is the applet in raven.
Reported here first : https://dev.solus-project.com/T1431

**Comment by fossfreedom** [comment]
duplicate of this I would suggest: https://github.com/budgie-desktop/budgie-desktop/issues/83

**Comment by ikeydoherty** [comment]
Agreed, closing as dupe, ty
