### ISSUE TITLE
Not all applications launch in the screen center

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#705]
Operating System: Solus 1.2.1
Budgie version: Budgie 10.2.8

Is it possible to force all applications to automatically launch in the middle of the screen? I noticed that some always launch centered such as the Software Center or Hexchat while others such as Transmission or Rhythmbox pop up anywhere on the screen. Some applications seem to "remember" their previous position. Is it possible to override this?

**Comment by ikeydoherty** [comment]
Its not them remembering, they're requesting that the window manager place them in the center of the screen. Solus SC specifically requests it

**Comment by ikeydoherty** [comment]
So there is a way to enforce this:

```
gsettings set org.gnome.mutter center-new-windows true
```

**Comment by JoshStrobl** [comment]
After a short discussion with @ikeydoherty, it's been agreed that the ability to center new windows should be functionality exposed in the new Settings app for the Budgie 11 series, rather than adding more settings into Raven.

**Comment by ikeydoherty** [comment]
Mutter specific Thing's won't be in 11, closing
