### ISSUE TITLE
[Feature Request] Mailnag : Budgie integration 

### ISSUE THREAD

**Issue by 1Claude** [budgie-desktop/budgie-desktop#710]
Mailnag has just landed in unstable.

Infos here : https://dev.solus-project.com/T589

I guess that now all it needs is an applet or some sort of integration in Raven notifications. 

There's a plugin for a couple of desktops environnement : GNOME, Unity, Cinnamon, etc.

**Desktop Integration** : https://github.com/pulb/mailnag#desktop-integration

> By default, Mailnag emits libnotify notifications, which work fine on most desktop environments
> but are visible for a few seconds only. If you like to have a tighter desktop integration
> (e.g. a permanently visible indicator in your top panel) you have to install an appropriate
> extension/plugin for your desktop shell. Currently the following desktop shells are supported:

> GNOME-Shell (GNOME-Shell extension)
> Ubuntu Unity (MessagingMenu plugin)
> Elementary Pantheon (MessagingMenu plugin)
> XFCE (MessagingMenu plugin)
> Cinnamon (Applet by hyOzd)
> 
> Furthermore, I highly recommend GNOME users to install the GOA plugin,
> which makes Mailnag aware of email accounts specified in GNOME Online Accounts.

**Comment by ikeydoherty** [comment]
I don't see why Budgie needs to support this. Its a random external tool. Budgie supports external applets so if someone wants it they're free to write it, as an independent applet from Budgie.

**Comment by 1Claude** [comment]
Maybe you should ask your users if they would like an email applet/plugin
on the top bar or in the Raven notifications before dismissing it.

Regards.


——————
*Claude*

Le 6 novembre 2016 à 12:21:50, Ikey Doherty (notifications@github.com) a
écrit:

I don't see why Budgie needs to support this. Its a random external tool.
Budgie supports external applets so if someone wants it they're free to
write it, as an independent applet from Budgie.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/budgie-desktop/budgie-desktop/issues/710#issuecomment-258695579>,
or mute the thread

**Comment by ikeydoherty** [comment]
That's a very ignorant response, @1Claude. Budgie core is *too big*. We're going through a very public modularisation effort, because the codebase is so monolithic. Adding every edge-case applet into Budgie itself just can't be done anymore.

As I said, Budgie supports *external* applets, and this is the proper way to approach it. Even my new applet, the global menubar one, is external.

**Comment by 1Claude** [comment]
I understand.

I was just redirected here by the guy who packaged Mailnag in Solus. He
told me to ask here if more integration of Mailnag was needed in Budgie.


*Claude*

Le 7 novembre 2016 à 05:42:40, Ikey Doherty (notifications@github.com) a
écrit:
