### ISSUE TITLE
[ Raven setting request ] Window controls on the left

### ISSUE THREAD

**Issue by toudi** [budgie-desktop/budgie-desktop#716]
After looking trough forums [ https://solus-project.com/forums/viewtopic.php?f=14&t=1187&p=6648&hilit=appmenu%3A#p6648 ] I was able to issue the following command:

`dconf write /com/solus-project/budgie-wm/button-layout "'close,maximize,minimize:appmenu'"`

would there be a chance of landing a small toggle to raven, in the 'Windows' section? Just besides 'disable undirect'

Thank you, santa @ikeydoherty :D

**Comment by ikeydoherty** [comment]
It was removed because it doesn't affect CSD applications, the code is simply commented out.

**Comment by Vistaus** [comment]
On my Budgie it does affect CSD applications. Running Budgie master on Arch.

**Comment by ikeydoherty** [comment]
And on *mine*, it does not.

**Comment by toudi** [comment]
right, I can see that Gnome Files are not affected. Damn you, GNOME ;(

![sad](https://media.giphy.com/media/l3rlmIkNNIARa/giphy.gif)

**Comment by ikeydoherty** [comment]
gedit too :(

**Comment by toudi** [comment]
I tried this: `https://ask.fedoraproject.org/en/question/65133/how-to-move-window-buttons-to-the-left-in-cinnamon-for-gtk3-csd-apps/` like so:

`dconf write /org/gnome/desktop/interface/gtk-decoration-layout "'close,minimize,maximize:menu'"`

but gedit didn't react. Is there a chance that the path has changed with GNOME 3.20 or budgie doesn't present itself as org/gnome ?

**Comment by ikeydoherty** [comment]
No - CSD apps are drawn by the apps themselves.  The decoration layout is only applied on app startup too afaik, and this has to be done with xsettings overrides.

**Comment by toudi** [comment]
hmm sorry for necrobumping, but... I was reading solus subreddit today and Joshua mentioned to install gnome-tweak-tool (I wanted to enable date being visible in calendar). And guess what - after I launched gnome-tweak-tool, both files and gedit show controls on the left. Therefore it seems that there is some hacky way to do this :D

**Comment by HEXcube** [comment]
Yay! :smiley: I got left window buttons working on Budgie using this command:

```gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ShellShowsAppMenu': <0>, 'Gtk/ShellShowsMenubar': <1>, 'Gtk/DecorationLayout': <'close,minimize,maximize,menu:'>}"```

I tested on Ubuntu Budgie 17.04 Beta. See [this link](https://xpressubuntu.wordpress.com/2016/03/11/displaying-the-appmenu-in-budgie/) for reference.

**Comment by ikeydoherty** [comment]
Right, we know that works. But what about apps with a *split headerbar* like gedit or gnome-tweak-tool?

**Comment by toudi** [comment]
![gedit-tweak-tool](https://cloud.githubusercontent.com/assets/81148/24864166/9cbce444-1e03-11e7-9eca-5c520881ec99.png)

hope this helps somehow as a proof :D

**Comment by ikeydoherty** [comment]
That's what I wanted to see - thanks! I'm assuming this was a GNOME 3.20 jankiness

**Comment by ikeydoherty** [comment]
Sidenote - lets put the option back into Budgie 10.3

**Comment by HEXcube** [comment]
> I merely opened gnome-tweak-tool and everything worked by itself (the window controls moved to the left by themselves)

That's strange! :open_mouth:  GNOME truly is mysterious :wink:

**Comment by ikeydoherty** [comment]
Now implemented :)
