### ISSUE TITLE
Applet in Ruby possible ?

### ISSUE THREAD

**Issue by Ogromny** [budgie-desktop/budgie-desktop#718]
Hi,
Is it possible to write an Applet in Ruby ?

Sorry for my bad grammar/english I'm French :)
Thanks in advance

**Comment by ikeydoherty** [comment]
Not possible, sorry. We only support what `libpeas` supports :/

**Comment by gsbhasin123** [comment]
@ikeydoherty  https://github.com/mvz/gir_ffi/issues/63, https://github.com/mvz/gir_ffi

**Comment by gsbhasin123** [comment]
Why was my comment deleted????

**Comment by JoshStrobl** [comment]
@gsbhasin123 You're necroing a post from 2017 where it was made quite clear we only support libpeas, which translates to the fact we only support C, Python, and Vala-based applets. In Budgie 11 it'll just be C and Vala-based applets. There are no plans on supporting Ruby.
