### ISSUE TITLE
Make shortcuts to move to left-right workspace editabl

### ISSUE THREAD

**Issue by quesada** [budgie-desktop/budgie-desktop#728]
Solus 1.2.0.5
Budgie 10.2.7 
**The issue encountered**
Please make shortcuts to move to left-right workspace editable.
As it is now, it conflicts with WPS office (uneditable) shortcuts to move a heading up or down in outline mode.

Are there shortcuts to send a window to another workspace?

**Comment by ikeydoherty** [comment]
The shortcuts are configurable, please check Keyboard Shortcuts in GNOME Control Center
