### ISSUE TITLE
Only default keyboard layout on login screen

### ISSUE THREAD

**Issue by fr3dm4n** [budgie-desktop/budgie-desktop#731]
Everytime I login, I have to enter my password as I would use an English locale/keyboard layout. But my selected locale ist `de_DE.utf-8` (in the top right corner)

**Operating System**: 
Solus 1.2.1

**Budgie version**: 
Budgie 10.2.8

**The issue encountered**
On login

**Steps to reproduce the issue**
- Change keyboard layout to a non qwerty-style
- Change your password to use one of the letters/key which are affected by the different keyboard layout
- Logout and good luck to get in again :smile:

**Comment by fr3dm4n** [comment]
got it working with this:
/etc/X11/xorg.conf.d/00-keyboard.conf:
```
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbModel" "pc104"
        #Option "XkbLayout" "de+nodeadkeys"
        Option "XkbLayout" "de"
        Option "XkbVariant" "nodeadkeys"
EndSection
```

I don't know if Budgie is responsible for the entry `Option "XkbLayout" "de+nodeadkeys"` but LightDM will ignore it.

**Comment by hersh-verthun** [comment]
@fr3dm4n You don't need to change your password to replicate this. If your password is in English just select another keyboard layout and logout. Now try to log in. Good luck.

**Comment by ikeydoherty** [comment]
LightDM isn't part of Budgie, sorry. Closing this as it doesn't pertain to Budgie itself

**Comment by hersh-verthun** [comment]
@ikeydoherty Ubuntu uses LightDM but it allows selecting **keyboard layout** at login screen. Could you advise how I can enable this feature - switching keyboard layout at the time of login?

Thanks!

**Comment by fr3dm4n** [comment]
@ikeydoherty You are right, sry again. 

Just btw I found a fix, in case of anyone else will find this ticket:

**/etc/X11/xorg.conf.d/00-keyboard.conf**
````
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbModel" "pc104"
        #Option "XkbLayout" "de+nodeadkeys"
        Option "XkbLayout" "de"
        Option "XkbVariant" "nodeadkeys"
EndSection
```
