### ISSUE TITLE
No HiDPI support at the login screen

### ISSUE THREAD

**Issue by fr3dm4n** [budgie-desktop/budgie-desktop#732]
I am on a 3820x2160 screen. Everything works well, but it looks like gnome-scaling is disable/not available at the login screen

**Operating System**: 
Solus 1.2.1

**Budgie version**: 
Budgie 10.2.8

**Steps to reproduce the issue**

Install Solus 1.2.1 on a HiDPI-Rig an log out

**Comment by fr3dm4n** [comment]
Maybe relevant: Touchpad taping is also disabled. It looks like all Gnome settings would be ignored

**Comment by ikeydoherty** [comment]
Budgie itself provides no greeter, this is down to the LightDM Greeter, which is currently `lightdm-gtk-greeter` in Solus. Gonna have to close it here as its not directly applicable to Budgie itself, sorry. Note that a new greeter *is* planned, though.

**Comment by fr3dm4n** [comment]
My fault, sry. Just getting in touch with solus ecosystem :)

Also here a hint for anyone like me reading this (using Solus at a xps 15 with QHD):
```bash
sudo sed -i -e "s/xft-dpi.*/xft-dpi\=226/g" /usr/share/lightdm/lightdm-gtk-greeter.conf.d/10_solus_default.conf
```

**Comment by feskyde** [comment]
@fr3dm4n since LightDM is stateless, you can add a file in the "normal" greeter configuration (`/etc/lightdm/lightdm-gtk-greeter.conf`) with your changes instead of overwriting those in the default configuration:

```ini
[greeter]
xdpi-stuff=value
```
