### ISSUE TITLE
Workspace Switcher Doesn't Indicate Current Workspace

### ISSUE THREAD

**Issue by SolarLune** [budgie-desktop/budgie-desktop#733]
Hello. 

So the "problem" is that the workspace switcher doesn't indicate the active monitor, it just indicates the active window (which can be confusing when you are focused on a monitor that doesn't have a window on it). 

It'd be nice to have it display the active monitor somehow.

EDIT: A related suggestion would be to display the active workspace number on switch.

**Comment by JoshStrobl** [comment]
Duplicate of #412
