### ISSUE TITLE
Window management and window geometry functionality

### ISSUE THREAD

**Issue by CrisBRM** [budgie-desktop/budgie-desktop#734]
Make it possible to save and edit window geometry, like so: https://userbase.kde.org/File:Kwin-window-attributes.png
Also, it wouldn't hurt to have more macros to snap windows to corners in order to avoid installing third party window managers.

**Comment by tristan957** [comment]
Snapping to corners is a problem with Mutter. The GNOME devs have failed to include it in yet another release. Budgie-wm is scheduled for an upgrade soon though that will take away its dependence on Mutter code

**Comment by ikeydoherty** [comment]
This isn't something we can implement with Mutter, sorry.

**Comment by CrisBRM** [comment]
@ikeydoherty Well, the hotkeys bit will be possible since they're currently rewriting the tiling functionality. https://bugzilla.gnome.org/show_bug.cgi?id=645153

**Comment by orschiro** [comment]
> Are you still going to move away from gnome?

I am not Ikey, but yes:

https://solus-project.com/forums/viewtopic.php?t=3043
