### ISSUE TITLE
Natural scrolling doesn't work

### ISSUE THREAD

**Issue by alseambusher** [budgie-desktop/budgie-desktop#735]
**Operating System**: Ubuntu 16.10
**Budgie version**: Budgie 10.2.8

**The issue encountered**

Natural scrolling doesn't work. 

![screenshot from 2016-11-20 09-04-01](https://cloud.githubusercontent.com/assets/1242542/20464657/4f4d1e08-af00-11e6-96ab-c957175cfe99.png)

![screenshot from 2016-11-20 09-09-01](https://cloud.githubusercontent.com/assets/1242542/20464697/05b52316-af01-11e6-9f9d-f304ac54abd7.png)

 ...

**Comment by ikeydoherty** [comment]
Natural scrolling doesn't work *where* ? I'm highly doubtful this is a Budgie issue given it's using gnome-settings-daemon.

**Comment by alseambusher** [comment]
Hi,
Natural scrolling doesn't work anywhere when I use budgie. Note that it works fine when i use Unity.

**Comment by JoshStrobl** [comment]
Can't reproduce issue on Solus 1.2.1 running Budgie 10.2.8.

**Comment by ikeydoherty** [comment]
Also cannot confirm. "Natural scrolling" inverts the scroll direction when using a mouse, on Solus 1.2.1 using libinput driver (Which is mandatory for GNOME now)

This looks Ubuntu specific.

**Comment by alseambusher** [comment]
It works after installing libinput driver with

`sudo apt-get install xserver-xorg-input-libinput`

Thanks

**Comment by ikeydoherty** [comment]
FWIW that should more than likely be a hard dep of `gnome-control-center` at this point :)

**Comment by VGerris** [comment]
This issue is still present for me on a Lenovo Yoga 2 11 with Ubuntu 17.10 and budgie 10.4. The scrolling works properly in Gnome and Unity (running the default wayland) but does not work in a Budgie session.
Seems Budgie relate to me.

**Comment by fossfreedom** [comment]
Works fine here on Ubuntu Budgie 17.10 and budgie 10.4

**Comment by VGerris** [comment]
If I look under settings, I do not see Touchpad as depicted here:
https://solus-project.com/articles/configuration/configuring-mouse-and-touchpad/en/
but I see Mouse.
I also have the xinput package installed.
Again, this works fine on a Gnome session, not Budgie.
Should I file a new bug for this or can this be reopened?

**Comment by fossfreedom** [comment]
You mentioned Unity - make sure you uninstall the xserver-xorg-input-synaptics package (this will break Unity) - you have to use the xserver-xorg-input-libinput package only.

**Comment by VGerris** [comment]
Hi,

Thank you again for the quick reply :).
I have Unity, Gnome and Budget all installed and switch sometimes.
I found a workaround based on this post:
https://solus-project.com/forums/viewtopic.php?t=9233
I saw this:
synclient -l | grep -i scroll
gave me values 62.
When I did:
synclient HorizScrollDelta=-62 && synclient VertScrollDelta=-62
it worked as expected.

After that I tried to remove xserver-xorg-input-synaptics and that actually made the settings show the settings for touchpad and when I enabled natural scrolling there, it worked too.

So problem solved, but still seems it could use improvement because it's not completely compatible with other desktop sessions?
Thanks for the help, let me know if it makes sense to file a bug :).

**Comment by fossfreedom** [comment]
Its not a budgie issue - this is how GNOME works - your GNOME session is wayland so it defaults to the libinput package.  When using xorg (i.e. budgie) both synaptics and libinput come into play - synaptics (wrongly) takes precedence - at least in ubuntu land.

Remember - Unity is deprecated - it needs to switch to libinput in the same way as other desktops.  Then synaptics can die gracefully.

So no - filing a bug report here is not the right track.  Maybe the "Unity7" boys and girls have plans to replace synaptics with libinput?  Best ask that on the community discourse forum.

**Comment by VGerris** [comment]
Aha, I didn't realise Budgie uses Xorg (and thus not Wayland?).
It feels like 'the supported Ubuntu families' are not coherent when it comes to this driver.
Seems like the synaptics one should probably be marked as a Unity dependency then and as such deprecated when Unity is? I understand that would be an Ubuntu issue, not Budgie.

**Comment by elisboa** [comment]
> It works after installing libinput driver with
> 
> `sudo apt-get install xserver-xorg-input-libinput`
> 
> Thanks

Workerd here. Thank you very much, sir
