### ISSUE TITLE
Crashes in Fedora 25

### ISSUE THREAD

**Issue by TheServerAsterisk** [budgie-desktop/budgie-desktop#738]
If (hopefully when) you plan to create a repo for Fedora 25 users this is the current errors I get using the f24 version. 

Version: budgie-desktop 10.2.8

```
budgie-wm[1930]: The Clutter backend is not a X11 backend
kernel: budgie-wm[1930]: segfault at 10 ip 00007f912ae43033 sp 00007fff7f0d7790 error 4 in libmutter.so.0.0.0[7f912ade9000+127000]
gnome-session-binary[1643]: WARNING: Application 'budgie-wm.desktop' killed by signal 11
```

Also,  `budgie-desktop --debug` Produced the following warnings I'll try to determine the correct way for installing nvidia drivers for f25 since it seems that it may have changed. 

```
hardware acceleration check failed: Child process exited with code 1
No protocol specified
Unable to init server: Could not connect: Connection refused
```
There was also a core dump that I'll look at a little later.

**Comment by niyasc** [comment]
Incompatibility with Wayland may be a cause of this issue. A discussion on wayland was going on issue #553

**Comment by alunux** [comment]
I grab SRPM from OBS repo and rebuild it for Fedora 25. It's running smooth on my Fedora 25.

**Comment by digitaldissent** [comment]
Alunux I am using your Budgie repo and it has worked great on F25 but with the latest update whenever it lauches the pop up asking for the root password it is a small solid box that does nothing.

**Comment by alunux** [comment]
@digitaldissent I had updated the copr repo. Can you update and test it?

**Comment by JoshStrobl** [comment]
Please validate if this is still an issue.

**Comment by alunux** [comment]
@JoshStrobl you can close this issue. The latest Budgie has worked great on Fedora 24, 25, and 26 Alpha (tested by me).
