### ISSUE TITLE
Terminal Commands Widget

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#745]
It would be great to have a _Terminal Commands Widget_. A drop down menu could reveal the most important and most used terminal commands and clicking one of them would automatically launch the terminal with the appropriate command. Next to each command there could be a short explanation of what it is for.

**Comment by ikeydoherty** [comment]
Not inside Budgie sorry, it's not an core feature. I don't want to bloat up the core offering. With that said someone should consider implementing this as an out of tree applet for Budgie, I'm sure it wouldn't be too difficult

**Comment by ikeydoherty** [comment]
Maybe we can centralise a "wanted widgets" in the budgie 11 roadmap? given our move to modularisation something like this is more doable

**Comment by JoshStrobl** [comment]
We believe this functionality should be implemented "out of tree" (external to Budgie core) by the community.

> Maybe we can centralise a "wanted widgets" in the budgie 11 roadmap?

A "wanted widgets" section on the Budgie website may provide an entry point for individuals to get involved in expanding the ecosystem. Filed an issue at budgie-desktop/budgie-site#8
