### ISSUE TITLE
Battery Applet stays red

### ISSUE THREAD

**Issue by aldoiljazi** [budgie-desktop/budgie-desktop#746]
Basically, the first time that the battery of the laptop goes low, the battery applet goes red.

After I plug the laptop to the power source, the color of the applet stays red, no matter what I do.

![zlye3id](https://cloud.githubusercontent.com/assets/12599754/20652314/86b9f6c2-b4ff-11e6-832c-43ece6828efe.png)

**Comment by JannikHa** [comment]
Hey there, pease specify the **Operating System** and **Budgie Version**  you're using.

**Comment by aldoiljazi** [comment]
**Operating System:** Solus with latest updates as of today.

**Budgie Version:** 10.2.8-107

**Comment by Vistaus** [comment]
Same problem here. Also using Solus with Budgie 10.2.8 It started happening a few days ago.

**Comment by aldoiljazi** [comment]
For me it is fixed. Don't know how. :laughing:

**Comment by cablespaghetti** [comment]
Still broken for me. Anyone else got the issue?

**Comment by ikeydoherty** [comment]
This is fixed in upower updates in Solus unstable. It'll arrive in next update batch
