### ISSUE TITLE
Removed budgie, still getting an extra dock underneath the unity dock

### ISSUE THREAD

**Issue by trivett** [budgie-desktop/budgie-desktop#748]
After installing I rebooted and tried to open with the regular ubuntu desktop that I had already set up, and the budgie dock is appearing underneath or on top of the Unity dock. The login screen is also changed to the budgie one. I've also noticed that startup times are also dramatically slower. Can anyone help me get rid of this without doing a fresh install? 

Looks like I am not the only one https://askubuntu.com/questions/851793/how-do-i-switch-between-unity-and-budgie-desktop-environments-in-ubuntu-16-04

As for versions, since I already purged everything I could think of I have none to report. I am using Ubuntu 16.10.

**Comment by ikeydoherty** [comment]
This is a package/distro issue, not a Budgie issue. Budgie doesn't have a dock, Budgie has panels.
Ubuntu Budgie (Budgie Remix) uses Plank, so make sure that is gone.
Also ensure `budgie-desktop` and `budgie-desktop-environment` packages are removed.
