### ISSUE TITLE
Window Button Stay Highlighted After Workspace Change

### ISSUE THREAD

**Issue by Uks2** [budgie-desktop/budgie-desktop#749]
**Operating System**: Ubutnu Budgie Remix 16.04
**Budgie version**: Budgie 10.2.8

**The issue encountered**

If the active workspace is changed using keyboard shortcuts (ctrl + alt + left / right) while the mouse is hovering above a window button (i.e. minimise, maximise, close), and the mouse is then moved outside of that windows area before the active workspace is changed back, the button stays highlighted until the mouse re-enters the window in question.

**Steps to reproduce the issue**

Select a Gtk theme that highlights window button when they are being hovered over.
Hover mouse over the minimize, maximize or close button and while it's there change workspace by pressing ctrl + alt + left / right. Then move the mouse outside of where screen space occupied by the window in question and change the workspace back, either using the keyboard shortcut or the buttons in the panel and the highlighted button will remain so until the mouse is returned to that window.

**Comment by ikeydoherty** [comment]
Closing as dead.
