### ISSUE TITLE
Right click on window titles doesn't _always_ register

### ISSUE THREAD

**Issue by CrisBRM** [budgie-desktop/budgie-desktop#751]
Title. Sometimes I have to click up to 7 times before I get the context menu. 
Originally I thought there was no such menu and was going to request that you introduce the 'always on top' feature, only to find out that it already exists but right clicks don't always register.

OS is Solus, so I'm on budgie 10.2.8.

**Comment by fossfreedom** [comment]
how odd - I don't see this in Ubuntu.  very strange observation :/

Any window - or limited to specific applications - e.g. CSD based applications, QT based etc ?

**Comment by CrisBRM** [comment]
Firefox and the gnome terminal.

**Comment by fossfreedom** [comment]
ah - good - yes - can reproduce in ubuntu with firefox and gnome-terminal.

**Comment by tristan957** [comment]
This reproducible on Chrome as well fyi

**Comment by ikeydoherty** [comment]
FWIW it's not "odd" as such - we really shouldn't be using GTK in the window manager. I'll try to workaround it for 10.2.9

**Comment by fa7ad** [comment]
Same here, Budgie 10.2.8 on Arch

**Comment by ikeydoherty** [comment]
So this was changed in 10.2.9, basically we register a timeout and after 100ms we spawn it. Mutter will ungrab the key and cancel the event if you hold down right click for a long press. Normal right clicks now work.
