### ISSUE TITLE
settings app for budgie

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#752]
... couldn't find the degnomification issue ...

https://medium.com/elementaryos/making-system-settings-access-a-cross-desktop-feature-c98eadcaea30#.hqv9ylqi8

In light of the tight coupling of gnome-control-center with GNOME - is what the elementary guys are doing to replace that something that budgie-desktop is interested in (in terms of direction/code reuse etc?

**Comment by ikeydoherty** [comment]
A Control Center is already planned for Budgie (see the `info/` repo) - I don't need elementary apps for this :)

**Comment by asonix** [comment]
I don't think @fossfreedom was proposing using Switchboard. Instead, I think they were encouraging the adoption of Elementary OS's proposed settings URL scheme in budgie-settings to allow cross-platform applications to feel more native.

**Comment by ikeydoherty** [comment]
Sure we can support a URI scheme

> (in terms of direction/code reuse etc?

Is what I won't be doing, though :)
