### ISSUE TITLE
When i launch Kodi 17 it crashes the budgie panel.

### ISSUE THREAD

**Issue by virtuae** [budgie-desktop/budgie-desktop#753]
When i launch Kodi 17.0 it crashes the budgie panel. Also raven does not work anymore. 
I'm using Solus 1.2.1 Shannon with the latest budgie 10.2.8.

**The issue encountered**

 ...

**Steps to reproduce the issue**

 ...

**Comment by tristan957** [comment]
I do not have this problem fyi. Same specs as you

**Comment by ikeydoherty** [comment]
Raven is part of the panel. Is the `budgie-panel` process still running after this happens?

`ps aux | grep budgie-panel`

**Comment by virtuae** [comment]
Yes. But I forgot to tell an important thing, so now I will relate all the steps as I did, and below you can see the system report.

1. login; 
2. open Kodi and start a movie; 
3. connect the notebook to my tv via HDMI; 
4. Super Key+P to send the image only to TV (okay); 
5. noted that the audio continued in the notebook, than I pressed Super key to reach panel and Raven (no response); 
6. minimised Kodi to reach Panel and Raven (okay); 
7. Could not toggle audio to TV (Raven did not accept it - it tooks audio back to internal speaker instantaneously); 
8. Super Key+P to return to screen to notebook - Kodi crashed video, and the screen gone washed; 
7. Alt+F4 closed Kodi, and gave up.

marcelo@vaio ~ $ ps aux | grep budgie-panel
marcelo    927  1.7  0.5 1065732 46656 ?       Sl   16:39   0:14 budgie-panel
marcelo   2177  0.0  0.0 120052  2368 pts/0    S+   16:52   0:00 grep budgie-panel

marcelo@vaio ~ $ grep -i chipset /var/log/Xorg.0.log
[    19.946] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
[    19.946] (II) RADEON: Driver for ATI/AMD Radeon chipsets:
[    19.949] (II) VESA: driver for VESA chipsets: vesa
[    20.169] (--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 3000
[    20.200] (--) RADEON(G0): Chipset: "CAICOS" (ChipID = 0x6760)

**Comment by mitchellurgero** [comment]
Super key might not work in applications that are fullscreen / take control of X server. Try using Kodi in a different tty?

**Comment by virtuae** [comment]
Ok, thanks.
