### ISSUE TITLE
Undo widget removal

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#754]
Operating System: Solus 1.2.1
Budgie version: Budgie 10.2.8

To save myself the typing, a quote from this site:
http://www.ocsmag.com/2015/03/21/some-cool-plasma-tips-and-tricks/
"If you feel like customizing your desktop, you may want to rearrange the position of existing widgets, add some new and delete existing ones. Sometimes, the finger is faster than regret, and should that happen, you don’t want to spend time re-adding the old thingie and tweaking it to your liking. Plasma comes with the undo function, allowing you to easily restore widgets. I believe this should be extended across the board, allowing users to preserve their settings and layout periodically, automatically, and then let them switch back to older configurations."
Could we have this functionality for Budgie too?

**Comment by ikeydoherty** [comment]
No.  Instead we can have a mechanism for saving layouts.
