### ISSUE TITLE
unknown coverart icon on top of instead of behind song and display options

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#757]
*Operating System**: e.g. ubuntu 16.04 and 16.10
**Budgie version**: i.e. Budgie 10.2.8 and budgie 10.2.9

**The issue encountered**
Not using the inbuilt theme option - an unknown cover from any media player (e.g. rhythmbox or vlc) displays like this:

https://github.com/UbuntuBudgie/budgie-desktop-environment/issues/38

using arc-darker theme

![](https://cloud.githubusercontent.com/assets/19637593/21243068/7dc49178-c317-11e6-910c-97884861429a.png)

Using the inbuilt theme the icon is correctly behind everything - the song details and play controls are correctly overlayed with the icon.

Thoughts?

**Comment by recke96** [comment]
Same issue on Manjaro 16.10 with vlc
![raven-bug](https://cloud.githubusercontent.com/assets/7427710/22974145/528cc422-f381-11e6-9250-1ca6cf761e27.png)

**Comment by ikeydoherty** [comment]
Not a bug, basically. It's still in the same position, but your FG colours are mangling with the symbolic icon colour, so it *looks* like its on top. It's not, it's behind.

The point here is, you disable the internal theming... it has no theming. You should only use the option when your GTK theme provides complete Budgie theming. In the case of Arc styling, it's internal to Budgie, not the external Arc theme. Ergo, if you use Arc theme, you shouldn't be disabling internal theming.

**Comment by fossfreedom** [comment]
k - ta. makes sense.
