### ISSUE TITLE
Budgie Menu and User Indicator Menu appear too high

### ISSUE THREAD

**Issue by TheKoopaKingdom** [budgie-desktop/budgie-desktop#758]
**Operating System**: x86_64 Linux 4.8.13-1-ARCH (Arch Linux)
**Budgie version**: 10.2.9

When I click on the Budgie Menu icon or press Super, or click on the User Indicator Icon, their menus appear at the top of the screen before being moved to the bottom. This only happens when the Budgie panel is at the bottom of the screen.

[Here's a screenshot of me clicking on the menu icon and the menu being too high](http://i.imgur.com/wpL5Rr8.png), [here's a screenshot of it correcting itself a second later](http://i.imgur.com/8rMk1DS.png), and [these are my settings](http://i.imgur.com/9K2M1y9.png).

Steps to reproduce:
 - Move the Budgie panel to the bottom
 - Open the Budgie menu or User Indicator Menu

In my testing, this issue still occurs when I change the positioning of my second monitor, unplug it altogether, or change my theme from Breeze Dark to Adwaita.

**Comment by JannikHa** [comment]
Already a known issue #634 .

**Comment by ikeydoherty** [comment]
Yeah its a duplicate - we're fixing it in Budgie 11 where we'll drop popovers
