### ISSUE TITLE
Date applet highlights current day number on any month

### ISSUE THREAD

**Issue by nazar-pc** [budgie-desktop/budgie-desktop#759]
**Operating System**: Ubuntu 17.04
**Budgie version**: 10.2.9

**Steps to reproduce the issue**
1. Open Raven
2. Today is December 29, it is highlighted
3. Switch to November, September, January - any month

**Expected result:**
On months other than current December no days should be highlighted.

**Actual result:**
November 29, September 29, January 29 - all highlighted.

**Comment by Vistaus** [comment]
Not sure if there might be a design reason for this, but I can confirm this issue on Solus 1.2.1 with Budgie 10.2.9 as well.

**Comment by ianmcxa** [comment]
Confirmed on budgie-desktop 10.2.9 Arch Linux
