### ISSUE TITLE
Icon Shift?

### ISSUE THREAD

**Issue by Hacksaurus** [budgie-desktop/budgie-desktop#766]
I am not 100% this is caused by Budgie or GNOME it self, but you can kind that there is a big gap between the Blueman applet and the nm-applet... I seen the problem once is XFCE, but fixed itself after logging out and back in...
![screenshot_2017-01-03_19-19-34](https://cloud.githubusercontent.com/assets/24832107/21630807/95d2b444-d1e9-11e6-929d-a54a107e595d.png)

(Also have you fixed being able to change cursor and lock screen... From my understanding, its a no...)

**Comment by JoshStrobl** [comment]
Should be resolved as of 10.3. Feel free to reopen if issue remains.

**Comment by ikeydoherty** [comment]
Yeah new natray should help with this

**Comment by Hacksaurus** [comment]
Well I still see the gap... But it doesn't really bother me because I have so much stuff in my systray now...
![screenshot_2017-04-28_09-07-46](https://cloud.githubusercontent.com/assets/24832107/25537139/284abde6-2bf2-11e7-8181-e0951276f5fc.png)
