### ISSUE TITLE
Menu not closing?

### ISSUE THREAD

**Issue by Hacksaurus** [budgie-desktop/budgie-desktop#767]
Another issue... You can see that when I press the `Super Key` that it opens the menu. Yay! But when I press it again... it opens it up... again... and again... and again... Until you press `ESC`
Is this a GNOME thing? Or is it a true issue...
![budgie menu not closing](https://cloud.githubusercontent.com/assets/24832107/21631156/0e870d88-d1ed-11e6-9c16-075c4b2dd811.gif)

Don't worry about how there is some cut up sections of the menu, that's just my screen capture... (I use a Chromebook for Linux)

~~(Also what do I have to download for settings, such as extra keybindings for GNOME..)~~

**Comment by JannikHa** [comment]
Having the same issue for quite a time. This happens on Arch Linux with the latest Budgie-Desktop-Git, so V10.2.9 (If I am not mistaken). I believe this occurred since the relase of Gnome 3.22.

**Comment by fossfreedom** [comment]
this sounds very similar - or possible the same as this issue https://github.com/budgie-desktop/budgie-desktop/issues/605

**Comment by Hacksaurus** [comment]
It seems that using `Super + S`, sort of solves the problem... I'm not sure 100% why, and you have to keep holding the Super button and press "S" 2 times, and then you have full control of the menu..

**Comment by ikeydoherty** [comment]
Current Budgie menu is utterly buggered due to the use of popovers, we're dropping GtkPopover in Budgie 11 (first item..) - check https://github.com/ikeydoherty/ui-tests for the experimental work.

Closing as dupe per @fossfreedom's advice.

**Comment by Hacksaurus** [comment]
Ah I see... Budgie still needs a lot of work!
Can't wait for 11!
