### ISSUE TITLE
[Feature] select video output from Raven

### ISSUE THREAD

**Issue by Redneckita** [budgie-desktop/budgie-desktop#768]
The audio output switch on Raven is really clever, how about selecting screens too? That's handy for people with laptops who regularly use external monitors or desktop users that need to switch monitors often.

**Comment by Hacksaurus** [comment]
@Redneckita Thats actually not a bad idea... But I think they are going to only limit themselves to stuff in the status indicator... I frequently use monitors too, so being able to configure them would be pretty neato!

**Comment by JoshStrobl** [comment]
We believe this functionality should be implemented "out of tree" (external to Budgie core) by the community.
