### ISSUE TITLE
Panel doesn't like the Super Button

### ISSUE THREAD

**Issue by Hacksaurus** [budgie-desktop/budgie-desktop#770]
Problem with the Super Button... Again...

Steps to Reproduce:
1. Click the Raven Sidebar Control
2. Press the Super Button
3. Panel Disappears!
(Usually works after 1-2 tries)

![panel doesn t like the super button](https://cloud.githubusercontent.com/assets/24832107/21708089/e228aa96-d389-11e6-8d27-587e99491330.gif)

**Comment by fossfreedom** [comment]
this is a duplicate of this - https://github.com/budgie-desktop/budgie-desktop/issues/726

**Comment by Hacksaurus** [comment]
Thanks, Closing this
