### ISSUE TITLE
[Feature] Favorite Apps as Raven Applet

### ISSUE THREAD

**Issue by Solarunit** [budgie-desktop/budgie-desktop#771]
It would be nice to have a Favorite Apps Applet. You can pin apps there from main menu using D&D or context menu. 

![Alt Text](http://i.imgur.com/Loe8Ii4.png)

**Comment by ikeydoherty** [comment]
Seems an odd place to have them, given that you can pin icons to the tasklist, and you have a menu

**Comment by Solarunit** [comment]
> you can pin icons to the tasklist

Yes, but only icons without text. List view has more advantages.

> and you have a menu

Right now it doesn't have "Favorites" category.  And i think the most important - how many clicks you need in order to open Favorites apps list. 
With using hot edges/corners to open Raven - 1 click max.
Raven can store a big list of apps compared to main menu.

**Comment by ikeydoherty** [comment]
Right the menu doesn't _currently_ have favourites - doesn't mean it wouldn't gain them :]

**Comment by Solarunit** [comment]
> Right the menu doesn't currently have favourites - doesn't mean it wouldn't gain them :]

How will it be look like? Like a category or more like windows 7 start menu? =)

> Seems an odd place to have them

Why? People often put their docks (plank) to the left|right edge of the screen. I think Raven side panel is a perfect place for favorite apps. There are even similar 3rd party software for windows e.g. True Launch Bar:
https://www.youtube.com/watch?v=VPgNvgVrjs8

**Comment by JoshStrobl** [comment]
We believe this functionality should be implemented "out of tree" (external to Budgie core) by the community.
