### ISSUE TITLE
"Starting Up <APPLICATION>"

### ISSUE THREAD

**Issue by Hacksaurus** [budgie-desktop/budgie-desktop#772]
I'm not sure if this is an issue or a a feature, so I just wanted to ask... 
You can see that when I start up a lot of programs that I didn't select in autostart, there will be another dialog popup, that I can't interact with, that says "Starting up <APPLICATION>"

This also has an affect on the program, because there will be the loading circle for at least a couple of seconds.

![starting up application](https://cloud.githubusercontent.com/assets/24832107/21752988/80443bfa-d597-11e6-85fe-22c09fa7da3f.gif)

You can see that the loading circle stays with me for a good 10 seconds until it disappears...
Is this a bug?

**Comment by ikeydoherty** [comment]
The current "classic" task indicator will be removed in Budgie 11. The idea is that we'll "merge" this with the icon tasklist, and make the icon tasklist configurable, so that you can disable text, etc.

Right now the "classic" tasklist is actually provided by "WnckTasklist", which is basically completely opaque and we can't alter

**Comment by Hacksaurus** [comment]
@ikeydoherty Ok thanks!
*More waiting*

![image](https://cloud.githubusercontent.com/assets/24832107/21753499/881e5cc8-d5a3-11e6-8ee3-8cc1c9344f6c.png)

**Comment by Hacksaurus** [comment]
Also @ikeydoherty Will custom cursors also be added in Budgie 11?

**Comment by ikeydoherty** [comment]
Complaining about waiting is not going to make me do it any faster, quite the opposite. We have a roadmap in place.

As for custom cursors, you've been able to change cursor themes in Budgie for a very long time (since budgie 8 or even older)

**Comment by Hacksaurus** [comment]
@ikeydoherty Hmmm... Ok I'll see about that... The only cursor that I can select is "Adwaita"
And I only mean waiting as a joke! I just feel like everything that will be in 11 is everything that I want in Budgie!
But thanks anyways!

**Comment by ikeydoherty** [comment]
Budgie itself doesn't provide the cursor themes :) Solus uses 'breeze' for example, check your distro repos, you might be surprised :)

**Comment by Hacksaurus** [comment]
@ikeydoherty No I have installed other cursor themes... `xcursor-dmz` is one of them... But I think its not working because I installed from AUR... idk

**Comment by JannikHa** [comment]
@Hacksaurus It really **should** work. I don't know about the AUR package, but for example, I installed xcursor-vanilla-dmz and it worked, how it is supposed to.

Maybe it's a broken AUR package or something, Budgie itself doesn't have an issue regarding cursor themes :P

**Comment by Hacksaurus** [comment]
@JannikHa Oh `vanilla` I just did `xcursor-dmz`
Ok Ill try that!

**Comment by JannikHa** [comment]
@Hacksaurus Nah you got me wrong.

The AUR package *xcursor-dmz* **does** exist but it may be broken or something.

With the **xcursor-vanilla-dmz** (Arch Package, not AUR) example I just wanted to point out that cursor themes on budgie work in general :P

**Comment by Hacksaurus** [comment]
Yeah, Thanks again! Also, (I should be opening another issue but it might not be) But you know when you open a link? or use the system tray to open it? Sometimes it opens it, but does not "popup" Like it opens, but then you have to click the minimized application to open it again... How do i make it so that it does "popup"? (I think it may have something to do with "unredirect")
