### ISSUE TITLE
Move to option in Nautilus produces an error when moving a file located on the Desktop

### ISSUE THREAD

**Issue by tristan957** [budgie-desktop/budgie-desktop#773]
**Operating System**: e.g. Solus current as of 1/12/17
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**
If I have a file on the desktop that I then right click and click the menu option "Move to", Nautilus opens with an error dialog stating that "The folder contents could not be displayed. The specified location is not supported". For reference I have icons on the desktop enabled.
 ...

**Steps to reproduce the issue**
Move a file to the desktop. Right click the file. Click "Move to"
 ...

**Comment by ikeydoherty** [comment]
I'm confused - Nautilus isn't part of Budgie :/ Nor are the desktop icons (also Nautilus)

**Comment by ikeydoherty** [comment]
(BTW I dont want this issue closed, just expressing my confusion)

**Comment by tristan957** [comment]
I know :/. Should I create a bug report on Nautilus bugzilla? I was maybe thinking this was Solus specific but maybe not

**Comment by tristan957** [comment]
Link to relevant Bugzilla report for nautilus: https://bugzilla.gnome.org/show_bug.cgi?id=777202

**Comment by tristan957** [comment]
My bug was marked as a duplicate. Here is the resolved bug report: https://bugzilla.gnome.org/show_bug.cgi?id=777201

**Comment by tristan957** [comment]
Feel free to close the issue @ikey
