### ISSUE TITLE
Lock Screen MAJOR Security Flaw

### ISSUE THREAD

**Issue by mitchellurgero** [budgie-desktop/budgie-desktop#774]
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	2017.01.01.0
Codename:	shannon
Budgie Version: 10.2.9

Issue: When a VGA monitor is plugged in, and the lock screen is active. Unplugging the Monitor temporarily UNLOCKS the desktop. The attacker CANNOT type, but can ACTIVELY browse The currently locked users files and even open applications. This is a huge security issue as settings can be changed, as well as private documents can be viewed. This is repeatable as well. Plugging in a VGA monitor does NOT have this issue. I do not know where to get LOGS for this to give to devs, so if someone can walk me through getting them..

**Comment by ikeydoherty** [comment]
OK so this isn't the way to report security issues, and could do with significantly less drama and the-end-is-nigh styling. It's also not Budgie related as Budgie doesn't _have_ a lockscreen.  It's therefore whichever lockscreen you then use on Solus (gnome-screensaver or mate-screensaver.)

Please re-report onto the *Solus* infra, where it will then be dealt with appropriately.

**Comment by ikeydoherty** [comment]
Sidenote: This is not an acknowledgement of an issue, this is just the enforcement of responsible processes.
