### ISSUE TITLE
[Arch Linux] Error installing budgie-desktop-git

### ISSUE THREAD

**Issue by JannikHa** [budgie-desktop/budgie-desktop#775]
**Operating System**: Arch Linux
**Budgie version**: 10.2.9

**The issue encountered:**

After the latest (tiny) [commit](https://github.com/budgie-desktop/budgie-desktop/commit/ca8af4609873b6fc9f9822670faed4bd9c6145d2), problems occur when trying to (re-)install budgie-desktop.

**Error output:** (When trying to build *budgie-desktop-git*)

make: *** [Makefile:537: check-recursive] Error 1
make: Target 'check' not remade because of errors.
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Makepkg was unable to build budgie-desktop-git.
==> Restart building budgie-desktop-git ? [y/N]
==> -------------------------------------------
==> 

**Steps to reproduce the issue:**

    yes | yaourt -S budgie-desktop-git

**Comment by ikeydoherty** [comment]
I can't reproduce those cuz I don't use Arch :P Lemme take a dig quick

**Comment by ikeydoherty** [comment]
Compiles here - I need more of your build log please.
Also, `master` is the development branch, I've said this before but PKGBUILDs really should stop following master, its not reproducible.

**Comment by JannikHa** [comment]
I don't know what part of the log you're after exactly, heres the entire log written into a file :P

    yes | yaourt -S budgie-desktop-git &> log.txt

[log.txt](https://github.com/budgie-desktop/budgie-desktop/files/714980/log.txt)

I guess I'm eventually going to fall back to the regular **budgie-desktop** package, the non-git version.
Anyways, thanks for having a look at this! :)

**Comment by ikeydoherty** [comment]
I think the Budgie package is actually outdated so fwiw i dont blame you

**Comment by ikeydoherty** [comment]
Why is it running make check.. wtf.
Anyway, this is the error:

```
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.

src/panel/applets/places-indicator/MountHelper.c
```

**Comment by Flat** [comment]
If I recall wasn't this an issue before? (The running checks that is).

Anyway, arch  users can still build the package fine by editing the PKGBUILD, adding ```BUILDENV+=('!check')``` to their makepkg.conf or running ```makepkg --nocheck```

If budgie-desktop doesn't support tests for master builds I'll leave a comment on the aur and see if the maintainer will remove the check() block.

**Comment by ikeydoherty** [comment]
You're looking at it from the wrong angle. It's a development branch, you can't expect it to package and be stable. That's what tags and sha refs are for :P Anyway, Budgie doesn't *have* a test suite, this one comes from intltool, and is part of a larger distcheck failure due to the untranslated file. It can be fixed.

**Comment by Flat** [comment]
Sorry, I guess that's what I was trying to see is if Budgie had a test suite itself. I should have phrased that better.

 I also understand what you're saying, but I believe most people that install the git packages understand that they aren't release quality and it is the latest code from the repository. A lot of people just want the latest as long as it compiles :)

**Comment by JannikHa** [comment]
Well, might be a bit unusual, especially after reading @Flat 's idea, but I simply removed the **check()** function in the PKGBUILD when yaourt asked me to in the beginning. After doing that, the remaining installation went smoothly, without any errors.

Thanks for your time @ikeydoherty @Flat ! :)

- As for me, you can close this issue since it's "fixed" :P

PS: @Flat I'm really not a bleeding edge kind of guy, but the only alternative from the git package is the outdated [package](https://www.archlinux.org/packages/community/x86_64/budgie-desktop/) x).
Won't matter anyways since in about 1-2 weeks, I'm switching to Solus entirely.

**Comment by ikeydoherty** [comment]
>  A lot of people just want the latest as long as it compiles :)

Exactly. Which puts pressure on me to not have a development branch :P

**Comment by Flat** [comment]
>PS: @Flat I'm really not a bleeding edge kind of guy, but the only alternative from the git package is the outdated package x).
Won't matter anyways since in about 1-2 weeks, I'm switching to Solus entirely.

Does look like that's a little behind, but cheers hope you enjoy Solus.

>>A lot of people just want the latest as long as it compiles :)

>Exactly. Which puts pressure on me to not have a development branch :P

Touche.  :smile:

**Comment by ikeydoherty** [comment]
> Does look like that's a little behind

https://github.com/budgie-desktop/budgie-desktop/compare/v10.2.8...v10.2.9

  298 changed files  with 4,776 additions and 2,289 deletions.

**Comment by ikeydoherty** [comment]
^ Try now

**Comment by Flat** [comment]
```make -k check``` completes successfully for me.

**Comment by ikeydoherty** [comment]
Awesome :) Ofc now you *have* to stay on master xD

**Comment by Flat** [comment]
I've used master for budgie from the beginning :) :heart:

**Comment by ikeydoherty** [comment]
so can close?

**Comment by Flat** [comment]
As far as I'm concerned yes, everything works on my end; I'm not the one that opened the issue though.

I suppose this also means JannikHa agrees :)
>As for me, you can close this issue since it's "fixed" :P

**Comment by JannikHa** [comment]
Yes, everythings fine on my end aswell now, thanks for your guys help :)

Closing it now.
