### ISSUE TITLE
No icons in Right Click

### ISSUE THREAD

**Issue by Hacksaurus** [budgie-desktop/budgie-desktop#776]
Hello its me again, asking about icons...
So I was wondering if this is a feature of just a bug, because I'm not really sure...
When you right click something it shows you options of what you can do and usually they have icons according to what they do... Now I am OK without having this, but sometimes I do need it...
Here in `xfce4-clipman`, it needs to icon in order to show which thing I am selecting!

![screenshot_2017-01-21_08-04-49](https://cloud.githubusercontent.com/assets/24832107/22175752/5cca6fa0-dfb0-11e6-8b68-3da708e5b1af.png)

**Comment by JannikHa** [comment]
Please always submit the operating system and the Budgie Desktop version you're using when you submit an issue.

Regarding your problem, if it even is a bug, it would definitely be a nautilus bug, but I don't think so since the rightclick options in Nautilus have never had that kind of thing. Correct me if I'm wrong though :P

**Comment by Hacksaurus** [comment]
I am running Arch Linux and my Budgie version is 10.28
And I don't think this is a Nautilus bug, because if I right click **anything** there is no icons...
![screenshot_2017-01-21_08-58-30](https://cloud.githubusercontent.com/assets/24832107/22176124/f7d8a154-dfb7-11e6-89fc-04398d54ab6f.png)
![screenshot_2017-01-21_08-58-15](https://cloud.githubusercontent.com/assets/24832107/22176127/fc3a4d24-dfb7-11e6-925f-10ed5b7eb589.png)

**Comment by Hacksaurus** [comment]
@JannikHa Any suggestions?

**Comment by JannikHa** [comment]
What File Manager were you using when you made those screenshots? I first though you'd be using the regular Budgie Desktop setup.

**Comment by Hacksaurus** [comment]
I was using Thunar in those screenshots... The first 2 screenshots were from Budgie, and the other 2 were from XFCE, sorry that I didn't point that out clearly

**Comment by JannikHa** [comment]
Okay now I got your problem. Right, but that's definitely not a **Budgie Bug**. You can't install and use custom stuff like parts of **xfce4** and expect it to work on a budgie session. Budgie uses **Nautilus** to manage File and the Desktop.

Your problem however could be related to the type of session you're in. Budgie has a gnome-session, xfce4 has a xfce4-session and both have other programs/daemons running in background which could cause this problem.

I'm not very familiar with xfce4, neither is thjs the right place to talk about,but maybe try this:

    $ xfdesktop &

Anyways, Thunar is **not** a part of Budgie, thus it is not a Budgie bug.

**Comment by Hacksaurus** [comment]
I don't think you are getting my point... First of all doing `xfdesktop &`, didn't really do anything except change my background (Which is actually kind of neat)
What I am talking about is the **icons** that are part of the right-click; you can see that in Budgie there is no icons when you right click while in XFCE, that there is...

**Comment by fossfreedom** [comment]
GNOME dropped support for icons against menu options a long-time ago.

https://bugzilla.gnome.org/show_bug.cgi?id=583352
https://bugzilla.gnome.org/show_bug.cgi?id=557469

for quite a while you could enable it via a dconf setting but I think that has been stripped a few GTK versions ago.

**Comment by Hacksaurus** [comment]
Ahh I c... Thanks for the insight @fossfreedom!
Closing this thread...

**Comment by Hacksaurus** [comment]
Fixed it!

![screenshot_2017-01-22_16-17-56](https://cloud.githubusercontent.com/assets/24832107/22187606/5face252-e0be-11e6-9932-97b772af3f93.png)
![screenshot_2017-01-22_16-17-34](https://cloud.githubusercontent.com/assets/24832107/22187611/6f537982-e0be-11e6-9d0f-dde7a083c0bb.png)
![screenshot_2017-01-22_16-17-21](https://cloud.githubusercontent.com/assets/24832107/22187612/73148976-e0be-11e6-84d3-a1e7ff7c0b68.png)
