### ISSUE TITLE
Start menu not opening in the right spot.

### ISSUE THREAD

**Issue by kevinarefunny** [budgie-desktop/budgie-desktop#783]
**Operating System**: Solus 2017.01.01.0 shannon
**Budgie version**: Budgie 10.2.9-110

**The issue encountered**

When opening the start menu, whether it's with the windows (super) button, or clicking the menu itself, it will open the menu in the wrong area before going to where it should be, but it's delayed by about a good second sometimes.
![screenshot from 2017-01-26 08-18-50](https://cloud.githubusercontent.com/assets/15918185/22332931/7615e22e-e3a1-11e6-8e31-f764d05e20b2.png)

**Steps to reproduce the issue**

Opening the start menu.

**Comment by fossfreedom** [comment]
This is a duplicate of https://github.com/budgie-desktop/budgie-desktop/issues/292

**Comment by kevinarefunny** [comment]
My bad, I'll close the issue then.
