### ISSUE TITLE
Places applet displays duplicate directory names

### ISSUE THREAD

**Issue by tristan957** [budgie-desktop/budgie-desktop#784]
**Operating System**: e.g. Solus 2017.01.01.0
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**

The places applet is duplicating directory names.
![bug](https://cloud.githubusercontent.com/assets/11936772/22394049/cd16720c-e4da-11e6-8c77-84b2cfaf7b52.png)
 ...

**Steps to reproduce the issue**

Bookmark a directory in Nautilus and open the Places indicator.
 ...

**Comment by ikeydoherty** [comment]
I'm fairly sure that was fixed in git, @cybre ?

**Comment by tristan957** [comment]
Sorry didn't see anything when I searched for similar issues.

**Comment by ikeydoherty** [comment]
Nah probably not issue wise, but I think the git since 10.2.9 fixed it, hence wanting confirmation :D

**Comment by cybre** [comment]
This is the first time I've seen this behaviour. Can you paste me the output of `cat ~/.config/gtk-3.0/bookmarks`, please?

**Comment by cybre** [comment]
@tristan957 Can I get that output?

**Comment by ikeydoherty** [comment]
Fairly sure this is resolved with https://github.com/budgie-desktop/budgie-desktop/commit/3337893b2076022fd5359a9c7ed41094baa909cf

If not, please reopen.

**Comment by tristan957** [comment]
@cybre my bad on the late reply. For reference:

![cyber](https://cloud.githubusercontent.com/assets/11936772/23454359/97f206a2-fe31-11e6-802a-9d04cf0c180a.png)

**Comment by ikeydoherty** [comment]
Yeah that's the space issue I fixed in the referenced commit. URL is the left side of the split and the display name is the right hand side.
