### ISSUE TITLE
Budgie Freezes when Super key is pressed.

### ISSUE THREAD

**Issue by Riokei** [budgie-desktop/budgie-desktop#798]
**Operating System**: Solus 2017.01.01.0
**Budgie version**: i.e. Budgie 10.2.9

When striking the super key on  my keyboard budgie completely freezes and becomes non-responsive when I click on it.

**Comment by JoshStrobl** [comment]
Unable to reproduce. Please validate if this still an issue on latest Solus and Budgie.

**Comment by Riokei** [comment]
After all the updates I can't find the issue either I think it was fixed, if I remember correctly it only happened on Arc theme but it seems an update fixed it.

**Comment by fossfreedom** [comment]
thanks for the confirmation.

**Comment by ikeydoherty** [comment]
Yay for random
