### ISSUE TITLE
 Budgie Desktop Settings by command line or file settings 

### ISSUE THREAD

**Issue by subhaniminhas** [budgie-desktop/budgie-desktop#801]
**Operating System**: budgie-remix-16.10-i386 Fresh - A special OS which takes 220 mb after booting
**Budgie version**:budgie-desktop 10.2.9
I am building a custom OS based on Budgie Remix using squashfs tools. I want to customize my budgie desktop in a certain manner in the custom CD e.g i want the panel to be at the bottom, clock to be on the right side, load all applets in a certain manner etc. How can i achieve it? I know it is not an issue, but if i have to do it again and again on hundreds of PCs, then there must be some  file settings which i can edit or some command line options. If not then some method of command line option must be provided to customize the budgie desktop as per requirement. Any clue or help is appreciated. Thanks

**Comment by ikeydoherty** [comment]
Please see https://github.com/solus-project/budgie-desktop-branding for an example of how to do this.
Effectively you need to provide gsettings schema overrides. 

Additionally, see the `src/panel/panel.ini` file for the default layout file, which you can provide your version of at:

 - `/usr/share/budgie-desktop/panel.ini`
 - `/etc/budgie-desktop/panel.ini`

**Comment by fossfreedom** [comment]
@subhaniminhas for ubuntu budgie  we have tailored our panel.ini as per this https://github.com/UbuntuBudgie/budgie-desktop-environment/tree/master/panel_override - other customisations via override files as per https://github.com/UbuntuBudgie/budgie-desktop-environment/tree/master/debian

**Comment by ikeydoherty** [comment]
Yep override the .ini, and then use gschema overrides. I'm closing this as resolved, feel free to reopen

**Comment by PizzaLovingNerd** [comment]
Hey, where is the panel.ini file on Arch?
