### ISSUE TITLE
Screen doesn't turn back on after closing the laptop lid.

### ISSUE THREAD

**Issue by kimsaehun** [budgie-desktop/budgie-desktop#802]
**Operating System**: I'm pretty sure its the latest one since I always run "sudo eopkg up". Not sure how to check.
**Budgie version**: Budgie 10.2.9

**Screen doesn't turn back on after closing the laptop lid.**

The issue is that the screen stays turned off after reopening laptop lid after closing it. If I close it and open it right away, the issue doesn't occur but occurs only if the laptop lid stays closed for a short period of time (around 3-5 min). Then I've had to hold down the power button to shut the laptop off since nothing would get the screen to turn back on.

The Solus version I use is most likely the latest stable one and same with budgie as well.

The laptop I am using is [HP 15-ay192nr](http://support.hp.com/us-en/document/c05349041).

I would like to provide a stack trace/logs but am unsure of what logs would be useful and how to provide the logs.

**Steps to reproduce the issue**
Close the laptop lid and wait a couple of minutes. Reopen the lid and check if the screen turns back on.

**Comment by fossfreedom** [comment]
doubtful this is a budgie-desktop issue - suggest phabricator would be a better place to raise this issue https://dev.solus-project.com/

**Comment by ikeydoherty** [comment]
Yeah sounds like a systemd/gnome-screensaver interaction issue.

**Comment by kimsaehun** [comment]
Ah, understood, moved to https://dev.solus-project.com/T2601

Thanks for the replies! Will close this this issue.
