### ISSUE TITLE
Hibernate / Lock not working

### ISSUE THREAD

**Issue by JDECOMBE** [budgie-desktop/budgie-desktop#803]
Hi,
I've just install the Budgie Desktop on a fresh Archlinux installation and i can't hibernate / lock. I'm a bit of a newbie with arch ... :) Everythings else work. I'm using a grub to switch between my different os and i don't have any problem with them.
Did I do something wrong with the installation ? My logind.conf is set as default at the moment but i've try to uncomment the poweroffkeybutton line and set it to hibernate... In fact, the suspend function works fine. 
On the top right of the screen, when i click on the power-management applet i have a list of options like suspend, hibernate, poweroff, reboot. All of them works except for Hibernate and Lock... Suspend doesn't lock my computer by the way.
Can you guys help me fixing the issue please ? :)
Thank you for reading all my paragraph and i apology for the language mistakes i should have made.

**Comment by ikeydoherty** [comment]
Do you have `gnome-screensaver` and `lightdm` installed & active?

**Comment by JDECOMBE** [comment]
I think lightdm is not installed and I don't know for gnome-screensaver. But I'm not using the gnome desktop. Is it important to have ?

**Comment by JDECOMBE** [comment]
The budgie* desktop

**Comment by JDECOMBE** [comment]
I've just check and both of them are not in the systemctl -a command output.
When I type systemctl hibernate, i have this error : "Failed to hibernate system via logind: Sleep verb not supported"
Thanks for your replie by the way :)

**Comment by archevist** [comment]
@JDECOMBE run:

1) `pacman -Qs gnome-screensaver` to see if installed, if _no_ then run `pacman -S` to do so.

2) For hibernation on Arch, are you sure to have followed? I think it is a not budgie issue.
> https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#Hibernation

Also see discussion in Ubuntu forums about `systemctl hibernate`:
> https://ubuntuforums.org/showthread.php?t=2331899

**Comment by archevist** [comment]
@JDECOMBE: I also run Arch, just tested Suspend (to RAM) is working correctly as intended on default settings:

1) `pacman -Qs gnome-screensaver` to see if installed, if _no_ then run `pacman -S` to do so.

2) For hibernation on Arch, are you sure to have followed? Hibernation is also working for me but since I haven't configured it as required it does not restore saved state. I think it is a not budgie issue.
> https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#Hibernation

**Comment by JDECOMBE** [comment]
I may have misunderstood what is hibernation. I've read your link. I think all i want is a suspend + lock functionnality. But i can't even lock with the system applet ... I've intalled the gnome-screensaver what is it supposed to be ? Thanks for you replies

**Comment by CameronNemo** [comment]
Is `light-locker` also supported in place of `gnome-screensaver`.

**Comment by JDECOMBE** [comment]
I'm sorry i didn't understood what you meant to say :/ I've installed xscreensaver to lock my computer as the default actino isn't working (rip) but it doesn't automatically lock my computer when i close the laptop :/ just suspend. I'm sorry for being a bit of a pain in the backside by not understanding much of what's happening xD

**Comment by JDECOMBE** [comment]
It's okay everythings work xD I've just forget to reboot my computer after installeing gone-screensaver xDDDD Thanks everybody for yopur help i'll close the issue :)
