### ISSUE TITLE
Audit output controls in Raven side menu

### ISSUE THREAD

**Issue by archevist** [budgie-desktop/budgie-desktop#804]
_Hi, please excuse if this is not a bug but I am unable to trace any documentation or similar issue on web to fix mine. Suggest me a solution please_

**Issue:**
Unable to toggle (turn on/off) audio outputs from Raven menu. Currently, all 3 outputs are on and cannot be changed. 

<a href="http://tinypic.com?ref=i2mz9d" target="_blank"><img src="http://i68.tinypic.com/i2mz9d.png" border="0" ></a>

Correct behavior should be like this screenshot (where one device is on and others are off):
<img src=https://cloud.githubusercontent.com/assets/156574/12983245/131399fa-d0f1-11e5-8a76-9b48f7b0d28f.png ></a>

**Other information**
OS: Arch Linux

Kernel: 
Linux _mypc_ 4.9.10-1-ck-nehalem x86_64 GNU/Linux

Budgie version:
budgie-desktop 10.2.9-1

**Comment by ikeydoherty** [comment]
Fixed in ef067f48b75067218ad45d35de50950cb4fece5b
