### ISSUE TITLE
Network indicator isn't visible after update to 10.2.9-2

### ISSUE THREAD

**Issue by majinsaiyan** [budgie-desktop/budgie-desktop#806]
**Operating System**: Ubuntu budgie remix 16.10
**Budgie version**: 10.2.9-2

**The issue encountered**

After updating all packages (which includes budgie desktop) via synaptic package manager , network indicator has gone missing. I tried removing/adding system tray applet but it still doesn't show.

**Comment by fossfreedom** [comment]
This isnt a budgie-desktop issue - it is a distro specific issue.  As such, please close this.  Pop into our chat room and we'll see if we can work out what your issue is. https://gitter.im/ubuntubudgie/community

**Comment by majinsaiyan** [comment]
Sorry, actually a reboot for 2nd time bought back indicator. My bad
