### ISSUE TITLE
Password entry completely looses focus when sign in

### ISSUE THREAD

**Issue by DaniloGomez** [budgie-desktop/budgie-desktop#808]
**Operating System**: Debian 9 (stretch)
**Kernel Version**: 4.9.0-1
**Budgie version**: Budgie 10.2.9-2

When I unblock my computer the entry for password at budgie login window (not the window manager's) loses the focus and after that there's no way to recover it. I can even push the sign-in button but I can't write my password.

I found this behavior **almost** every day on my computer and sometimes twice. But it doesn't happen every time I unblock the computer.

**Comment by fossfreedom** [comment]
That window is provided for by gnome-screensaver not budgie-desktop. As such this looks to be a Debian stretch specific issue with that package.

**Comment by DaniloGomez** [comment]
I think that window is from budgie. The gnome-screensaver window is too ugly to look like that.

**Comment by JoshStrobl** [comment]
@DaniloGomez We leverage gnome-screensaver during unlock and LightDM during the initial sign-in.

**Comment by DaniloGomez** [comment]
# OK or K.O.
for some reason `xscreensaver` and `gnome-screensaver` both had an entry at the starting up applications and there was the two instances at unblock time
thanks
