### ISSUE TITLE
double flash when opening any panel popover

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#809]
**Operating System**: e.g. Ubuntu Budgie 17.04 (GTK+3.22, libmutter 3.23.90)
**Budgie version**: i.e. Budgie 10.2.9

**The issue encountered**

An end-user has reported the following:

Any budgie-panel popover double flashes - example video:
https://youtu.be/vedptXZDcao
 ...

**Steps to reproduce the issue**
As above. Demonstrated the issue with the start menu - clicking on places/sound applets also shows this effect.

User confirms this is not a theme issue - changed from Arc to Adwaita.
Use confirms that this is not a standard popover issue - apps with client-side decorations - all buttons in the CSD work without a flash except the window control (top left most button) also exhibits the issue.

User states: "Thinkpad T60 using the Intel Corporation Mobile 945GM/GMS graphics card."

Another user on G+ also appears to report the same issue - will try to get them to update here on this issue.

 ...

**Comment by makitso** [comment]
I original reported this issue to David.  The same behavior happens booting the Ubuntu 17.04 live CD.
The graphics driver is i915

**Comment by ikeydoherty** [comment]
Yeah - this is actually a 3.22+beyond issue. We had to adapt those last changes to suit 3.22, prior to Meson switch. We'll need to #ifdef that stuff for 3.22.. and fix it

**Comment by makitso** [comment]
sudo hwinfo | grep Graphics
  E: ID_MODEL_FROM_DATABASE=Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (ThinkPad R60/T60/X60 series)
  E: ID_MODEL_FROM_DATABASE=Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphics Controller (ThinkPad R60/T60/X60 series)
  Device: pci 0x27a6 "Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphics Controller"

**Comment by fossfreedom** [comment]
has been reported also here: https://bugs.launchpad.net/ubuntu/+source/budgie-desktop/+bug/1667934

relevant info from the bug report:

) Lappy Spec: https://hastebin.com/ucoqeqahik.sql
2)Graphical Issue: I have given a reference video sample which was taken on remix 16.10 in which this issue is not present. remix 16.04 also does not have this glitch.

The issue is when i click options on top bar such as "user indicator(power button)" or "bluetooth" or "clock" or "budgie menu" etc. , the animation is aggressive as if it opens twice.

video (where this bug is present): https://drive.google.com/open?id=0B18EJ0Qm1XtWNmFzQzBGSEFaWEU

**Comment by CrisBRM** [comment]
It's worth nothing that if you _click_ on the menu, it will only flicker the very first time. It will not flicker if you _click_ on it again. However, it will always flicker if you hit the superkey.

Driver stack is radeon's (free).

**Comment by ikeydoherty** [comment]
Yeah I've said this a few times now its not driver/hardware related :P It's GNOME 3.22+ related

**Comment by fossfreedom** [comment]
feedback from two users affected:

dropping this commit resolves this issue for those users affected by this issue

 - https://github.com/budgie-desktop/budgie-desktop/commit/1d7145ef6a6cf1827b724586bc7aa2eb479e7f1c

**Comment by fossfreedom** [comment]
ok - more feedback - for some users even dropping the gtk animations .hide vs .popup this issue still occurs.

Any thought @ikeydoherty where is the code-base this issue is occurring?

**Comment by ikeydoherty** [comment]
Reverting it for now per advice

https://github.com/budgie-desktop/budgie-desktop/commit/97d78d14941c4538389d18492fd44fdd92cdb5b9

Once I find a better fix I'll merge. Better to have no animation than two of them.
