### ISSUE TITLE
Panel (Task Bar) Visual Issue

### ISSUE THREAD

**Issue by chifreeagle** [budgie-desktop/budgie-desktop#812]
**Operating System**: Solus 2017.01.01.0 64-bit
**Budgie version**: budgie-desktop 10.2.9

**The issue encountered**

The task bar is not positioned properly. 

**Steps to reproduce the issue**

1. Open Raven Menu
2. Select Settings
3. Select Panel
4. Make the size value bigger 
> The issue should be visible.

** Solution ** 

1. Open Raven Menu
2. Select Settings
3. Select Panel
4. Reduce the font value

// Take a look at the screenshot attached

**Comment by ikeydoherty** [comment]
Please say that you actually did forget to upload the screenshot. I have an eyetest tomorrow and I'm now worried.

**Comment by chifreeagle** [comment]
My bad...

**Comment by chifreeagle** [comment]
[there](https://drive.google.com/file/d/0B1EqoEWNWo8bTk9rc3VUcmpaOW8/view?usp=sharing) we go

**Comment by chifreeagle** [comment]
The panel (Task Bar ) have to be set on the bottom position in order for the white line to appear.

**Comment by JoshStrobl** [comment]
Duplicate of #312 it turns out.
