### ISSUE TITLE
`ninja install` fails from installing documentation

### ISSUE THREAD

**Issue by MatthewScholefield** [budgie-desktop/budgie-desktop#813]
**Operating System**: Solus 2017.01.01.0
**Budgie version**: Latest Budgie Git (`5991c79b4a8ff0ac9a4bde85f02daa71421cd4dd`)

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

    budgie-desktop --version

**The issue encountered**
[This error when fetching remote content](https://gist.github.com/MatthewScholefield/4ae843b52c3ae6a2811bcc8e3afeaaab)

**Steps to reproduce the issue**
Build and attempt to install budgie-desktop with:
```
meson build
cd build
ninja
sudo ninja install
```

**Comment by ikeydoherty** [comment]
Ah right, you need `docbook-xml` installed. We should make that a runtime dep of `gtk-doc` in Solus. Additionally we should likely make it *optional* to install gtk-doc

**Comment by ikeydoherty** [comment]
I've fixed this on the Solus side in https://git.solus-project.com/packages/gtk-doc/commit/?h=gtk-doc-1.24-3

**Comment by ikeydoherty** [comment]
Can now disable it as described in the referenced commit above ^
