### ISSUE TITLE
Menu popup issue when panel is set to bottom (arch linux)

### ISSUE THREAD

**Issue by tankmohit** [budgie-desktop/budgie-desktop#815]
When panel is set to top, everything works fine. But when moved to bottom, pressing super key opens menu at top left corner first then pops up again at bottom left corner.

I installed Budgie desktop straight after installing arch.

Laptop info.
Amd 7410 apu.
Amd r5 m330 graphics
4 gb ram.

**Comment by fossfreedom** [comment]
Hi!
 welcome to budgie-desktop.

This issue has been reported previously and is being tracked here - https://github.com/budgie-desktop/budgie-desktop/issues/292

As such I'll close this as a duplicate. cheers.
