### ISSUE TITLE
Whoa: "Are you sure you want to permanently delete the 36,130 selected items?"

### ISSUE THREAD

**Issue by SomeGuy54321** [budgie-desktop/budgie-desktop#816]
**Operating System**: Ubuntu 17.04 (on VMware Workstation)
**Budgie version**: budgie-desktop 10.2.9
**The issue encountered**

I was renaming a file, and I made an error while typing, and I pressed CTRL+Z to undo, then I was asked if I wanted to permanently delete my whole home directory.

Ideally I would never ever be asked this.

**Steps to reproduce the issue**

1. Create a folder on your Desktop
2. Make a file in it
3. Right-click > Rename
4. Type something
5. Press CTRL+Z

Screenshot: 
![ubuntu budgie - zesty zapus 17 04 64-bit - vmware workstation](https://cloud.githubusercontent.com/assets/13367887/23577684/86818d3c-00bd-11e7-9d63-dccc192251c2.png)

**Comment by SomeGuy54321** [comment]
This happens even when I untick "Show action to permanently delete files and folders" in the Files preferences.

**Comment by fossfreedom** [comment]
Hi
  welcome to budgie-desktop.

Nautilus (Files) is part of the GNOME project.  The correct location for submitting issues is on their tracker - https://bugzilla.gnome.org/

As such I will close this.  Please submit your report to GNOME.

**Comment by SomeGuy54321** [comment]
Filed https://bugzilla.gnome.org/show_bug.cgi?id=779562
