### ISSUE TITLE
Dashed lines when scrolling to the end

### ISSUE THREAD

**Issue by baimafeima** [budgie-desktop/budgie-desktop#818]
Operating System: Solus 2017.01.01.0
Budgie version: Budgie 10.2.9

The issue encountered:
When scrolling to the end in applications such as Nautilus or SC, I get visual screen artefacts in the form of dashed lines. See screenshots below.

Steps to reproduce the issue:
Scroll in Nautilus or SC

Screenshots: 
![visualartefacts1](https://cloud.githubusercontent.com/assets/23112309/23614663/af9cf35c-02be-11e7-9897-480f5399472f.png)
![visualartefacts2](https://cloud.githubusercontent.com/assets/23112309/23614664/afb042a4-02be-11e7-8eae-2cdf728e4e99.png)

**Comment by ikeydoherty** [comment]
Those aren't visual artefacts - they're what Gtk calls "overshoot" regions. Ugly as all fuck but that's how they decided to handle overlay scrolling with kinetic input. By sticking dashed lines at one end to tell you its the end of that direction.

Themes *can* override this a small but - but its a big pain. As such it's not an actual Budgie issue, as much as I wish it was, so I could neuter it.

**Comment by baimafeima** [comment]
Thanks for the letting me know the cause of those dashed lines. Then I guess we need to sit this out until Budgie has moved to Qt or is there any way to fine-tune the default themes a bit to make it less obvious?
