### ISSUE TITLE
Raven sidebar is outlined when opened

### ISSUE THREAD

**Issue by rawsh** [budgie-desktop/budgie-desktop#819]
**Operating System**: Solus latest
**Budgie version**: Budgie 10.2.9

**The issue encountered**

Whenever the panel is clicked it is outlined with no background. An image is worth a thousand words, and a gif... a gif is worth a thousand images:

![](https://u.teknik.io/jUrv3.gif)

And a freeze frame:

![](https://u.teknik.io/pF205.gif)

This is the arc theme but it happens with others.

**Comment by ikeydoherty** [comment]
You disabled the builtin theme didn't you?

**Comment by ikeydoherty** [comment]
TL;DR The builtin theme *is* Arc. If you disable it you need to use a theme that actually supports Budgie (i.e. Paper, Adapta, etc.) 

Not being themed isn't a bug - you've requested it to not do so. With builtin theming enabled it will provide the Arc styling by default.

**Comment by rawsh** [comment]
@ikeydoherty Ok, cool. By "using arc" I meant that I disabled the built in theme and selected arc dark.

**Comment by ikeydoherty** [comment]
Yeah it's *already* Arc Dark styled :)
