### ISSUE TITLE
Can't pin Gnome Twitch to the budgie bar

### ISSUE THREAD

**Issue by ky0-kunix** [budgie-desktop/budgie-desktop#821]
Install the Gnome Twitch app and launch it. It doesn't have the correct icon and can't be pinned.

Info from xprop: WM_CLASS(STRING) = "gnome-twitch", "Gnome-twitch"

full xprop dump:
_NET_WM_ICON_GEOMETRY(CARDINAL) = 414, 0, 35, 31
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x2e00001
_GTK_THEME_VARIANT(UTF8_STRING) = "dark"
XdndAware(ATOM) = BITMAP
_GTK_APP_MENU_OBJECT_PATH(UTF8_STRING) = "/com/vinszent/GnomeTwitch/menus/appmenu"
_GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/com/vinszent/GnomeTwitch/window/1"
_GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/com/vinszent/GnomeTwitch"
_GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.57"
_GTK_APPLICATION_ID(UTF8_STRING) = "com.vinszent.GnomeTwitch"
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1920, 1048
_GTK_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 48234505, 48234506
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2e00008
WM_CLIENT_LEADER(WINDOW): window id # 0x2e00001
_NET_WM_PID(CARDINAL) = 2059
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "zen"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 969 by 146
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "gnome-twitch", "Gnome-twitch"
WM_ICON_NAME(STRING) = "GNOME Twitch"
_NET_WM_ICON_NAME(UTF8_STRING) = "GNOME Twitch"
WM_NAME(STRING) = "GNOME Twitch"
_NET_WM_NAME(UTF8_STRING) = "GNOME Twitch"

**Comment by ikeydoherty** [comment]
What is the .desktop file name?

**Comment by ky0-kunix** [comment]
com.vinszent.GnomeTwitch.desktop

Desktop info:


[Desktop Entry]
Name[cs]=GNOME Twitch
Name[de]=GNOME Twitch
Name[fr]=GNOME Twitch
Name[hu]=GNOME Twitch
Name[pl]=GNOME Twitch
Name[pt]=GNOME Twitch
Name[ru]=GNOME Twitch
Name[sr]=Гном Твич
Name[sv]=GNOME Twitch
Name[nl]=GNOME Twitch
Name=GNOME Twitch
Comment[cs]=Užijte si Twitch na svém GNU/Linux systému
Comment[de]=Genieße Twitch auf deinem GNU/Linux Computer
Comment[fr]=Profitez de Twitch sur votre bureau GNU/Linux
Comment[hu]=Élvezd a Twitch-et a GNU/Linux gépeden
Comment[pl]=Oglądanie serwisu Twitch w systemie GNU/Linux
Comment[pt]=Desfrute o Twitch no seu ambiente de trabalho GNU/Linux
Comment[ru]=Наслаждайтесь Twitch в вашем GNU/Linux
Comment[sr]=Уживајте у гледању Твича на вашем ГНУ/Линукс уређају
Comment[sv]=Njut av Twitch på din GNU/Linux desktop
Comment[nl]=Geniet van Twitch op uw GNU/Linux desktop
Comment=Enjoy Twitch on your GNU/Linux desktop
# Translators: Search terms to find this application.
# Do NOT translate or localize the semicolons!
# The list MUST also end with a semicolon!
Keywords[cs]=stream;streamování;video;twitch;živě;live;hry;hraní;
Keywords[de]=stream;video;twitch;live;spiele;
Keywords[fr]=flux;vidéo;twitch;direct;jeux;stream;video;twitch;live;games;
Keywords[hu]=közvetítés;videó;twitch;élő;játékok;
Keywords[pl]=stream;strim;streamowanie;wideo;video;twitch;tłicz;na 
żywo;live;gry;granie;oglądanie;kanały;
Keywords[pt]=stream;vídeo;twitch;direto;jogos;
Keywords[ru]=stream;video;twitch;live;games;
Keywords[sr]=stream;video;twitch;live;games;strim;video;tvič;uživo;lajv;igre;igrice;стрим;видео;твич;лајв;уживо;игре;игрице;
Keywords[sv]=livesändning;video;twitch;spel;
Keywords[nl]=livestream;video;twitch;spel;
Keywords=stream;video;twitch;live;games;
Type=Application
Exec=gnome-twitch
# Translators: Don't translate this, xgettext marks this automatically
Icon=gnome-twitch
Categories=GTK;GNOME;AudioVideo;Player;Video;
Terminal=false

**Comment by ikeydoherty** [comment]
As expected the `.desktop` file doesn't match the `WM_CLASS` name so Budgie can't find it.

**Comment by ky0-kunix** [comment]
I see - I'll rename it as a workaround for now. Thx ikey - close or keep this bugfix open - do as you like :)

**Comment by ikeydoherty** [comment]
Or symlink :) Budgie has somewhat .. limited.. powers

**Comment by ky0-kunix** [comment]
renaming to gnome-twitch.desktop did the trick :) Much <3
