### ISSUE TITLE
A second keypress should close Budgie Menu

### ISSUE THREAD

**Issue by rawsh** [budgie-desktop/budgie-desktop#822]
**Budgie version**: Budgie 10.2.9

Pressing the windows key brings up Budgie menu, but pressing it again closes and reopens it.

![](https://u.teknik.io/Ubjw4.gif)

**Comment by archevist** [comment]
Same here, but try pressing ESC and it will close forever.

**Comment by fossfreedom** [comment]
This issue is being tracked here - https://github.com/budgie-desktop/budgie-desktop/issues/605

As such we'll close this as a duplicate.  thanks.
