### ISSUE TITLE
Application Applet Drawing Bug

### ISSUE THREAD

**Issue by JLCCI** [budgie-desktop/budgie-desktop#825]
Fresh install of Budgie (10.2.9), everything updated. After moving the panel to the bottom and hitting the windows key/clicking the application button (which brings the application selection applet) the applet is first drawn at the top, quickly disappears and then is properly drawn at the bottom. Difficult for me to get a snapshot as it happens too fast to catch. Happens every time I press the window button and 60% of the time when I click the button.

Many thanks for looking into this!

**Comment by chifreagle** [comment]
the same as #292 #612  etc ...

**Comment by JLCCI** [comment]
Ups, did not notice. Will close, thanks for pointing it out.

**Comment by chifreagle** [comment]
thanks for contributing
