### ISSUE TITLE
Raven visual bug

### ISSUE THREAD

**Issue by rawsh** [budgie-desktop/budgie-desktop#826]
**Budgie version**: budgie-desktop 10.2.9

After a certain period of time (for me its around 20 mins) the raven panel opener opens raven, then quickly closes again. Subsequent clicks behave normally.

**Comment by fossfreedom** [comment]
Please edit your comment - we need to have these exact details as per the issue template

**Operating System**: e.g. Solus 1.2.0.5
**Budgie version**: i.e. Budgie 10.2.7 OR specific git commit

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

    budgie-desktop --version

**Comment by rawsh** [comment]
@fossfreedom it has been edited. I'm running budgie desktop on Arch.

**Comment by JoshStrobl** [comment]
Please validate if this is still an issue with Budgie 10.3/10.3.1.

**Comment by rawsh** [comment]
Fixed.
