### ISSUE TITLE
Alt + Fn + F2 crashes budgie

### ISSUE THREAD

**Issue by rawsh** [budgie-desktop/budgie-desktop#828]
**Operating System**: Manjaro 17
**Budgie version**: budgie-desktop 10.2.9

When attempting to open the run dialogue the desktop freezes and does not accept input. The mouse moves but cannot interact, and the dialogue does not open.

I would include logs but I'm not sure where they are.

**Comment by ikeydoherty** [comment]
The shortcut is Alt+F2

**Comment by rawsh** [comment]
@ikeydoherty I know, but my laptop requires the FN key. Plugging in a keyboard and using Alt+F2 results in the same issue.

**Comment by ikeydoherty** [comment]
Ah gotcha. Ok anything in `dmesg`, `journalctl -ae` or `coredumpctl` ?

**Comment by rawsh** [comment]
It looks like switching to an Arch console breaks it as well.

I don't see any relevant in dmesg or coredumpctl but here are some lines from journal:

`
Mar 20 10:25:42 rawlinux gnome-session[690]: gnome-session-binary[690]: WARNING: Could not parse desktop file budgie-desktop-screensaver.desktop or it references a not found TryExec binary
Mar 20 10:25:42 rawlinux gnome-session-binary[690]: WARNING: Could not parse desktop file budgie-desktop-screensaver.desktop or it references a not found TryExec binary

...

Mar 20 10:25:43 rawlinux budgie-wm[808]: invalid (NULL) pointer instance
Mar 20 10:25:43 rawlinux budgie-wm[808]: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Mar 20 10:25:43 rawlinux budgie-wm[808]: ibus.vala:51: ibus-daemon unsupported on this system
Mar 20 10:25:43 rawlinux budgie-wm[808]: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Mar 20 10:25:43 rawlinux budgie-wm[808]: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Mar 20 10:25:43 rawlinux budgie-panel[838]: IconTasklistApplet.vala:382: Invalid application! firefox.desktop

...

Mar 20 10:25:56 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:25:56 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:25:56 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:25:58 rawlinux budgie-panel.desktop[838]: [1183:1183:0320/102558.377760:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

...

Mar 20 10:26:01 rawlinux budgie-panel[838]: IconTasklistApplet.vala:382: Invalid application! firefox.desktop
Mar 20 10:26:18 rawlinux pamac-tray[931]: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Mar 20 10:26:23 rawlinux budgie-panel.desktop[838]: couldn't lock 16384 bytes of memory (secret_session): Cannot allocate memory

...

Mar 20 10:29:42 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:29:57 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:30:49 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:30:50 rawlinux budgie-panel.desktop[838]: Setting up Steam content in /home/robert/.local/share/Steam
Mar 20 10:30:51 rawlinux budgie-panel.desktop[838]: cp: cannot stat '/usr/share/applications/steam.desktop': No such file or directory
Mar 20 10:30:51 rawlinux budgie-panel.desktop[838]: chmod: cannot access '/home/robert/Desktop/steam.desktop': No such file or directory
Mar 20 10:30:53 rawlinux budgie-panel.desktop[838]: Running Steam on manjarolinux 17.0 64-bit
Mar 20 10:30:53 rawlinux budgie-panel.desktop[838]: STEAM_RUNTIME is enabled automatically
Mar 20 10:30:53 rawlinux budgie-panel.desktop[838]: Installing breakpad exception handler for appid(steam)/version(0)
Mar 20 10:30:53 rawlinux budgie-panel.desktop[838]: /home/robert/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib32/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
Mar 20 10:30:53 rawlinux budgie-panel.desktop[838]: /home/robert/.local/share/Steam/steam.sh: line 444: no match: ssfn*
Mar 20 10:31:00 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:31:16 rawlinux budgie-panel.desktop[838]: Repairing installation, linking /home/robert/.steam/steam to /home/robert/.local/share/Steam
Mar 20 10:31:16 rawlinux budgie-panel.desktop[838]: Running Steam on manjarolinux 17.0 64-bit
Mar 20 10:31:16 rawlinux budgie-panel.desktop[838]: STEAM_RUNTIME is enabled automatically
Mar 20 10:31:16 rawlinux budgie-panel.desktop[838]: Installing breakpad exception handler for appid(steam)/version(0)
Mar 20 10:31:16 rawlinux budgie-panel.desktop[838]: /home/robert/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib32/libxcb-dri3.so.0: undefined symbol: xcb_send_request_with_fds
Mar 20 10:31:16 rawlinux budgie-panel.desktop[838]: /home/robert/.local/share/Steam/steam.sh: line 444: no match: ssfn*
Mar 20 10:32:03 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:32:07 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:32:09 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00007 (Package Ma)

...

Mar 20 10:32:19 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1400008 (Authentica)
Mar 20 10:32:21 rawlinux polkitd[351]: Operator of unix-session:c1 successfully authenticated as unix-user:robert to gain TEMPORARY authorization for action org.manjaro.pamac.commit for system-bus-name::1.49 [pamac-manager] (owned by unix-user:robert)
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:32:21 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:33:33 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:33:36 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:33:57 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:33:57 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00007 (Package Ma)

...

Mar 20 10:40:19 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:40:21 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c000f8 (Untitled D)
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:04 rawlinux budgie-panel[838]: wnck_window_set_icon_geometry: assertion 'WNCK_IS_WINDOW (window)' failed
Mar 20 10:41:05 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0xe00007 (budgie-pan)
Mar 20 10:41:06 rawlinux budgie-wm.desktop[808]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c000f8 (Untitled D)
`

plus a few more lines. I have attached the full files if you would like to take a look. (it looks like firefox being pinned then uninstalled while pinned caused an error? I'm not sure it's related though)

https://u.teknik.io/41GF6.log
https://u.teknik.io/hkCZH.log
https://u.teknik.io/1cQV8.log

**Comment by ikeydoherty** [comment]
OK so it looks like several things are going wrong here. The WM shat its pants because ibus isn't supported

**Comment by rawsh** [comment]
@ikeydoherty Is this something wrong with Manjaro? I think this was working on Antergos.

**Comment by ikeydoherty** [comment]
What version of Budgie you on ?

**Comment by rawsh** [comment]
@ikeydoherty looks like just FN in generall crashes this.

**Comment by rawsh** [comment]
@ikeydoherty also happening on gnome. Yet Another GTK Issue? 

BTW I look forward to your move to QT.

**Comment by Orion116** [comment]
I am also on Manjaro and I have to use the same fn + alt + f2 command. Budgie 10.2.9 built from github source. I am also using GNOME 3.22. The command works fine for me.
![screenshot from 2017-03-22 22-39-36](https://cloud.githubusercontent.com/assets/10589187/24229576/8cb71bd0-0f50-11e7-980f-e26e2e1ad263.png)

**Comment by rawsh** [comment]
@Orion116 hmmm, I started off with manjaro gnome then installed budgie from there. Not sure why it's not working for me.

@ikeydoherty Any updates? A bunch more keys like brightness keys crash budgie as well. Any more logs I need to send over?

**Comment by rawsh** [comment]
Fixed on update.
