### ISSUE TITLE
Show the run command prompt with Super key

### ISSUE THREAD

**Issue by giangm9** [budgie-desktop/budgie-desktop#831]
Since the "Show the run command prompt" is not quite diffirent than Budgie menu, i removed the menu icon and try to use that function instead. But i can not assign the Super key to that function.

**Comment by mehcode** [comment]
I have it bound to `Super+Space` and it works nice. I think allowing a modifier key to be a key shortcut on its own is weird and could make the handling code complex.

**Comment by JLCCI** [comment]
@mehcode but the Budgie menu is bound to it already? I tried playing with the shortcuts in Gnome keyboard but it does not allow to set a shortcut with just Super. Would be nice it there was an easy solution to reassign it.

**Comment by ikeydoherty** [comment]
The Super key is reserved solely for the Budgie Menu. Any hotkeys may be altered within GNOME Control Center itself. We will not be making Super activate anything other than the default Mutter signaling behaviour
