### ISSUE TITLE
Add shutdown, reboot, logout to Menu and run command prompt

### ISSUE THREAD

**Issue by giangm9** [budgie-desktop/budgie-desktop#832]
Can you add Shutdown, Reboot in the menu and run command prompt ?
like this 
![image](https://cloud.githubusercontent.com/assets/10234339/24250777/9dcae342-100a-11e7-92f1-8d9542c2d77c.png)

**Comment by mehcode** [comment]
To add to this list, "Force Quit", ala `xkill` would be lovely to be able to quickly access via the run dialog.

---

Perhaps there could be some simple way of defining commands (with a set of common pre-defined ones)?

**Comment by fossfreedom** [comment]
@mehcode if you have a predefined command line - just wrap it up in a .desktop file and pop it into ~/.local/share/applications.  It should then appear in the run-dialog/menu

**Comment by mehcode** [comment]
@fossfreedom Oh. I should clarify. I know but I meant a GUI ability to do so conveniently like (I know alacarte works for Budgie _now_ but with the move away from Gnome It'd be a nice thing to make sure still works):

![bnoaj](https://cloud.githubusercontent.com/assets/753919/24395237/d472c72e-1353-11e7-8049-2afeb42cacb7.png)

**Comment by giangm9** [comment]
can you give me a command to show shutdown prompt instead of shutdown instantly ?

**Comment by ikeydoherty** [comment]
Yeah I'm not peppering every possible window with a shutdown control, sorry. We have one in Raven. For the menu itself in the style you describe, it would require .desktop files invoking `gnome-session-quit` (check `--help` for it :))
