### ISSUE TITLE
Button "Open Software Center" doesn't work

### ISSUE THREAD

**Issue by iachopolo** [budgie-desktop/budgie-desktop#834]
**Operating System**: Solus 2017.01.01.0
**Budgie version**: Budgie 10.2.9

**The issue encountered**
The button "Open Software Center" from the popup when updates are available doesn't work.

**Steps to reproduce the issue**
Press the button when popup appears
Nothing happens

PS: I have it in spanish, so I'm not completely sure if translations to English are correct. Hope it's clear.

**Comment by JLCCI** [comment]
+1, though sometimes couple of clicks does the trick. Also the windows does not close after pressing the button (unless it should not?).

**Comment by GladOSkar** [comment]
This also always applies when using Dunst as Notification Daemon (e.g. on i3)

**Comment by ikeydoherty** [comment]
Yeah something went janky along the way because this used to work once upon a time

**Comment by JoshStrobl** [comment]
This issue was resolved as of https://git.solus-project.com/packages/solus-sc/commit/?id=e520ec78cfc613ddc91d270893f681cafdb7434a

**Comment by Pokey1Kenobi** [comment]
dead link

**Comment by chifreagle** [comment]
@Pokey1Kenobi  they moved the "Solus Development Portal" from[ git.solus-project.com](git.solus-project.com) to [dev.solus-project.com ](dev.solus-project.com )
