### ISSUE TITLE
Budgie Panel Visual Bug - Applet Info Bulle

### ISSUE THREAD

**Issue by hmasmoudi** [budgie-desktop/budgie-desktop#836]
**Operating System**: SyphaxOS 2.0.0
**Budgie version**: Budgie 10.2.9

**The issue encountered**
When task bar is placed in the button, applet Info Bulle are displayed for short time on the top of Sceen,Then it is displayed correctly on the buttom of screen.

**Steps to reproduce the issue**
1- Log in to Budgie Session,
2- Place taskbar in the bottom of Screen,
3- Try to click to clock applet, or any applet,
4- The issue will be visible

 ...

**Comment by hmasmoudi** [comment]
Issue visible in this video : https://app.hyfy.io/v/abyDCl6Uh9/

**Comment by fossfreedom** [comment]
Thanks for reporting this.  It is a known issue and as such we'll close this as a duplicate. https://github.com/budgie-desktop/budgie-desktop/issues/292
