### ISSUE TITLE
Wrong icons on panel when apps are open

### ISSUE THREAD

**Issue by jjcazau** [budgie-desktop/budgie-desktop#838]
**Operating System**: Solus 2017.01.01.0
**Budgie version**: 10.2.9

**The issue encountered**

Budgie-desktop / panel displays wrong icon on some apps if they are running but shows themed icon when they are not running and pinned. 

Eg: Play on linux / wine office applications are themed with a certain icon but when they run the icon changes to the default windows icon. 

Another eg: chrome displays the correct icon but when an extension opens in another window, the default chrome icon is displayed. 

**Steps to reproduce the issue**
Pin Google Chrome. Open chrome, open an extension that opens in a new window. 

Run a play on Linux

![budgie icon bug](https://cloud.githubusercontent.com/assets/10113231/24485186/54954d22-154e-11e7-8dba-2072352a358a.png)
 wine app with a custom icon pinned. when the app opens the icon changes.

**Comment by Jazqa** [comment]
I have this issue with all .desktop files for which I've manually changed the icon. The custom icons are working on the menu but not on the panel, unless pinned.

**Comment by ikeydoherty** [comment]
It's not displaying the "wrong" icon. It's displaying the icon that the application told it to.

**Comment by ikeydoherty** [comment]
We try to stop some things from overriding but it can break user expectations when the icon doesn't change for previews for EOG, or the current selection in GNOME Control Center, etc. It needs some more thinking on my part :]

**Comment by jjcazau** [comment]
Hmm thats a good point. How do other distros solve this, do they have a white list of applications allowed to change the icon. If so that just creates problems for apps not on the list. Maybe have a flag in the desktop shortcut file to not allow icon changing, but im not sure if that would go against some sort of desktop environment standards that also use the files.

**Comment by ikeydoherty** [comment]
It's not a distro thing its a DE thing :) It's also not mandated by any spec. My assumption is that GNOME and such just ignore icon changes if they manage to grab it from a .desktop file

**Comment by jjcazau** [comment]
Decisions, decisions. Ill let you think about it. Its a pretty minor visual bug to be honest. Hasn't really bugged me too much.

**Comment by ikeydoherty** [comment]
Closing as opinion - we have a forced set of logic to allow overwrites where needed
