### ISSUE TITLE
Package "budgie-desktop" should recommend "budgie-welcome" (+autostart)

### ISSUE THREAD

**Issue by spectas** [budgie-desktop/budgie-desktop#845]
Hi everyone and thanks for this great desktop!

Having installed "budgie-desktop" via ppa (http://www.webupd8.org/2016/03/how-to-install-budgie-desktop-in-ubuntu-ppa.html), the first impression was a bit disappointing. Everything looked very gray and Win95-esque. Why? Because the Budgie themes were missing and the default settings weren't set - Things, the "budgie-welcome" application does greatly, as I found out later.

I suggest therefore:
- let package  "budgie-desktop"  recommend to install "budgie-welcome" too
- while installing "budgie-welcome" put it as autostart for the next login

Imho users would have a much easier access to Budgie like this.

Thank you again!
Spectas

_My configuration:
budgie-desktop 10.2.9
budgie-welcome 0.4.3.1
Linux kernel 4.4.0-53-generic
Linux Mint 18.1. Serena (Xenial)_

**Comment by ikeydoherty** [comment]
Uhm. This isn't a Budgie issue, this is an issue for the Ubuntu/Debian package maintainers :)
Budgie itself is distro agnostic.

Roping in @fossfreedom :)

**Comment by fossfreedom** [comment]
aye!

  random instructions from blogs.  The correct instructions to install and theme budgie-desktop on Ubuntu is to install the package budgie-desktop-environment

budgie-desktop is the GUI environment and is up-to-you to theme and iconise stuff.  At least that is how Debian expects to-do stuff.

budgie-desktop-environment will do as you suggest - autostart budgie-welcome, theme, apply a good icon-set.

**Comment by ikeydoherty** [comment]
Awesomeness abound - thanks @fossfreedom :)

**Comment by spectas** [comment]
Thanks for this quick response. Great!
