### ISSUE TITLE
"budgie-welcome" installation routines fail

### ISSUE THREAD

**Issue by spectas** [budgie-desktop/budgie-desktop#846]
Hello everyone,
the package "budgie-welcome" comes with the great feature to recommend installing applications and for example the (missing) standard themes Arc/Moka. Unfortunately, these installation links do not work (at least with my system configuration). It looks like they are linked to one software center app, but crash with a notification (e.g.: "Welcome app: Failed installation of arc-theme") when this app is missing.

Imho it would be good to use a more abstract approach to installing apps. Imho this could be done by using "sudo apt-get install arc-theme". If not preferred (e.h. for user convenciance reasons) this might be a fall back solution if budgie-welcome cannot find the preferred sofware center application. 

Thanks a lot for this great desktop!!
Spectas

_My configuration:
budgie-desktop 10.2.9
budgie-welcome 0.4.3.1
Linux kernel 4.4.0-53-generic
Linux Mint 18.1. Serena (Xenial)_

**Comment by fossfreedom** [comment]
This is not a budgie-desktop issue - it is ubuntu specific and as such I will close this. Ubuntu specific issues go here - https://github.com/UbuntuBudgie/budgie-welcome.

**Comment by spectas** [comment]
Thank you for the quick response!

It sent in the bug report there. https://github.com/UbuntuBudgie/budgie-welcome/issues/108
