### ISSUE TITLE
Battery Remaining stuck at 60% on budgie-desktop while ACPI -v shows much lower

### ISSUE THREAD

**Issue by Archerious** [budgie-desktop/budgie-desktop#847]
**Operating System**: Arch Linux
**Budgie version**: budgie-desktop 10.2.9

**The issue encountered**

Battery output stuck at "60%" even on a brand new battery. ACPI -v in terminal gives: 36% as shown here. 

http://i.imgur.com/NIGu7CN.png

![acpi -v 36% but budgie-desktop shows 60%](https://cloud.githubusercontent.com/assets/26941475/24846906/15d259ec-1dad-11e7-9e4f-4c38d9a9123e.png)

Even if I charge overnight, same occurance. I do not encounter this issue in MATE or i3status. Reboots do not fix issue.

**Steps to reproduce the issue**

Use budgie-desktop on Thinkpad X220 or X230. My work Dell XPS 15 9550 is also affected.

Am using a one week old battery on X220, older battery was likely fine just affected by the same bug which led me to spen $77 on a battery for no reason ;(.
 ...

**Comment by ikeydoherty** [comment]
Please make sure you have latest upower update in Arch Linux and re-test. upower stable version is broken and must be patched/up to date

**Comment by JoshStrobl** [comment]
Given lack of response from original poster and this appearing to be an issue that'd be resolved by the respective operating system patching upower, marking as resolved.
