### ISSUE TITLE
"Task list" panel applet is not aware of other applets in budgie-panel.

### ISSUE THREAD

**Issue by Open96** [budgie-desktop/budgie-desktop#848]
**Operating System**: Budgie Remix 16.10
**Budgie version**: Budgie 10.2.9 from ubuntu repos

**The issue encountered**
Task list panel applet overlaps with other elements of budgie-panel if it is big enough. I doubt that is intended behavior and I believe that making task switcher aware of its surroundings and resize accordingly would fix that issue.

**Steps to reproduce the issue**

1. Add task list panel applet
2. Open some programs until task list starts overlapping

**Comment by fossfreedom** [comment]
kind of think this is the same or is very similar to this issue: https://github.com/budgie-desktop/budgie-desktop/issues/739

**Comment by Open96** [comment]
That is exactly what I am talking about.

**Comment by ikeydoherty** [comment]
Applets shouldn't be aware of each other at all. They just need better layout management (GtkBox sucks.) Closing as dupe
