### ISSUE TITLE
GNOME 3.24 release

### ISSUE THREAD

**Issue by Mailaender** [budgie-desktop/budgie-desktop#849]
Hi, can you tag a new release for the GNOME 3.24 libmutter vs. libmutter-0 change for @openSUSE Tumbleweeed? It isn't easy to patch as you also changed the build system since version 10.2.9 to meson.

**Comment by ikeydoherty** [comment]
Please follow issue #800 where I'm already tracking the preparation of 10.3

**Comment by jbicha** [comment]
@Mailaender If you're impatient, you could grab the patches from the [Ubuntu package](https://launchpad.net/ubuntu/+source/budgie-desktop). You'll also need https://github.com/budgie-desktop/budgie-desktop/commit/0e8e93799b65e04ebd5fecfedacbd194edd838d7

**Comment by ikeydoherty** [comment]
The main blocker item is the alt+tab, which I put up a bounty for. If someone comes through on that we can do a release of 10.3 this weekend
