### ISSUE TITLE
System Tray Missing Items

### ISSUE THREAD

**Issue by FunOrange** [budgie-desktop/budgie-desktop#851]
**Operating System**: Ubuntu 16.10
**Budgie version**: Budgie 10.2.9 

The only item that shows in my system tray is the network button. I have shutter, steam, alarm clock, and redshift all running in the background, but it's impossible to tell or bring them up since their icons don't show in the system tray.
Sometimes the network button doesn't even show, but other times it does. Its behaviour is unpredictable.

![selection_002](https://cloud.githubusercontent.com/assets/11964109/25060146/6634eeb2-2164-11e7-81bb-d486df5b3b9e.png)

**Comment by ikeydoherty** [comment]
Do you have two of them added? i.e. multiple panels. You can only have one. Also make sure you don't have the indicator applet running too.. Doesn't look like default Ubuntu Budgie setup

**Comment by fossfreedom** [comment]
This is a ubuntu specific problem so I'll close this here - ubuntu specific issues can be raised here.  thanks https://github.com/UbuntuBudgie/budgie-desktop-environment

As to your issue - install the appindicator applet and add to you panel
    
    sudo apt install budgie-indicator-applet

For the sometimes see / sometimes dont network icon, something has gone wrong with your updates - delete the following file and this observation will be resolved

    sudo rm /etc/xdg/autostart/budgie-desktop-nm-applet2.desktop

**Comment by ikeydoherty** [comment]
Ah it was missing instead.. :) Cheers
