### ISSUE TITLE
The new Alt+Tab Switcher is not Centered

### ISSUE THREAD

**Issue by moriel5** [budgie-desktop/budgie-desktop#856]
The  new Alt+Tab switcher is not centered, which is problematic when opening over 25 windows at the same time

As I cannot upload pictures through ForkHub, I am adding a link to the picture I had uploaded from my PC to Phabricator:

https://dev.solus-project.com/file/data/kq6z45xrjjs4mzdfbzzs/PHID-FILE-ugxiz55kusenoktdmaar/Screenshot_from_2017-04-16_11%3A07%3A26.png

I am (like usual) utilizing the unstable repo, and I had made sure that the sysyem is up-to-date right before sending this issue.

**Comment by ikeydoherty** [comment]
BTW what is "forkhub" ? And comments/etc support images on github

**Comment by Flat** [comment]
[Forkhub](https://github.com/jonan/ForkHub) is an android app for github.

**Comment by ikeydoherty** [comment]
Oh :) Learn a new thing every day :D

**Comment by moriel5** [comment]
Yeah, ForkHub is a FOSS GitHub Android client, with no Google Play Services dependencies whatsoever.
