### ISSUE TITLE
Application Menu Tray Widget

### ISSUE THREAD

**Issue by MggMuggins** [budgie-desktop/budgie-desktop#859]
So I'm using unity right now, and there are some things that I really like about it. There are other bits that I don't, and because of the recent announcement that Ubuntu is leaving Unity 8 and going back to GNOME, I started looking for a new DE that would suit my needs. I just don't really like GNOME much at all... Anyway, I've seen some Budgie, and tried out a live USB of Solus, and really like the new clean budgie look. However, there is one thing that I'd like to see as an option in Budgie:
Application menus that are integrated with the DE instead of being underneath the titlebar of each window. I realize that many people like the way it is, and this is only a suggestion. However, I really like having the application menus on the system tray at the top instead of having them a permanent part of the window. It just makes for a cleaner UI in my opinion, and also frees up screen space for the actual application window. If the widget were included in the system tray, then the menus would only appear there, instead of being underneath the titlebar of the window.

**Comment by ikeydoherty** [comment]
So the vala-panel-appmenu actually achieves this. I'll see if I can work with @rilian-la-te at some point on getting the theming and integration right in Budgie out of the box for a 10.3.1, as menubars are unthemed with built-in styling.

**Comment by MggMuggins** [comment]
Thanks so much! I was quite iffy on whether or not something like that would be possible, just for the sake of not having an awkward UI. If this is successfully implemented, I'm completely sold on Budgie :P

**Comment by rawsh** [comment]
If this would happen, I think that there should also be an option to move the entire window controls for maximized windows to the panel, so that the title and controls could be there as well (the way unity does this). This would also save a lot of space on smaller screens.

**Comment by MggMuggins** [comment]
I feel like budgie is gaining a following from Unity-lovers who don't like Gnome...

**Comment by fossfreedom** [comment]
For the window controls issue there is this https://github.com/ilgarmehmetali/budgie-pixel-saver-applet

**Comment by ikeydoherty** [comment]
This stuff already exists out of tree

**Comment by rilian-la-te** [comment]
I am waiting for correct CSS for my appmenu applet:) Because I am too busy now to write it myself (and Budgie is not my primary target).

**Comment by ikeydoherty** [comment]
@rilian-la-te and if *you're* too busy, what does that make me? :) I've pinged you an number of times on GitHub about this, long story short its very hard for me to recommend your applet when there is no effort to get any improvements in upstream Budgie, and from your own words Budgie isn't a priority.

**Comment by rilian-la-te** [comment]
I will consider it eventually, as @fossfreedom write a good CSS, but with issues (plagues all panel menuitems).
I will rework this CSS and integrate it into Budgie applet.

About upstreaming - no, I will not made my applet Budgie upstream, because it is primary a vala-panel applet, budgie was done, because it is similar. Core part is DE-independent and can be run even in arbitrary window.

**Comment by rilian-la-te** [comment]
But anyone in Budgie-panel uses menuitems in applets?

**Comment by ikeydoherty** [comment]
Budgie uses popovers, so there is no menubar styling built in at present.
I also didn't ask you to upstream the applet, just the fixes required to make the applet run. As it stands it doesn't actually work out of the box with default built-in theming.

**Comment by rilian-la-te** [comment]
How to monitor built-in budgie theme setting? Is there a public API to do it?

**Comment by rilian-la-te** [comment]
To disable built-in styling, when proper theme is using (not internal)

**Comment by ikeydoherty** [comment]
@rilian-la-te would it not make more sense for it to just exist in the git master so that individual themes can then override it? I'm fine with it being there. When I get a second to poke I'll see if there is an easy way to copy it across, as the menu styling will be very similar to the popover styling.

**Comment by rilian-la-te** [comment]
Can you test latest update with @fossfreedom patch? With and without proper theme, please:)

**Comment by fossfreedom** [comment]
@rilian-la-te sure - I'll do that tonight. cheers

**Comment by ikeydoherty** [comment]
So now there are *2* out of tree applets with their own CSS styling for menubars..

**Comment by rilian-la-te** [comment]
What is other 2? Sntray does not have menubars style (but if will, it will also have style from appmenu)

**Comment by rilian-la-te** [comment]
So, it seems 2 out of 4:) Because I have 2 applets, and both uses menubars:)))

**Comment by ikeydoherty** [comment]
So it's probably about time to have a standard base level for the menu styling in Budgie :P

**Comment by MggMuggins** [comment]
Sorry for interupting this, but what do you mean by "out of tree"? I'm not sure I understand...

**Comment by ikeydoherty** [comment]
Well. Not in this git tree.

**Comment by fossfreedom** [comment]
Ikey - I'm kind of doing this with zero knowledge ... got this far - managed to screw up the labels in Raven though.  Thoughts?

![ubuntu budgie - new development running - oracle vm virtualbox_011](https://cloud.githubusercontent.com/assets/996240/25642909/ae7d21b0-2f94-11e7-975e-c29e396ac282.jpg)

added the following to _main.scss

```
%reset_style,
 menubar {
    menuitem {
        padding: 4px 8px;
        border: solid transparent;
        border-width: 0;
        }
    
    menuitem:hover {
        background-color: $selected_bg_color;
        color: $fg_color; 
        }

    menuitem:disabled {
        color: rgba(207, 218, 231, 0.2);
        border-color: transparent;
        }
        
    menuitem label {
        background: none;
        color: $fg_color;
        }
    }

%reset_style,
  menu {
    margin: 4px;
    padding: 5px;
    border-radius: 0;
    background-color: rgba(53,57,69,0.93);
    menuitem:hover {
        background-color: $selected_bg_color;
        color: $fg_color; 
        }
    
    arrow {
        border:none;
        min-width:16px;
        min-height:16px;
        }

    arrow.top {
        -gtk-icon-source:-gtk-icontheme("pan-up-symbolic");
        border-bottom:1px solid rgba(76,79,90,0.937);
        }

    arrow.bottom {
        -gtk-icon-source:-gtk-icontheme("pan-down-symbolic");
        border-top:1px solid rgba(76,79,90,0.937);
        }

    menuitem accelerator {
        color: transparentize($fg_color, 0.65);
        }
        
    menuitem check, menuitem radio {
        min-height: 16px;
        min-width: 16px; 
      }
    }
```

**Comment by JaneSmith** [comment]
Is it possible for Budgie to have the application menus drawn inside the window titlebars? That is what I expected this thread to be about originally, but it seems to be about global menus instead. Unity offered a non-default option where the menu could be drawn inside the titlebar, saving vertical space. KDE Plasma also supports this.

http://fasterland.net/activate-global-menu-kde-plasma-5-9.html
https://farm8.staticflickr.com/7290/12657295614_502f95ef46_o.png
