### ISSUE TITLE
Cannot move windows to second monitor if it has to pass a panel

### ISSUE THREAD

**Issue by adrianloy** [budgie-desktop/budgie-desktop#868]
Hello!

**Operating System**: Ubuntu 17.04 (Budgie Flavour)
**Budgie version**:  budgie-desktop 10.2.9
**The issue encountered**

I use a laptop with an external monitor attached. In my setup, the second monitor is above my laptop screen and I would also like to configure them like this in the settings. However, that means that moving a window from my laptop screen to the monitor screen, it would have to go through/above the top panel on my laptop screen, which is the primary screen. As far as I can see, this is currently not possible. I therefore cannot move windows to my monitor screen.

**Steps to reproduce the issue**

Attach a second monitor, arrange it above the primary screen, which has to have a top panel.

P.S.: Cool project

**Comment by fossfreedom** [comment]
Thanks for raising the issue

This is a duplicate - https://github.com/budgie-desktop/budgie-desktop/issues/648.

I'll mark it as such.
