### ISSUE TITLE
Would like a simple way to enable Wake-on-LAN for a NIC

### ISSUE THREAD

**Issue by Timalex** [budgie-desktop/budgie-desktop#877]
A simple switch button would make this a lot easier for users to enable.
_I believe it should be easy for users to fully utilize their hardware_

It was previously mentioned on [Phabricator](https://dev.solus-project.com/T515)

**Comment by ikeydoherty** [comment]
Sorry, this is out of scope for Budgie and is a GNOME Control Center issue
