### ISSUE TITLE
Currently selected window is not highlighted with alt+tab window switcher.

### ISSUE THREAD

**Issue by niyasc** [budgie-desktop/budgie-desktop#878]
**Operating System**: budgie-remix 16.04.x (Using Gtk 3.18.x)
**Budgie version**: Budgie 10.3.1

I'm using budgie 10.3.1 from budgie-remix proposed repositories. The problem is, atl+tab window switcher is not highlighting current selection. In [original release announcement](https://budgie-desktop.org/2017/04/19/release-of-budgie-10-3/) of 10.3, current selection is highlighted.

![screenshot from 2017-04-22 19-43-58](https://cloud.githubusercontent.com/assets/2451833/25305208/a2b844d4-2794-11e7-84c2-05254a8b23ec.png)

**Inferences**
As pointed out by @fossfreedom in an issue created with ubuntu budgie fork of budgie desktop, the problem is apparently associated with theming in Gtk prior to 3.20.

This [commit](https://github.com/budgie-desktop/budgie-desktop/commit/e6be8db7024c86f0e29a801e5ffca6176c9e697f) has made changes for alt+tab theming. Apparently, it is using css classes `.flowbox` and `.flowbox-child` instead of `GtkFlowBox` and `GtkFlowBoxChild`.

I just want to confirm if it is the actual issue. Where does the generated css files goes after installing `budgie-desktop`? Can we see theme separate files or are they embedded in any libraries?

**Comment by ikeydoherty** [comment]
They're cooked into the libraries yeah, lemme try and get a fix for it

**Comment by ikeydoherty** [comment]
^ Both commits will be needed

**Comment by niyasc** [comment]
Just updated, and it is working now :+1:

**Comment by ikeydoherty** [comment]
Lemme know when you guys are ready to sign off on the current changes and we'll do a 10.3.2 so it can be a candidate for deb upload.
