### ISSUE TITLE
reducing the number of workspaces crashes the window manager

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#881]
**Operating System**: Ubuntu 17.04
**Budgie version**: 10.3.1

mutter = 3.24

**The issue encountered**

using dconf or gnome-tweak-tool - if you reduce the number of workspaces - for example, from 4 to 3 the window manager crashes
 
Would appreciate if someone can confirm this.

**Comment by JoshStrobl** [comment]
Duplicate of #504.
