### ISSUE TITLE
Placing windows buttons on left side causes inconsistent order

### ISSUE THREAD

**Issue by N-ckOH** [budgie-desktop/budgie-desktop#882]
Operating System: Solus 2017.04.18.0 64-bit
Budgie version: 10.3.1

**The issue encountered**

When changing the window button layout to left the window buttons become inconsistent in order for different apps.  For example FireFox is ordered (left to right) : Close, Maximize, Minimize.  And Nautilus is ordered : Close, Minimize, Maximize.

**Steps to reproduce the issue**

Open Raven and go to settings.  Under Windows setting change Button Layout to 'Left'.

**Comment by niyasc** [comment]
Does [this commit](https://github.com/budgie-desktop/budgie-desktop/commit/a4373614d7454a4ed6bb24ac9657c3535240d943) causes the mentioned issue?

    case ButtonPosition.LEFT:
        xset = this.new_filtered_xsetting("close,minimize,maximize,menu:");
        wm_set = "close,maximize,minimize,appmenu";
        break;

**Comment by ikeydoherty** [comment]
Derp. Mah bad :P TBF they're still on the left ... xD
