### ISSUE TITLE
Clicking the top left corner for opening menu inconvenience

### ISSUE THREAD

**Issue by haiderrehmanbutt** [budgie-desktop/budgie-desktop#883]
Operating System: Solus 2017.04.18.0 64-bit
Budgie version: 10.3.1

Steps to reproduce:

When clicking the menu, if cursor reaches the top left corner, the menu can not be selected, you have to move the cursor on the button. It is a minor inconvenience but frustrating.

**Comment by ikeydoherty** [comment]
Works here. Do you have any spacer applets added before the menu?

**Comment by haiderrehmanbutt** [comment]
Hi! Spacer was placed before the menu. Issue fixed. :)

**Comment by ikeydoherty** [comment]
Oh cool :)
