### ISSUE TITLE
Timesyncd will not work on Solus/budgie Vmware VM (and neither will vmware tools time sync.

### ISSUE THREAD

**Issue by jsamyth** [budgie-desktop/budgie-desktop#885]
**Operating System**: VERSION="2017.04.18.0"
**Budgie version**: budgie-desktop 10.3.1
Vmware Workstation Virtual Machine

**The issue encountered**

Upon Resume suspended machine, time does not update.
None of the GUI settings work to correct this.
A reboot is necessary to get the current time updated automatically.

systemd-timesyncd.service is set ConditionVirtualization=no
however solus/budgie does not ship necessary modules for 
host/vm time synchronization.

Temporary fix
Comment ConditionVirtualization=no in systemd-timesyncd.service 
time sync service then continues to run keeping clock synced.

 ...

**Steps to reproduce the issue**
Suspend VM
Wait some time.
Resume VM
Notice time is unsynced.

 ...

**Comment by fossfreedom** [comment]
This is perhaps the wrong tracker for this issue.  Suggest file this on phabricator - https://dev.solus-project.com/

**Comment by frojack** [comment]
I did my part.  You can certainly forward it to the right desk without me having to chase it all over the internet.
  
Solus/Budgie is the only distro that behaves this way under Vmware.  I've got about 8 distros running in VMs.

**Comment by ikeydoherty** [comment]
? You're not the OP, so as far as I can see you did nothing.
And I seriously doubt it's the only case, as its part of the systemd unit, from upstream. Lastly, it's definitely the wrong tracker, as Budgie isn't a distro.

**Comment by ikeydoherty** [comment]
(To whomever *IS* the OP - I'll make sure the relevant RTC modules are enabled for virtualisation.)
