### ISSUE TITLE
Error on boot for 17.04

### ISSUE THREAD

**Issue by makitso** [budgie-desktop/budgie-desktop#887]
During the boot sequence, after the login, this message appears.  It happens on the 17.04 release .iso during the install and also after during normal boot.  System is Thinkpad T60.

/scripts/init-button/plymouth: line 18 /bin/plymouth not found

**Comment by ikeydoherty** [comment]
Please note that Budgie Desktop is a separate upstream, distro agnostic project.
Ubuntu Budgie, the Linux distribution, should report issues on launchpad: https://launchpad.net/ubuntubudgie

Closing and pinging @fossfreedom

**Comment by fossfreedom** [comment]
yep- known - https://github.com/UbuntuBudgie/budgie-artwork/issues/13 - fixing for 17.10
