### ISSUE TITLE
[Feature Request] Multi monitor Plank

### ISSUE THREAD

**Issue by DaRo0** [budgie-desktop/budgie-desktop#888]
Hello, everybody!

I've looked online for a solution for this without succeeding, so yeah, that's a feature request for a multi-monitor capability for the Plank bar.

Thank you for this awesome distro!

Regards,
Daniel

**Comment by ikeydoherty** [comment]
Hi. Budgie is not a distro, it's a distro agnostic desktop environment originally created for Solus, now adopted in multiple distros.

Plank is from the elementary project, not from Solus, or Budgie, so this should either go upstream to your relevant distro (please actually follow our issue template, don't delete it, it's there for a reason) or to the Plank developers.

Thanks. Also people opening issues to Budgie Desktop for Ubuntu Budgie is getting old now.

**Comment by paulalbertheliopsis** [comment]
Try multiplank maybe ?
And configure each plank with "plank --configure -n THENAMEOFTHEINSTANCE"
THENAMEOFTHEINSTANCE is the name of a folder inside ~/.config/plank/
