### ISSUE TITLE
Mouse crash

### ISSUE THREAD

**Issue by Zlobarq** [budgie-desktop/budgie-desktop#889]
When reporting issues for Budgie Desktop, ensure you read these guidelines and delete this first
introductory paragraph. If including build failures, or general tool output, please ensure they are
in English, i.e. `LC_ALL=C LANG=C`. If your issue is a Budgie *crash*, include a stack trace. (gdb)

**Operating System**: e.g. Solus 1.2.0.5
**Budgie version**: i.e. Budgie 10.2.7 OR specific git commit

Before submitting *ANY* issue, please run the following command to
verify that you have, at minimum, Budgie `10.2.7`, to provide the
exact version of your Budgie installation:

    budgie-desktop --version

**The issue encountered**

 ...

**Steps to reproduce the issue**

 ...

**Comment by fossfreedom** [comment]
Sorry - no information here to help.  Please do look at the template in the future and fill in the details.  Especially the bit about supplying a gdb stack trace for a  budgie desktop crash.
