### ISSUE TITLE
Crossover (possibly Wine also) Steam application weird behaviour in System Tray

### ISSUE THREAD

**Issue by hogar1977** [budgie-desktop/budgie-desktop#891]
**Operating System**: Antergos 2017.04 (fully updated)
**Budgie version**: Budgie 10.3.1

**The issue encountered**

 I use Crossover and I installed a Windows Steam client with it. When started it creates an icon in the system tray and that is where the fun starts. When I right click the icon to access the context menu the icon moves to the left. After several right clicks the icon is already on the leftmost side of the top panel.
I do not encounter such behaviour in other DEs, so it is not Crossover (Wine) issue per se. But it could be related to how Budgie interprets the processes related to Crossover (Wine) applications (there are many spawned processes, etc...). It is not a big issue but it looks weird and it hampers the usability :-/

**Steps to reproduce the issue**

Well, try to install the trial version of Crossover and then windows Steam client and run it, then right click the Steam system tray icon and see if it will move left or not...
_______________________________________________________________________________
Other than that just keep doing what you're doing. I love what you guys have done until now with Budgie and I hope it just gets better from here... If the official repo of apps grows I think I'm gonna switch to Solus :-) I didn't have this much enthusiasm about an operating system for a long time :-) Thumbs up for doing things from scratch!

**Comment by hogar1977** [comment]
Just ignore it.. I reinstalled budgie and now it behaves properly (no moving of icons...) But maybe someone will still encounter this :-/

**Comment by ikeydoherty** [comment]
I blame Time Jesus.
