### ISSUE TITLE
Desktop icons

### ISSUE THREAD

**Issue by lchaussard** [budgie-desktop/budgie-desktop#901]
Hi, is it possible to hide some of the desktop icons? For example, I want to hide only the trash bin icon and keep the home icon. Is there file that I can edit and change that? Thanks.

**Comment by ikeydoherty** [comment]
This is down to Nautilus's own settings. You can use GNOME Tweak Tool to change them (Desktop tab)

**Comment by lchaussard** [comment]
Thanks.
