### ISSUE TITLE
Desktop background and icons appear on startup, then disappear after a few seconds

### ISSUE THREAD

**Issue by AlexMCrick** [budgie-desktop/budgie-desktop#904]
I am running Budgie version 10.3.1 on Ubuntu 16.04

**I have edited this since posting**

It seems as though the problem is with the default files application. When I open it it closes almost immediatley and my desktop items are still not showing but a different file manager (thunar) works perfectly fine. Is this something I can fix myself?

Thanks

**Comment by fossfreedom** [comment]
Doesn't really sound like a budgie desktop issue. Sounds like nautilus is crashing for some reason. If you switch off desktop icons via raven does the problem still occur?

**Comment by AlexMCrick** [comment]
I turned off desktop icons in raven settings and the files application no longer crashes. Having desktop icons isn't a big deal but I was just wondering what the cause could be.

**Comment by ikeydoherty** [comment]
This is a Nautilus issue on Ubuntu, gonna close it to clear up the tracker (Doesn't pertain to Budgie)
