### ISSUE TITLE
Editing the built-in theme

### ISSUE THREAD

**Issue by lchaussard** [budgie-desktop/budgie-desktop#907]
Hi, I would like to edit the built-in theme, specifically the icon sizes of the budgie-panel, but i didn't find the folder in the /usr/themes path. Where is it located? Thanks.

**Comment by niyasc** [comment]
You can a file in home directory with name `/.config/gtk-3.0/gtk.css` and add custom styles inside that.

**Comment by ikeydoherty** [comment]
Icon sizes are controlled by code, not CSS
