### ISSUE TITLE
Window button layout not saved after restart

### ISSUE THREAD

**Issue by marek287** [budgie-desktop/budgie-desktop#908]
Operating System: Arch Linux
Budgie version: budgie-desktop 10.3.1

If I have changed this settings buttons are left side.
gsettings set com.solus-project.budgie-wm button-layout 'close,minimize,maximize:appmenu'
After restart buttons are back right side for some apps (Firefox, Telegram, Atom).

**Comment by fossfreedom** [comment]
can I ask why you are setting it directly?  What happens if you use the raven option to switch left and right?

**Comment by marek287** [comment]
I even didn't know that this settings is now in raven option. I have been using this command long time (Budgie Desktop Arch Wiki).
