### ISSUE TITLE
Large icons on some windows

### ISSUE THREAD

**Issue by rawsh** [budgie-desktop/budgie-desktop#913]
```
[robert@rawlinux ~]$ budgie-desktop --version
budgie-desktop 10.3.1
Copyright © 2014-2017 Ikey Doherty, Solus Project
```
![](http://i.imgur.com/xbc8ksT.png)

**Comment by ikeydoherty** [comment]
Please update your icon themes :) (Notice it won't happen with latest Moka, etc.)

**Comment by rawsh** [comment]
Cool, thanks. I was on papirus

**Comment by ikeydoherty** [comment]
Is it fixed in latest Papirus? If not we could all go talk to them.. :D

**Comment by rawsh** [comment]
@ikeydoherty Nope, I'm on the latest in that screenshot

**Comment by rawsh** [comment]
@ikeydoherty I added an issue to Papirus :)

**Comment by ikeydoherty** [comment]
Ta :)

**Comment by ikeydoherty** [comment]
Now tracking in https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/453
