### ISSUE TITLE
Keyboard Captured During Unlock

### ISSUE THREAD

**Issue by MggMuggins** [budgie-desktop/budgie-desktop#914]
**Operating System**: Manjaro Latest
**Budgie version**: 10.3.1

**The issue encountered**
Alright, so I was installing an iso of another distro in a VM, which apparently captured my keyboard. I left it for a bit to go do something else, and when I came back (as expected), the monitor had gone to sleep. However, when I tried to unlock the machine, I couldn't, because the VM was holding my keyboard, and of course budgie did not allow me to use it to log back in.

**Steps to reproduce the issue**
Open up a VM of any distro you want (Oracle VM), and let the machine lock itself. Then try and sign back in...

I'm not 100% sure that this is the right place to put this, but I figured it was the most likely. Feel free to close if it isn't a budgie issue.

**Comment by ikeydoherty** [comment]
Sorry, the problem is gnome-screensaver itself. We want to replace it, and we're open to suggestions (just not deadtech like lightlocker pls.) - can't fix this in Budgie :(

**Comment by MggMuggins** [comment]
Alright, well thanks for the info anyway. Can't wait for budgie 11!
