### ISSUE TITLE
No keyboard option for shift+alt+tab

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#917]
**Operating System**:  Solus 2017.04.18.0
**Budgie version**: 10.3.1

**The issue encountered**
This is technically a feature request, but I'm not sure how to tag it as such. Anyway, most operating systems have a way to go backwards (shift+alt+tab) as well as forwards (alt+tab) in the task list. I don't see any way to enable the former in the keyboard settings menu.

**Steps to reproduce the issue**
Hit alt+tab to switch tasks. You can only move to the right, not the left.

 ...

**Comment by vanitasvitae** [comment]
Came to this repository to create a feature request for exactly this 👍

**Comment by sidahmed-malaoui** [comment]
It looks like this feature was implemented in `budgie-desktop 10.4`.

**Comment by fossfreedom** [comment]
cheers for the confirmation!

**Comment by ohot2015** [comment]
up

**Comment by ComputingFroggy** [comment]
It is not working on budgie desktop 10.5.1-6 on Ubuntu Budgie 20.04 !
