### ISSUE TITLE
Segfault on GTK 3.22.13+

### ISSUE THREAD

**Issue by FredDeschenes** [budgie-desktop/budgie-desktop#918]
**Operating System**: Arch Linux
**Budgie version**: 10.3.1 (happens for both the official package in "community" and "budgie-desktop-git v10.3.1.r1.g932cd0c-1" from AUR)

**The issue encountered**
`budgie-panel` segfaults as soon as opened. This started happening this morning following a system upgrade.

Backtrace from the coredump (I can provide the coredump if you want too) : 

``` 
0  0x00007f0e62d98b8f in budgie_raven_set_notification_count () at /usr/lib/libraven.so.0
1  0x00007f0e62d90894 in  () at /usr/lib/libraven.so.0
2  0x00007f0e62d955b9 in budgie_notifications_view_construct () at /usr/lib/libraven.so.0
3  0x00007f0e62d8fcf8 in budgie_main_view_construct () at /usr/lib/libraven.so.0
4  0x00007f0e62d98e69 in budgie_raven_construct () at /usr/lib/libraven.so.0
5  0x000000000040e192 in budgie_panel_manager_on_name_acquired ()
6  0x00007f0e5aebb1c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
7  0x00007f0e5aebac2a in ffi_call () at /usr/lib/libffi.so.6
8  0x00007f0e618667ae in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
9  0x00007f0e61865f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
10 0x00007f0e61b6dffd in  () at /usr/lib/libgio-2.0.so.0
11 0x00007f0e61b6e306 in  () at /usr/lib/libgio-2.0.so.0
12 0x00007f0e61b6e548 in  () at /usr/lib/libgio-2.0.so.0
13 0x00007f0e61b326b3 in  () at /usr/lib/libgio-2.0.so.0
14 0x00007f0e61b33176 in  () at /usr/lib/libgio-2.0.so.0
15 0x00007f0e61b65ffa in  () at /usr/lib/libgio-2.0.so.0
16 0x00007f0e61b326b3 in  () at /usr/lib/libgio-2.0.so.0
17 0x00007f0e61b326e9 in  () at /usr/lib/libgio-2.0.so.0
18 0x00007f0e6158c66a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
19 0x00007f0e6158ca20 in  () at /usr/lib/libglib-2.0.so.0
20 0x00007f0e6158cd42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
21 0x00007f0e6268eea5 in gtk_main () at /usr/lib/libgtk-3.so.0
22 0x000000000040adb9 in _vala_main ()
23 0x00007f0e6063f511 in __libc_start_main () at /usr/lib/libc.so.6
24 0x000000000040ab4a in _start ()
```

[I have also attached the list of packages that were upgraded by the system upgrade that caused the issue to start happening.](https://github.com/budgie-desktop/budgie-desktop/files/990661/updates.txt)

**Steps to reproduce the issue**
- Start `budgie-panel` with either a display manager (I use `gdm`) or `budgie-panel --replace`
- It segfaults

Everything else seems to work fine after this though (can still start apps with Alt-F2, etc)

I'm afraid that's as far as my debugging skills go, but if there's anything you want me to try or logs you want me to provide I can definitely do that.

Thanks!

**Comment by fossfreedom** [comment]
Highly likely that this is due to an upstream issue here - https://bugzilla.gnome.org/show_bug.cgi?id=782453

Suggest you rollback your GTK upgrade for the moment.

**Comment by FredDeschenes** [comment]
Yup that looks like it, I hadn't even noticed the clipboard was broken. Downgrading `gtk3` did indeed fix the issue, thanks! Should I close this or leave it open until the upstream issue is fixed in case anyone else has the same issue?

**Comment by rilian-la-te** [comment]
I have:-)

**Comment by vanitasvitae** [comment]
Same issue here.

**Comment by JoshStrobl** [comment]
Working on tracking down the commit that could have caused segfaulting and have determined that the following GTK3 commits are *likely* to **not** have been the issue:

- https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=0a7151b22eb6b767948a9763410f878b28b68ec7
- https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=4496c5388b913db9288563618f69d35ae8dbf5b6
- https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=f3f71ef0ac49612912b91f700fa011d79ddb3488
- https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=c05c78f9c96341b211655bc652f569df0fb43bb1
- https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=001fa0a8101f9445a3631518432d9ded0b861088

**Comment by JoshStrobl** [comment]
Updated title to reflect that GTK 3.22.14 has been released and while that resolves an upstream issue with clipboard, it doesn't resolve segfaulting (*didn't expect it to, to be fair*).

**Comment by JoshStrobl** [comment]
I have discovered that the following commits causes budgie-panel to segfaults: `listbox: Properly remove placeholders` https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=b7fdc5b447b44b5b7638a3ac41cac58136bc5ca2

Did a revert, with the below patch comments, against GTK3 3.22.14 (should work with .13):

```
From 773bdc233434ab0a52ba1a712b13088c36144edd Mon Sep 17 00:00:00 2001
From: Joshua Strobl <joshua@stroblindustries.com>
Date: Wed, 10 May 2017 23:24:04 +0300
Subject: [PATCH 1/1] Revert "listbox: Properly remove placeholders"

This reverts commit b7fdc5b447b44b5b7638a3ac41cac58136bc5ca2.
---
 gtk/gtklistbox.c | 12 +-----------
 1 file changed, 1 insertion(+), 11 deletions(-)

diff --git a/gtk/gtklistbox.c b/gtk/gtklistbox.c
index 2bc6bfde43..f16e02aff8 100644
--- a/gtk/gtklistbox.c
+++ b/gtk/gtklistbox.c
@@ -2451,16 +2451,6 @@ gtk_list_box_remove (GtkContainer *container,
 
   was_visible = gtk_widget_get_visible (child);
 
-  if (child == priv->placeholder)
-    {
-      gtk_widget_unparent (child);
-      priv->placeholder = NULL;
-      if (was_visible && gtk_widget_get_visible (widget))
-        gtk_widget_queue_resize (widget);
-
-      return;
-    }
-
   if (!GTK_IS_LIST_BOX_ROW (child))
     {
       row = g_hash_table_lookup (priv->header_hash, child);
@@ -2542,7 +2532,7 @@ gtk_list_box_forall (GtkContainer *container,
   GSequenceIter *iter;
   GtkListBoxRow *row;
 
-  if (priv->placeholder != NULL)
+  if (priv->placeholder != NULL && include_internals)
     callback (priv->placeholder, callback_target);
 
   iter = g_sequence_get_begin_iter (priv->children);
-- 
2.12.2
```

**Comment by ikeydoherty** [comment]
OK so one imagines this is all going to be down to the Raven notification list, it's doing something that it doesn't like. Quite likely - it's now being allowed to murder the placeholder and yet will still access it later. Digging locally.

**Comment by ikeydoherty** [comment]
See fix in https://github.com/budgie-desktop/budgie-desktop/commit/b07359f5c14185126ac6d780c44b25fe325c2cba - should apply cleanly to current 10.3.x tarballs

**Comment by ikeydoherty** [comment]
Given that I was already using the "proper" pattern for accessing GtkListBox internals, don't be surprised if you see this GTK issue impact some GTK3 applications too.

**Comment by FredDeschenes** [comment]
Thanks for the quick fix! I'll try this tomorrow on my work laptop.

**Comment by ikeydoherty** [comment]
I stuck out all the gory details in a G+ post in case anyone else gets taken by surprise: https://plus.google.com/+IkeyDoherty/posts/hbPVVLpvm7i - saves fumbling around in the dark

**Comment by ikeydoherty** [comment]
Raised upstream in https://bugzilla.gnome.org/show_bug.cgi?id=782494

**Comment by Mailaender** [comment]
I can confirm that https://github.com/budgie-desktop/budgie-desktop/commit/b07359f5c14185126ac6d780c44b25fe325c2cba fixes the problem on @openSUSE Tumbleweed: https://build.opensuse.org/request/show/500938

**Comment by ikeydoherty** [comment]
The alternative is a newer GTK :)
