### ISSUE TITLE
systemd: multipathd.service entered failed state

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#919]
**Operating System**: 2017.04.18.0
**Budgie version**: 10.3.1

**The issue encountered**

Maybe this isn't a Budgie thing but it doesn't seem to happen on my other Linux distros.

I was looking into systemd behavior which led me to find the following failure buried in dmesg:

systemd[1]: Unit multipathd.service entered failed state.
systemd[1]: multipathd.service failed.

**Steps to reproduce the issue**

Just boot up and search dmesg for "systemd". For that matter there are some other weird messages that come up, although they're not reported as errors and don't relate to this problem.

**Comment by fossfreedom** [comment]
hmm - I'm doubtful this is specifically a budgie-desktop issue.  Maybe report this on solus phabricator?

**Comment by JoshStrobl** [comment]
Yea, this is something that should be submitted on our Phab.
