### ISSUE TITLE
rpath workaround?

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#920]
budgie-desktop 10.3.1

Debian regards the use of rpath as evil - yeah I know various GNOME apps are bad boys as well!

https://wiki.debian.org/RpathIssue

Ignoring the backward compatibility issue - is there a way to compile without using rpath just for GTK+3.22 and later?  If it is possible I'm more than happy to carry that as a specific patch for Debian.

**Comment by ikeydoherty** [comment]
So does Solus, fwiw.  It's put on us because of the upstream Mutter changes. Unless Debian have already formulated a hack for GNOME Shell/Mutter then probably not, no.

**Comment by ikeydoherty** [comment]
Looked, nothing we can do. This is a problem stemming from upstream GNOME and can only be hacked around if the distributions *also* unvendor and thus unrpath the libs in Mutter, and then make GNOME Shell, Pantheon, Budgie, etc, all work with that.

**Comment by fossfreedom** [comment]
Just for fun (weird sense of fun I know)

I changed the meson build to not explicitly set the rpath value (rpath = '') when building budgie-wm.

Then in debian/rules I added this which allowed the linker to resolve:

override_dh_shlibdeps:
    dh_shlibdeps -l"usr/lib/$(DEB_HOST_MULTIARCH)/mutter"

Finally I amended /usr/bin/budgie-desktop:

export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/mutter${LD_LIBRARY_PATH:+:$LD_L
IBRARY_PATH}


The desktop launched ok (no real testing behind that statement).

**Comment by ikeydoherty** [comment]
Sure but thats not really portable and requires custom launcher scripts, and is still basically reliant on a runpath
