### ISSUE TITLE
Can't build git version 

### ISSUE THREAD

**Issue by SapiensAnatis** [budgie-desktop/budgie-desktop#923]
**Operating System**: e.g. Arch 2017.05.01 (kernel 4.10.13-1-ARCH)
**Budgie version**: https://github.com/budgie-desktop/budgie-desktop/commit/b07359f5c14185126ac6d780c44b25fe325c2cba

**The issue encountered**

I used `pacman -S budgie-desktop` and `pacman -S gnome` to get Budgie up and running on my new Arch install. The issue is, I don't have a window switcher at the bottom. When I attempt to add one in Raven's settings, pressing the add button does nothing. I suspected I could fix it by upgrading to the git version on the AUR, but that gave me errors about not having libwnck-3. I installed it using `pacman -S libwnck3` and now I get an error: `Could not generate cargs for libwnck-3.0:` then nothing.

Although I'm no developer, I suspect that this libwnck3 issue is involved with my inability to have a window switcher, since it seems to provide the facilities for that. However I'll leave the detective work up to those qualified for it...

**Steps to reproduce the issue**

Attempt to build the latest commit or use it with a base install of Arch

Build log:

```$ meson build --prefix=/usr --sysconfdir=/etc
The Meson build system
Version: 0.40.1
Source dir: /home/jay/Git/budgie-desktop
Build dir: /home/jay/Git/budgie-desktop/build
Build type: native build
Project name: budgie-desktop
Native c compiler: cc (gcc 6.3.1)
Native vala compiler: valac (valac 0.36.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program meson_post_install.sh found: YES (/home/jay/Git/budgie-desktop/meson_post_install.sh)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency gtk+-3.0 found: YES 3.22.15
Native dependency glib-2.0 found: YES 2.52.1
Native dependency libpeas-1.0 found: YES 1.20.0
Native dependency gdk-x11-3.0 found: YES 3.22.15
Native dependency uuid found: YES 2.29.2
Native dependency ibus-1.0 found: YES 1.5.15
Native dependency gnome-desktop-3.0 found: YES 3.24.2
Native dependency gsettings-desktop-schemas found: YES 3.24.0

Meson encountered an error in file meson.build, line 60, column 0:
Could not generate cargs for libwnck-3.0:


```

**Comment by ikeydoherty** [comment]
Looks like you're missing build dependencies, verify with:

`pkg-config --cflags --libs libwnck-3.0`

**Comment by SapiensAnatis** [comment]
I ran it, though I have no idea what the output actually means:

```$ pkg-config --cflags --libs libwnck-3.0
Package file '/usr/lib/pkgconfig/xres.pc' appears to be empty
Package 'xres' has no Name: field
```

**Comment by ikeydoherty** [comment]
OK so your xres pkgconfig is bollocksed, might need to reinstall that.

For initial clone:

```
git submodule init
git submodule update
```
