### ISSUE TITLE
[Feature Request] Change behaviour of Places applet

### ISSUE THREAD

**Issue by vanitasvitae** [budgie-desktop/budgie-desktop#924]
**Operating System**: Arch Linux
**Budgie version**: Budgie Desktop 10.3.1

I'd like to propose some changes for the places applet. Currently you have to make 3 clicks to open your home folder. Thats too much I think.

First of all, if you click the places applet, the actual "Places" category is not expanded, while the "local filesystems" (or something similar, my desktop is not english) category is.
I propose to have the places category expanded by default.

Secondly, in order to expand the places category, you have to click on the small down arrow button. I find that button too small. I'd propose to change the behaviour in a way that gets rid of the arrow button and instead enables the user to expand the places category by clicking the whole places list item.

Also there is a "." entry in the places category that produces errors for me.

Please keep up the good work! I'm very pleased with budgie desktop in general :)

**Comment by cybre** [comment]
This has been implemented in 1a8d035

**Comment by vanitasvitae** [comment]
> I suggest you open a new issue for this with some more info.

I did. See #931
