### ISSUE TITLE
Don't remove notifications applet

### ISSUE THREAD

**Issue by cavkirov** [budgie-desktop/budgie-desktop#925]
**Operating System**: e.g. Solus (latest stable version)
**Budgie version**: i.e. Budgie 10.3.1

**The issue encountered**
Icons in the top bar reverted to some Gnome-like icons. Got the Gnome foot instead for the menu for example. 

**Steps to reproduce the issue**
This occurred when I removed the notifications applet.
I have added the applet back hoping to return to the Solus defaults, but no luck. Logged out and in, also no change.

**Comment by cavkirov** [comment]
Ok, I discovered in Tweak Tools that if I changed the Appearance to Faba-Mono it seems ok. It was on Hicolor. Don't know what it was on though prior to deleting the notifications applet.

**Comment by ikeydoherty** [comment]
Closing as not an issue
