### ISSUE TITLE
Budgie applet order is not respected after editing applets

### ISSUE THREAD

**Issue by swarnendubiswas** [budgie-desktop/budgie-desktop#932]
**Operating System**: Ubuntu Gnome 17.04
**Budgie version**: Budgie 10.3.1

**The issue encountered** 
The order of applets gets messed up every time I add/remove applets.

**Steps to reproduce the issue** 
Open Raven to add a new applet. The applet gets added to the panel in the center position by default. As soon as you reposition to say the right side, the order of the other applets gets messed up. 

This generally seems to happen with user indicator applet.

![20170522_204626](https://cloud.githubusercontent.com/assets/7343807/26335234/225eecbc-3f30-11e7-8bcd-2a4ee19f71aa.jpg)

Sorry for the funny image, print screen isn't working for some reason.

**Comment by fossfreedom** [comment]
hmm

what happens if you try to repeat? - first run

    budgie-panel --replace --reset &

**Comment by swarnendubiswas** [comment]
It works, thanks.
