### ISSUE TITLE
Calendar broken integration with Google

### ISSUE THREAD

**Issue by michaeltintiuc** [budgie-desktop/budgie-desktop#934]
**Operating System**: Solus latest stable
**Budgie version**: 10.3.1

**The issue encountered**

 Adding a Google Account via online accounts does not update calendar list nor synchronization works. Removing said calendar and adding back again does not fix the issue, neither does reloading the calendar app. After several attempts online accounts report that the entered account is expired.

**Steps to reproduce the issue**
- Open calendar
- Add new Google Account
- Calendar list not updated
- Calendar no synchronized

**Comment by fossfreedom** [comment]
This is not a budgie-desktop issue per se.  Please raise this on phabricator and it will be dealt with there - https://dev.solus-project.com/maniphest/
