### ISSUE TITLE
Combo jack input source remains unchanged

### ISSUE THREAD

**Issue by michaeltintiuc** [budgie-desktop/budgie-desktop#936]
**Operating System**: Solus latest stable
**Budgie version**: 10.3.1

**The issue encountered**

 When connecting a combo jack (headphones + mic) the output is automatically switched to headphones but input remains on built-in mic, you have to manually switch it to the new input device. I can not confirm or deny if this is happening with a separate jacks or usb-type devices

**Steps to reproduce the issue**
- Connect combo jack
- Input source remains unchanged
- No input from connected mic

**Comment by JoshStrobl** [comment]
This isn't an issue with Budgie, this is enablement of particular pulseaudio connection modules that need to happen on Solus.

**Comment by michaeltintiuc** [comment]
@JoshStrobl gotcha, thanks for letting me know. Still pretty green :)
