### ISSUE TITLE
budgie-wm incrementing memory usage when wallpaper changes

### ISSUE THREAD

**Issue by wampacowboy** [budgie-desktop/budgie-desktop#938]
Operating System: Solus 2017.04.18.0
Budgie version: Budgie 10.3.1

**The issue encountered**
When switching desktop backgrounds the budgie-wm increases it's memory footprint each time the background is changed.
*noticed first using Variety wallpaper changer

"it may be the budgie-wm isn't flushing the old wallpaper from memory or something" -Justin'
"probably mutter xD" -Sunnyflunk
 ...

**Steps to reproduce the issue**
A. Use the "Change Background" option to change the desktop background
B. Use Variety wallpaper changer to automatically change background

 ...

**Comment by ikeydoherty** [comment]
This should be fixed with: https://github.com/budgie-desktop/budgie-desktop/commit/da19d50e3a3faaade3aa81b66d561aa7330f26bd

I'm putting the update into Solus for your to test.

**Comment by pauloflah** [comment]
Hello, just want to report that I'm getting this issue in the latest release of Budgie. Changing the desktop wallpaper, either through Settings -> Background or Variety, exponentially increases the memory usage of the "budgie-wm" process.

However, this only seems to affect multi-monitor setups. Currently using three monitors side-by-side @ 1920x1080. Disabling the other two extra monitors completely fixes the memory issue.

**Operating System**: Solus 3.9999
**Budgie Version**:  budgie-desktop v10.4-85-g36667bcb
**GPU**: GeForce GTX 970 w/ v390.77 (nvidia-glx-driver-current)
**Monitors** (in case it matters): Two 23" Asus VS238, one 24" Asus VS248 in the center.

**Comment by hmnd** [comment]
Experiencing same thing as @pauloflah when using Variety.

**Comment by be-gt** [comment]
![Screenshot from 2020-06-21 01-49-33](https://user-images.githubusercontent.com/67234473/85228948-01f6f300-b3e7-11ea-98bd-03be32183ce5.png)
I am also experiencing this in the latest variety & budgie-vm on an upto date Solus installation.
OS: Solus 4.1
Budgie: 10.5.1-209
Variety: 0.8.3-22
I have however only a single monitor setup.

**Comment by AndreKoepke** [comment]
Same problem with Variety.
Can we reopen this issue?

**Comment by jl-cs** [comment]
Still experience the same issue described.
Multi-monitor setup, switching backgrounds with Variety.
