### ISSUE TITLE
Problem  with colemak keyboard layout 

### ISSUE THREAD

**Issue by kohlerm** [budgie-desktop/budgie-desktop#940]
lsb_release -a
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	2017.04.18.0
Codename:	shannon

udgie-desktop --version
budgie-desktop 10.3.1
Copyright © 2014-2017 Ikey Doherty, Solus Project

when switching to the us (colemak) keyboard layout (using the budgie  keyboard layout switcher) CAPS lock does not work as expected. 
It should act like a backspace. Instead it does backspace and CAPS lock. 

Setting the layout from the command line works:
setxkbmap us -variant colemak

This is a known issue in some version of gnome, see
https://forum.colemak.com/topic/287-backspace-is-caps-lock-and-backspace/

**Comment by ikeydoherty** [comment]
Closing this due to being an upstream GNOME issue, not a Budge one.
