### ISSUE TITLE
Pressing a letter key in Files causes weird search behavior

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#941]
**Operating System**: Solus 17.04.18.0
**Budgie version**: 10.3.1
**The issue encountered**

Letter keys deliver unexpected search results.

**Steps to reproduce the issue**

Launch Files. Click on any folder in the left pane. Now switch context to the right pane by clicking on a file inside that folder. Type a letter, like "M". Files will then display all the files and folders in the right pane which merely contain, but don't necessarily start with, the letter "M". This is more annoying than helpful.

**Comment by JoshStrobl** [comment]
This isn't a Budgie issue. This is a Nautilus issue. Nautilus uses type-ahead searching, which means when you start typing, it searches.
