### ISSUE TITLE
Inconsistant Raven Behavior

### ISSUE THREAD

**Issue by Ubluntu1604** [budgie-desktop/budgie-desktop#944]
OS: Arch Linux 4.11.3
Budgie Version: 10.3.1

**The issue encountered**

Raven only closes when clicked out of into a window (active or inactive). It does not do this when clicking out to the desktop.

**Steps to reproduce the issue**

Open a window (terminal, browser, anything), open Raven, then click on the window. Raven should close.
Close the window, open raven, and click on space of unoccupied desktop. Raven will not close.

Not sure if this is a bug, but behavior should probably be consistant in both scenarios.

**Comment by ikeydoherty** [comment]
Works for me. You'll need to provide any output logs for `budgie-wm` and `budgie-panel` so we can see where they went wrong.

**Comment by Ubluntu1604** [comment]
Using GNOME 3.24.2
`budgie-panel` gives no errors when I replace it (or try to replicate the issue) 
But `budgie-wm` gives 

>** Message: ibus.vala:51: ibus-daemon unsupported on this system
>(budgie-wm:6701): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
>(budgie-wm:6701): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

 I also receive this message anytime I click on a tray icon.

>Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c00007 (budgie-pan)

**Comment by ikeydoherty** [comment]
OK so it looks like budgie-wm doesn't get any further due to the ibus thing being wonky. Are you using `budgie-desktop-git` or `budgie-desktop` ? Curious as to whether this is fixed in master. Also how come you have no ibus? :)

**Comment by Ubluntu1604** [comment]
Using the non-git `budgie-desktop`.
As for ibus, I am not entirely sure. It is supposed to be shipped with GNOME3 (which I do have installed)
It could also be that I may have removed it. I try to keep my system tidy since it is a toaster.
Anything not 100% neccesary gets removed.
