### ISSUE TITLE
Enable hibernation by default in Ubuntu Budgie

### ISSUE THREAD

**Issue by sidahmed-malaoui** [budgie-desktop/budgie-desktop#946]
**Operating System**: Ubuntu Budgie 17.04
**Budgie version**: budgie-desktop 10.3.1

I hope this is the right place to give this feature request.

To activate hibernation on ubuntu-budgie, I had to go through some pretty complicated and long procedure that you can find right  [here](https://askubuntu.com/questions/913517/cannot-hibernate-ubuntu-budgie-17-04?noredirect=1#comment1438642_913517) .

So can you please enable hibernation by default on Ubuntu Budgie.

PS: budgie-desktop really rocks. Really good job guys.

**Comment by fossfreedom** [comment]
This is the upstream issues tracker for the budgie-desktop interface itself.  Distro specific issues should be reported on their appropriate issue tracker - in this case https://github.com/UbuntuBudgie/budgie-desktop-environment

thanks.

**Comment by sidahmed-malaoui** [comment]
Thanks, I will post this feature request there.
