### ISSUE TITLE
Center applets are not in the middle

### ISSUE THREAD

**Issue by ferike1** [budgie-desktop/budgie-desktop#948]
**Operating System**: Solus 2017.04.18.0 64-bit
**Budgie version**: 10.3.1

**The issue encountered**

I've been messing around with applets to really make Solus my own, and I've decided to put an Icon Task List applet in the center. However, I have noticed that the icons are not really aligned in the middle.

See in this picture:
http://i.imgur.com/0eryWHF.png

You can see it compared to the Google Play Music player controls, that it's a bit off to the left. I've also marked the center area of the screen with yellow for reference.

Reference from the Solus forums:
https://solus-project.com/forums/viewtopic.php?f=14&t=8197

**Comment by ferike1** [comment]
I've also noticed that it is the same on the login screen (can't take a screenshot of it). The time in the top panel is slightly to the left, it's more noticeable there.

**Comment by tristan957** [comment]
They aren't centered because they are merely splitting the empty space on either side. More of a feature request than a bug

**Comment by ferike1** [comment]
I understand, however an official forum agreed that this is an issue, and he suggested to post it here.

**Comment by ikeydoherty** [comment]
He said to report it here, he didn't agree it was an issue. The icon tasklist applet is a poor demonstration of centering as it internally uses margins to offset the pinned from the non pinned icons, thus it can never truly be visibly centered.

**Comment by ferike1** [comment]
I just quoted his words saying "please lodge the issue". If it can't be centered, then it can't, I accept that :)

**Comment by ferike1** [comment]
I have recently noticed that the time on the login screen is also a bit off to the left, see the attachment. I suppose that something might still be wrong with the panel, this is the default layout for it on the login screen. Couldn't the center area be absolutely positioned instead of margins?

![img_20170726_195405](https://user-images.githubusercontent.com/29072315/28636537-b90e027e-723e-11e7-8f37-144bd4b4a07c.jpg)

**Comment by tristan957** [comment]
That is a LightDM GTK Greeter issue

**Comment by ikeydoherty** [comment]
Yeah thats not Budgie, sorry :')
