### ISSUE TITLE
Unable to change language in lock screen

### ISSUE THREAD

**Issue by KeltarHelviett** [budgie-desktop/budgie-desktop#949]
**Operating System**: Solus 2017.04.18.0 64-bit
**Budgie version**: budgie-desktop 10.3.1

**The issue encountered**

You're not able to change language in lock screen, so you're not able to unlock in situation when you forgot to change language back to English. (Instead of changing the language Super + Space provided space character)

**Steps to reproduce the issue**

1. Add Russian language in Settings-Region&Language-InputSources.
2. Super + Space to change language to Russian.
3. Super + L to lock the screen.
4. You're not able to unlock, because you are not able to change language.

**All we need**
Is language changer like in Login screen or correct Super+Space shortcut.
By the way, your DE is awesome as well as Solus, but this kind of things really annoy users. If I forget to change language to English I will have to log in from console and reboot. That's pretty bad and may cause problems if you have something unsaved.
Wish it'll be fixed soon.

**Comment by fossfreedom** [comment]
This is an issue with gnome-screensaver - not budgie-desktop directly.

There is an existing issue that covers this so I'll dupe it against that

https://github.com/budgie-desktop/budgie-desktop/issues/788

**Comment by savelmtr** [comment]
I'm here from 2024 and the problem still has not been solved.
