### ISSUE TITLE
Start app Firefox visual bug, after reboot

### ISSUE THREAD

**Issue by addeps3** [budgie-desktop/budgie-desktop#952]
**Operating System**: Solus 2017.04.18.0 64-bit
**Budgie version**:  budgie-desktop 10.3.1

**The issue encountered**

 Firefox window wrong size, and black area over background image when rebooted and starting app Firefox. 

**Steps to reproduce the issue**
Use FF, with multiple tabs, close FF presuming session is saved, reboot machine, and start FF..

 ...
![screenshot from 2017-06-14 21-54-26](https://user-images.githubusercontent.com/18384170/27152275-a567f7a0-514d-11e7-90d5-365b35439525.png)

**Comment by ikeydoherty** [comment]
There is an issue template so that you actually fill it in.

**Comment by addeps3** [comment]
I cant offer a terminal-output of this bug ASAP so closing for now.
