### ISSUE TITLE
pushed the meson to native so actual build failure i guess

### ISSUE THREAD

**Issue by SolarAquarion** [budgie-desktop/budgie-desktop#959]
**Operating System**: Archlinux
**Budgie version**: latest stable
AILED: src/appsys/appsys@sta/src_appsys_appsys@sta_AppSystem.c.o 
cc  -Isrc/appsys/appsys@sta -Isrc/appsys -I../src/appsys -Isrc/config -I../src/config -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -std=c11 -O0 -g -fstack-protector -pedantic -Wstrict-prototypes -Wundef -Werror-implicit-function-declaration -Wformat -Wformat-security -Werror=format-security -Wconversion -Wunused-variable -Wunreachable-code -Wall -W -DGDK_VERSION_MAX_ALLOWED=GDK_VERSION_3_18 -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_18 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_46 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_46 '-DGETTEXT_PACKAGE="budgie-desktop"' -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIC -pthread -DWNCK_I_KNOW_THIS_IS_UNSTABLE -MMD -MQ 'src/appsys/appsys@sta/src_appsys_appsys@sta_AppSystem.c.o' -MF 'src/appsys/appsys@sta/src_appsys_appsys@sta_AppSystem.c.o.d' -o 'src/appsys/appsys@sta/src_appsys_appsys@sta_AppSystem.c.o' -c 'src/appsys/appsys@sta/AppSystem.c'
src/appsys/appsys@sta/AppSystem.c:17:10: fatal error: BudgieAppSystem.h: No such file or directory
 #include "BudgieAppSystem.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[29/232] Compiling C object 'src/imports/natray/natray@sta/na-tray-manager.c.o'.
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_handle_dock_request’:
../src/imports/natray/na-tray-manager.c:277:24: warning: conversion to ‘Window {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
   Window icon_window = xevent->data.l[2];
                        ^~~~~~
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../src/imports/natray/na-tray-manager.h:28,
                 from ../src/imports/natray/na-tray-manager.c:25:
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_handle_message_data’:
/usr/include/glib-2.0/glib/gmacros.h:291:20: warning: conversion to ‘int’ from ‘long int’ may alter its value [-Wconversion]
 #define MIN(a, b)  (((a) < (b)) ? (a) : (b))
                    ^
../src/imports/natray/na-tray-manager.c:342:10: note: in expansion of macro ‘MIN’
    len = MIN (msg->remaining_len, 20);
          ^~~
../src/imports/natray/na-tray-manager.c:345:20: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
     &xevent->data, len);
                    ^~~
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_handle_begin_message’:
../src/imports/natray/na-tray-manager.c:420:28: warning: conversion to ‘gsize {aka long unsigned int}’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
       msg->str = g_malloc (msg->len + 1);
                            ^~~
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_set_padding_property’:
../src/imports/natray/na-tray-manager.c:664:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gint {aka int}’ may change the sign of the result [-Wsign-conversion]
   data[0] = manager->padding;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_set_icon_size_property’:
../src/imports/natray/na-tray-manager.c:692:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gint {aka int}’ may change the sign of the result [-Wsign-conversion]
   data[0] = manager->icon_size;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_set_colors_property’:
../src/imports/natray/na-tray-manager.c:720:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[0] = manager->fg.red * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:721:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[1] = manager->fg.green * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:722:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[2] = manager->fg.blue * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:723:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[3] = manager->error.red * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:724:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[4] = manager->error.green * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:725:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[5] = manager->error.blue * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:726:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[6] = manager->warning.red * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:727:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[7] = manager->warning.green * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:728:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[8] = manager->warning.blue * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:729:13: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[9] = manager->success.red * 65535;
             ^~~~~~~
../src/imports/natray/na-tray-manager.c:730:14: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[10] = manager->success.green * 65535;
              ^~~~~~~
../src/imports/natray/na-tray-manager.c:731:14: warning: conversion to ‘gulong {aka long unsigned int}’ from ‘gdouble {aka double}’ may alter its value [-Wfloat-conversion]
   data[11] = manager->success.blue * 65535;
              ^~~~~~~
../src/imports/natray/na-tray-manager.c: In function ‘na_tray_manager_manage_screen_x11’:
../src/imports/natray/na-tray-manager.c:813:23: warning: conversion to ‘long int’ from ‘Atom {aka long unsigned int}’ may change the sign of the result [-Wsign-conversion]
       xev.data.l[1] = gdk_x11_atom_to_xatom_for_display (display,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkx.h:54:0,
                 from /usr/include/gtk-3.0/gtk/gtksocket.h:34,
                 from /usr/include/gtk-3.0/gtk/gtkx.h:29,
                 from ../src/imports/natray/na-tray-child.h:25,
                 from ../src/imports/natray/na-tray-manager.h:30,
                 from ../src/imports/natray/na-tray-manager.c:25:
/usr/include/gtk-3.0/gdk/x11/gdkx11window.h:108:39: warning: conversion to ‘long int’ from ‘Window {aka long unsigned int}’ may change the sign of the result [-Wsign-conversion]
 #define GDK_WINDOW_XID(win)           (gdk_x11_window_get_xid (win))
                                       ^
../src/imports/natray/na-tray-manager.c:815:23: note: in expansion of macro ‘GDK_WINDOW_XID’
       xev.data.l[2] = GDK_WINDOW_XID (window);
                       ^~~~~~~~~~~~~~
[33/232] Compiling C object 'src/theme/budgietheme@sha/src_theme_budgie-theme-resources.c.o'.
ninja: build stopped: subcommand failed.

**Comment by fossfreedom** [comment]
no - exactly the same issue - meson is broken.  meson v0.37-0.40 all work 

meson broke something since then.

**Comment by SolarAquarion** [comment]
A hah so it doesn't matter if it's git or not. Huh

**Comment by fossfreedom** [comment]
I've raised on the meson tracker - please add any additional info that you can here.

thanks

https://github.com/mesonbuild/meson/issues/1969
