### ISSUE TITLE
Feature: Adding scroll speed option to "Mouse & Touchpad"

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#961]
Dear all, 

As discussed on the forums [Adding scroll speed to "Mouse & Touchpad"?](https://solus-project.com/forums/viewtopic.php?p=25226#p25226), I would like to request a setting being added to the great "Mouse & Touchpad" GUI for people to adjust the scroll speed of the touchpad.

This setting would be of great use, I believe, aside the already existing options. 

What do you think?

**Comment by tristan957** [comment]
Currently Budgie is using the GNOME Control Center. This request should be filed with GNOME. Luckily Budgie 11 will have a new control center though, and I'm sure Ikey will be taking opinions on what settings to include in the GUI

**Comment by orschiro** [comment]
Thanks, @tristan957! Shall we thus close this for now as not applicable?

**Comment by ikeydoherty** [comment]
I reckon close it for now but keep it in mind, if thats alright? This way we can work out what is immediately applicable. And fwiw - I'm in agreement with this bug

**Comment by orschiro** [comment]
I will keep it in mind, thank you, @ikeydoherty!

**Comment by alex-c3** [comment]
Any news on this feature ? Ubuntu Budgie 22.10 doesn't seem to have it yet.

**Comment by tristan957** [comment]
I think GNOME Control Center now has this for 44, but I think the Budgie fork is pretty old at this point. Presumably someone could port the functionality to the Budgie fork.
