### ISSUE TITLE
Main Menu appears in wrong inital position

### ISSUE THREAD

**Issue by D8174** [budgie-desktop/budgie-desktop#963]
**Operating System**: Debian Stretch
**Budgie version**: Budgie 10.2.9

[Video (YouTube)](https://www.youtube.com/watch?v=n020NeMLWeE)

Menu appears higher than it should be, then snaps to the correct position.
Looks like it appears where it would be if the panel were at the top, rather than the bottom.

**Comment by orschiro** [comment]
Cannot confirm this on Budgie 10.3.1. Can you update your version?

**Comment by D8174** [comment]
Updated to 10.3.1 but issue still there.

**Comment by D8174** [comment]
Didn't mean to close.

**Comment by fossfreedom** [comment]
This has just been resolved in hit and will be available with the next release of budgie desktop.

When released I will upload this to sid/buster
