### ISSUE TITLE
Budgie crashes at login when VBoxGuestAdditions are installed

### ISSUE THREAD

**Issue by catleeball** [budgie-desktop/budgie-desktop#967]
**Operating System**: Ubuntu 17.04 Zesty
**Budgie version**: budgie-desktop 10.2.9

**The issue encountered**
After entering password at login prompt, Budgie desktop environment crashes briefly, then returns to the login screen. This only happens while VBoxGuestAdditions are installed.

**Steps to reproduce the issue**
This occurs for me after installing the latest release of [Ubuntu Budgie](https://ubuntubudgie.org/downloads) in a VirtualBox VM. The VM worked fine until I tried to install VBoxGuestAdditions. After installing them, rebooting, then attempting to log in, Budgie persistently crashed after login, returning me to the login prompt. Via SSH I uninstalled guest additions, rebooted the VM, and it began working fine again.

This occurs using VirtualBox 5.1.22 r115126 (Qt5.6.2) running on Mac OS 10.12.5 with the guest additions bundled with VirtualBox.

Here's a snippit from my syslog ([full log here](https://gist.githubusercontent.com/anonymous/ffcd92901316146ae26a6ec911ae77b6/raw/0e9ca98f7de78ac092a75d84f21272bd0eaf133e/syslog)):
```
Jun 25 18:36:29 budgie-vm at-spi-bus-launcher[1485]: Activating service name='org.a11y.atspi.Registry'
Jun 25 18:36:29 budgie-vm at-spi-bus-launcher[1485]: Successfully activated service 'org.a11y.atspi.Registry'
Jun 25 18:36:29 budgie-vm org.a11y.atspi.Registry[1490]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Jun 25 18:36:29 budgie-vm budgie-wm.desktop[3426]: Window manager error: Failed to get proc address for 'eglGetPlatformDisplayEXT'
Jun 25 18:36:29 budgie-vm gnome-session[3132]: gnome-session-binary[3132]: WARNING: App 'budgie-wm.desktop' exited with code 1
Jun 25 18:36:29 budgie-vm gnome-session-binary[3132]: WARNING: App 'budgie-wm.desktop' exited with code 1
Jun 25 18:36:29 budgie-vm budgie-wm.desktop[3441]: Window manager error: Failed to get proc address for 'eglGetPlatformDisplayEXT'
Jun 25 18:36:29 budgie-vm gnome-session[3132]: gnome-session-binary[3132]: WARNING: App 'budgie-wm.desktop' exited with code 1
Jun 25 18:36:29 budgie-vm gnome-session[3132]: gnome-session-binary[3132]: WARNING: App 'budgie-wm.desktop' respawning too quickly
Jun 25 18:36:29 budgie-vm gnome-session-binary[3132]: WARNING: App 'budgie-wm.desktop' exited with code 1
Jun 25 18:36:29 budgie-vm gnome-session-binary[3132]: Unrecoverable failure in required component budgie-wm.desktop
Jun 25 18:36:29 budgie-vm gnome-session[3132]: gnome-session-binary[3132]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Jun 25 18:36:29 budgie-vm gnome-session-binary[3132]: WARNING: App 'budgie-wm.desktop' respawning too quickly
Jun 25 18:36:29 budgie-vm gnome-session-binary[3132]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Jun 25 18:36:29 budgie-vm org.a11y.atspi.Registry[1490]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Jun 25 18:36:29 budgie-vm org.a11y.atspi.Registry[1490]:       after 21 requests (21 known processed) with 0 events remaining.
Jun 25 18:36:30 budgie-vm lightdm[1080]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Let me know if you need any other info or if there's any way I can assist in reproducing the bug.

**Comment by fossfreedom** [comment]
have you got 3D acceleration ticked in the VM settings or unticked?

Try ticking/unticking this setting.

**Comment by catleeball** [comment]
That worked! Thanks a bunch for the tip. I'll close out this bug then if it's already a known issue.
