### ISSUE TITLE
Panel disappearing when opening menu with raven open

### ISSUE THREAD

**Issue by JoeAlden** [budgie-desktop/budgie-desktop#969]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: Budgie 10.3.1

**The issue encountered**:
When the Budgie panel is configured to be at the bottom of the screen, opening the Budgie Menu with the super/meta key whilst Raven is open causes the entire panel to become invisible.

**Steps to reproduce the issue**:
- Configure the Budgie panel to be at the bottom of the screen
- Open Raven
- Press the super/meta key

This was tested on my desktop, my laptop, and on a fresh ISO in live preview (VM). On all systems the bug occurs.

I am wondering if this might be a non issue in the upcoming Budgie update?

**Comment by ikeydoherty** [comment]
Fixed in git already, and a duplicate :) This'll be resolved in the next update (soon ™)

**Comment by ikeydoherty** [comment]
(The new popover stuff fixed it, fwiw)

**Comment by fossfreedom** [comment]
Yep. Can confirm that this is now fixed in git and will be in the next release.

**Comment by JoeAlden** [comment]
My apologies, I clearly didn't look hard enough to see if there was already an issue :/ Looking forward to the update :)

**Comment by ikeydoherty** [comment]
S'ok GitHub is hard to search for issues tbqh (when we have as many open as we do.. :))
