### ISSUE TITLE
Suggestion: Sort unread notifications with most recent first

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#970]
Currently, you need to scroll down to see the most recent unread notification. I suggest to revert it and show the most recent unread notification at the top.

What do you think?

**Comment by fossfreedom** [comment]
similar discussion here on a revamped raven - https://github.com/budgie-desktop/budgie-desktop/issues/763

**Comment by ikeydoherty** [comment]
We already list the newest first in the list in git

**Comment by orschiro** [comment]
Looking forward to the Git version, thank you.
