### ISSUE TITLE
Strange issue with builtin theme

### ISSUE THREAD

**Issue by Ste74** [budgie-desktop/budgie-desktop#972]
Hi guys , yesterday i have released the Manjaro 17.0.2 with Budgie as DE . Only a little issue with the theme : i have forked the arc theme and created the arc-theme-maia ( during the compiing the arc theme i have changed any bluish color with our maia color ) and use this in the ISO . So at last i have only changed the color . Now the issue : if i set buildin theme to false i obtain this behaviour
[see here](https://forum.manjaro.org/t/manjaro-budgie-17-0-2/26747/2).
Any idea why ?

**Comment by ikeydoherty** [comment]
Because your theme doesn't support Budgie. The built in theme does. Surely you know what your own theme supports? :P

**Comment by Ste74** [comment]
Hi @ikeydoherty , arc-theme support budgie so if you see my pkgbuild , this build on the fly the maia version without fork the upstream .. maybe , at last i can see if arc-theme have this issue :| not checked now because i'm at work ..when come back to home will check it 
https://github.com/manjaro/packages-community/blob/master/arc-themes-maia/PKGBUILD

**Comment by ikeydoherty** [comment]
No it doesn't support Budgie. The Arc theming support for Budgie lives only inside Budgie itself :)

**Comment by tristan957** [comment]
@Ste74 here is the relevant part of the README: https://github.com/budgie-desktop/budgie-desktop#theming. Might be fairly easy to change using sed to replace colors. Good Luck!

**Comment by Ste74** [comment]
@tristan957 , thank you .. i see the hardcoding for the theme ... 
@ikeydoherty you do more work for me 😜 , if modify the theme i need to found how menage this because arc-theme and arc-maia-theme can be installed at the same time but with this i can't or not ?

**Comment by ikeydoherty** [comment]
The desktop has to have builtin fallback theming, which happens to be styled like Arc, regardless of the theme. When the theme supports Budgie (Which this one does not) - then builtin-theme should be turned off. Until that point it should really stay on, otherwise its .. yknow, bad looking.

**Comment by Ste74** [comment]
Forgot to close this via https://github.com/manjaro/desktop-settings/commit/e9b8bd605592d36e10d7f7beaec1e161efd4b293#diff-b3221a8165ac9623b4850b713d4d352f
