### ISSUE TITLE
problem with keyboard layouts

### ISSUE THREAD

**Issue by amirniknami** [budgie-desktop/budgie-desktop#973]
hi . i found a bug in the budgie desktop . when you use 2 keyboard layouts in 2 different languages and the system locks when you do not use it for couple  of minutes . you can not change keyboard layout with and without the shortcut . please fix this problem . thank you . btw. i use budgie solus

**Comment by fossfreedom** [comment]
Hi,
  this has been reported a few times.  This is a gnome-screensaver issue - not budgie-desktop per se.

As such I will mark this as a duplicate: https://github.com/budgie-desktop/budgie-desktop/issues/788

**Comment by ikeydoherty** [comment]
Really need to find a way to kill GSS :(

**Comment by amirniknami** [comment]
i think this is a huge problem . i lost some of my code due to this problem . i had to switch back to linuxmint again . thanks.

**Comment by amirniknami** [comment]
yes i am talking about htat . i will check it  .thanks

**Comment by amirniknami** [comment]
i do not see the input next to the box .in budgie solus i just have the box alone

**Comment by fossfreedom** [comment]
hmm - must be one of the many patches Ubuntu has in its version of gnome-screensaver that Ubuntu Budgie has inherited.

**Comment by ikeydoherty** [comment]
Maybe we should inherit this in Solus too ..

**Comment by amirniknami** [comment]
yeah . it would be great . because this would be the only reason could make me to go back to linux mint again . and i do not want to do that because solus is greate
