### ISSUE TITLE
Suggestion: increase volume > 100% using the hotkeys or the applet icon

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#974]
Maybe through an optional setting. Currently, the user always needs to open the settings, go to sound and increase the level there.

What do you think?

**Comment by ikeydoherty** [comment]
Sure as long as its visible to the user they're going over 100% :) I'm actually sorta tempted to "fix" the sound applet to be better. As for the sound keys we're actually restricted by GNOME Settings Daemon there and can't fix that bit yet

**Comment by fossfreedom** [comment]
This looks like a similar/same issue https://github.com/budgie-desktop/budgie-desktop/issues/626

**Comment by orschiro** [comment]
@fossfreedom, correct, closing this one. 

Let's ignore the sound keys then until we move to Qt. Remember for the future that Ubuntu Unity had an excellent implementation.

Moving over to the other discussion but tempted to ask:

> Sure as long as its visible to the user they're going over 100% :) 

Maybe visually with a black colour up to 100% and with a red colour for over 100%?

> I'm actually sorta tempted to "fix" the sound applet to be better. 

Cool, already any concrete ideas?
