### ISSUE TITLE
raven settings move buttons hidden

### ISSUE THREAD

**Issue by julius16** [budgie-desktop/budgie-desktop#977]
**Operating System**:  Solus 2017.04.18.0
**Budgie version**:  Budgie 10.3.1

**The issue encountered**

settings (Raven): move buttons were not immediately visible (1280x720p)

**Steps to reproduce the issue**

- Panel settings (Raven): after adding stuff, I failed to move it for minutes because the move buttons were not immediately visible, but had to be scrolled down to (1280x720p) which I did not know / understand

**Comment by tristan957** [comment]
Adding a screenshot would probably be helpful!

**Comment by fossfreedom** [comment]
sounds like this issue - https://github.com/budgie-desktop/budgie-desktop/issues/678

**Comment by julius16** [comment]
Yes, that's the same issue.
