### ISSUE TITLE
budgie-panel 10.3.1 crashes

### ISSUE THREAD

**Issue by Dominator86** [budgie-desktop/budgie-desktop#980]
budgie-panel crashes immediately on launch on my Arch Linux machine after upgrading the budgie-desktop package from 10.2.9 to 10.3.1.

Terminal output: [https://pastebin.com/C57UAgna](https://pastebin.com/C57UAgna)

Unfortunately I skipped 10.3.0 so I don't know for sure if the problem existed there already but it's very likely.

**Comment by ikeydoherty** [comment]
The package will need these fixes:

https://github.com/budgie-desktop/budgie-desktop/commit/07b5ce0a12f8fadba9bb7941b0874db5493ef034
https://github.com/budgie-desktop/budgie-desktop/commit/c8950712cb95a257e9b08fd11507070f0c221d39

These were fixed post release and we're building up to a new release now

**Comment by fossfreedom** [comment]
since this has been resolved in git we'll keep the issue tracker tidy by  closing this for now.  Feel free to comment on the issue if you have this issue reoccur after applying those two commits.
