### ISSUE TITLE
[Enhancement] Multiple windows icon indicator instead of separate icons on panel

### ISSUE THREAD

**Issue by WRostom** [budgie-desktop/budgie-desktop#985]
The budgie panel gets really cluttered after a number of windows are opened. Especially from apps like Chrome and Nautilus. Maybe you can add some sort of stacked icon indicator like in Windows or add multiple dashes under an icon to indicate multiple windows. I think this would be much cleaner.

**Comment by orschiro** [comment]
I like this idea. I imagine to click on Chrome's icon in the panel to unfold a list of entries with each entry corresponding to the name of an open window.

**Comment by GladOSkar** [comment]
There is an age old issue for this: #278

**Comment by fossfreedom** [comment]
thanks for the pointer - I'll close this as a duplicate so we can keep the issue tracker tidy.
