### ISSUE TITLE
Inconsistency between single click and double click when selecting files

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#986]
Most interactions with files and folders require a double click to select and open. 

Can someone please confirm the following inconsistency:

1. From Chrome, select a file to upload
2. It opens the "Open Files" dialog
3. Open a folder from the sidebar
4. Select a file with a single click

Instead of marking the file as selected, it directly opens it and closes the "Open Files" dialog. I expect this to only happen on a double click but not a single click.

**Comment by MggMuggins** [comment]
I would expect the "Open Files" to be part of GTK, not Budgie. Could you maybe take an image or two that explains what is going on there?

**Comment by ikeydoherty** [comment]
I hate the Gtk3 file chooser..

**Comment by orschiro** [comment]
I tried to capture the problem in the following video:

https://www.useloom.com/share/cd0cdc0a74534fe5b9c0568c385e8c9b

**Comment by MggMuggins** [comment]
I agree completely with pretty much everything you said in there. Good video too, thanks for that. In response to your questions at the end, I'm 99% sure it's an issue with GTK's file chooser. You could file a report against them, or simply wait for Budgie 11 and Qt, which shouldn't have that problem.

**Comment by orschiro** [comment]
Thank you. I believe I found the problem:

https://bugzilla.gnome.org/show_bug.cgi?id=758065

**Comment by fossfreedom** [comment]
Well found!  Given that it isn't budgie desktop per se, we'll keep the issue tracker tidy by closing this.

cheers.

**Comment by ikeydoherty** [comment]
Here's hoping they revert it
