### ISSUE TITLE
Direct access to advanced sound settings from panel icon or sidebar

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#990]
Other settings can be accessed either through the panel icon or the sidebar.

Example:

The advanced power settings can be accessed from the battery panel icon by performing a left mouse click and then a subsequent mouse click on "Power settings".

**Comment by Xmetalfanx** [comment]
I am not in Budgie atm though this sounds like what some other DEs do, and a good idea ... instead of having to go to the control panel then sound and there are the "advanced sound settings" .. .just have a small option to open it directly say under the volume slider.

**Comment by fossfreedom** [comment]
This is resolved in git - https://github.com/budgie-desktop/budgie-desktop/commit/1f6504013fbc326eae01ee952463965af181e1fd

now have direct access to the sound panel in the control panel.

**Comment by orschiro** [comment]
This is great, thank you.
