### ISSUE TITLE
Chrome opens window attached to pinned panel icon whereas LO Writer does not

### ISSUE THREAD

**Issue by orschiro** [budgie-desktop/budgie-desktop#995]
**Operating System**: Solus Budgie 2017.04.18.0 
**Budgie version**: budgie-desktop 10.3.1

**The issue encountered**

If you click on the pinned Chrome panel icon, the opened window is attached to this pinned icon. If you do the same with LibreOffice Writer, however, it sometimes does not attach the new window to the pinned icon but creates a new icon.

**Steps to reproduce the issue**

Click on the pinned LibreOffice Writer icon.

**Screenshot**

![image](https://user-images.githubusercontent.com/170947/27777929-7ec9fb98-5fb7-11e7-810d-b23d487e497b.png)

**Comment by ikeydoherty** [comment]
This explains nothing.. There is an issue template for a reason, please use it.

**Comment by orschiro** [comment]
My apologies, @ikeydoherty. You are completely right. I should have taken more care when creating the issue. I expanded on my first comment but will actually close it because it's working now.

Should the issue occur again, I will reopen it. 

Thank you for your feedback! That was helpful. :-)

**Comment by ikeydoherty** [comment]
Alright cheers dude. FWIW I try to keep the issues trimmed down here and if there a reason to shut them down I'll prefer it, because we have lots of issues, so lots of work. :)
